### ISSUE TITLE
Windows11 Edge 浏览器插件无法获取网页信息

### ISSUE THREAD

**Issue by yhyu13** [QwenLM/Qwen-Agent#10]
已经Add to Qwen's Reading list了。但是还是没有获取到网页内容

![WzPKWJDprE](https://github.com/QwenLM/Qwen-Agent/assets/19365678/0dc48e4c-da47-490a-9bb0-c8d006c86bd5)

浏览器插件没法直接分析网页内容，作为prompt的一部分发给模型？为什么需要reading list? 

我在用的另一个浏览器LLM插件就蛮好的，Fission https://github.com/josStorer/chatGPTBox。
但是需要一套openai api适配。千问有平替/适配openai api的计划吗

**Comment by liaoweiguo** [comment]
插件支持safari吗

**Comment by tuhahaha** [comment]
您好，BrowserQwen是利用Qwen模型理解网页，是可以在网页端问答的。Reading list是出于保护隐私的目的，Qwen仅分析用户主动添加的页面，这些记录的页面将用于多页问答或写作。我们这边目前仅测试过Google浏览器，暂时没有测试过其他浏览器，可能存在未知错误，您可以把后台输出截图下吗？

**Comment by tuhahaha** [comment]
另外，Qwen开源模型目前实现适配[openai api](https://github.com/QwenLM/Qwen#api)接口，BrowserQwen的模型本地部署也是用的这个接口。

**Comment by yhyu13** [comment]
> 另外，Qwen开源模型目前实现适配[openai api](https://github.com/QwenLM/Qwen#api)接口，BrowserQwen的模型本地部署也是用的这个接口。

我之前说用dashscope api平替掉openai api。后来发现有https://github.com/songquanpeng/one-api了，所以不用了

**Comment by JianxinMa** [comment]
我自己测试Windows 11 + Edge + WSL2装插件目前普通网页没有遇到问题，仅PDF则还有待修的问题。如果有遇到Edge报错，欢迎截下报错信息，以便我们排查。
