### ISSUE TITLE
function calling的prompt

### ISSUE THREAD

**Issue by jiangix-paper** [QwenLM/Qwen-Agent#100]
你好，如果是本地通过vllm部署qwen1.5 chat模型。想调用function calling函数，需要自己在prompt中拼装function calling的格式吗？如果是的话，具体的prompt是怎样的呢？
还是说可以直接通过vllm的openai接口传入function calling呢

希望收到您的回复，非常感谢

**Comment by JianxinMa** [comment]
见 https://github.com/QwenLM/Qwen-Agent/issues/99#issuecomment-2014653140 的回复。

如果不想自己写prompt，也可以用qwen-agent的封装，参考：https://github.com/QwenLM/Qwen-Agent/blob/main/examples/function_calling.py

**Comment by jiangix-paper** [comment]
非常感谢您的回复，如果采用qwen-agent的封装，是不是后台的接口就不用采用vllm来启动了？需要使用dashscope吗

**Comment by tuhahaha** [comment]
后台可以使用vllm或dashscope都可以的 @jiangix-paper
