### ISSUE TITLE
qwen_agent目录下的代码，能单独发布一个包吗？

### ISSUE THREAD

**Issue by tiejunhu** [QwenLM/Qwen-Agent#107]
想依赖其中的部分代码，但不想引入整个项目的所有依赖

**Comment by JianxinMa** [comment]
安装readme的这个说明用pip的方式安装，就是只会安装 qwen_agent 目录下的东西的。其他的比如browser_qwen、qwen_server都不会安装到。
```
# Install dependencies.
git clone https://github.com/QwenLM/Qwen-Agent.git
cd Qwen-Agent
pip install -e ./
```
但 https://github.com/QwenLM/Qwen-Agent/blob/main/requirements.txt 里面有一些依赖是qwen_agent目录用不到的，比如 gradio 就用不到，具体您可以看下是不是需要修改下 requirements.txt 去掉一些没必要的依赖。

**Comment by JianxinMa** [comment]
发布了0.0.1版本到pypi了：https://pypi.org/project/qwen-agent/

同时改了下setup.py和requirement.txt，避免安装不必要的内容。
