### ISSUE TITLE
Error code: 404 - {'object': 'error', 'message': 'The model `/data/Qwen1.5-72B-Chat` does not exist.', 'type': 'NotFoundError', 'param': None, 'code': 404}

### ISSUE THREAD

**Issue by Modas-Li** [QwenLM/Qwen-Agent#110]
Error code: 404 - {'object': 'error', 'message': 'The model `/data/Qwen1.5-72B-Chat` does not exist.', 'type': 'NotFoundError', 'param': None, 'code': 404}

**Comment by YangYang-ynu** [comment]
如果启用的是vllm将本地模型的openaiapi服务，可以试着将model变量更改为启用vllm推理的模型位置
