### ISSUE TITLE
Error code: 400 - {'object': 'error', 'message' 'max_tokens must be at least 1, got -2815., 'type' 'BadRequestError', 'param': None, 'code': 400}

### ISSUE THREAD

**Issue by Modas-Li** [QwenLM/Qwen-Agent#111]
Error code: 400 - {'object': 'error', 'message' 'max_tokens must be at least 1, got -2815., 'type' 'BadRequestError', 'param': None, 'code': 400}

**Comment by Modas-Li** [comment]
INFO 04-02 14:55:30 async_llm_engine.py:508] Received request cmpl-b0572d1cb5534a5b9ccb40d91617eb16: prompt: '<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n请提取问题中的关键词，需要中英文均有，可以适量补充不在问题中但相关的关键词。关键词尽量切分为动词/名词/形容词等类型，不要长词组。关键词以JSON的格式给出，比如{"keywords_zh": ["关键词1", "关键词2"], "keywords_en": ["keyword 1", "keyword 2"]}\n\nQuestion: 这篇文章的作者是谁？\nKeywords: {"keywords_zh": ["作者"], "keywords_en": ["author"]}\nObservation: ...\n\nQuestion: 解释下图一\nKeywords: {"keywords_zh": ["图一", "图 1"], "keywords_en": ["Figure 1"]}\nObservation: ...\n\nQuestion: 核心公式\nKeywords: {"keywords_zh": ["核心公式", "公式"], "keywords_en": ["core formula", "formula", "equation"]}\nObservation: ...\n\nQuestion: 上证指数多少点\nKeywords:\n<|im_end|>\n<|im_start|>assistant\n', sampling_params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.7, top_p=1.0, top_k=-1, min_p=0.0, seed=None, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=['✿RESULT✿', '✿RESULT✿:', '✿RESULT✿:\n', 'Observation:', 'Observation:\n'], stop_token_ids=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=300, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt_token_ids: [151644, 8948, 198, 2610, 525, 264, 10950, 17847, 13, 151645, 198, 151644, 872, 198, 14880, 107439, 86119, 101047, 105291, 3837, 85106, 15946, 105205, 108549, 3837, 73670, 106968, 104361, 102972, 86119, 15946, 77288, 105470, 105291, 1773, 105291, 104638, 99322, 102239, 27733, 99689, 14, 113046, 14, 103196, 99689, 49567, 31905, 3837, 100148, 45861, 99689, 40027, 1773, 105291, 23031, 5370, 9370, 68805, 107485, 3837, 101912, 4913, 28995, 6415, 71, 788, 4383, 105291, 16, 497, 330, 105291, 17, 7914, 330, 28995, 6205, 788, 4383, 19863, 220, 16, 497, 330, 19863, 220, 17, 1341, 630, 14582, 25, 32181, 247, 113773, 9370, 57421, 105518, 94432, 43842, 25, 5212, 28995, 6415, 71, 788, 4383, 57421, 7914, 330, 28995, 6205, 788, 4383, 3094, 92010, 37763, 367, 25, 5468, 14582, 25, 85122, 68862, 16872, 28029, 14777, 198, 43842, 25, 5212, 28995, 6415, 71, 788, 4383, 28029, 14777, 497, 330, 28029, 220, 16, 7914, 330, 28995, 6205, 788, 4383, 22029, 220, 16, 92010, 37763, 367, 25, 5468, 14582, 25, 51461, 116, 63109, 110322, 198, 43842, 25, 5212, 28995, 6415, 71, 788, 4383, 100185, 110322, 497, 330, 110322, 7914, 330, 28995, 6205, 788, 4383, 2153, 14806, 497, 330, 59499, 497, 330, 25310, 367, 92010, 37763, 367, 25, 5468, 14582, 25, 64118, 33477, 104274, 100430, 27442, 198, 43842, 510, 151645, 198, 151644, 77091, 198], lora_request: None.
INFO 04-02 14:55:32 async_llm_engine.py:120] Finished request cmpl-b0572d1cb5534a5b9ccb40d91617eb16.
INFO:     112.65.186.246:53256 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request

**Comment by JianxinMa** [comment]
@tuhahaha 我看log里写了 max_tokens=300 ，框架里哪里有配置这个参数吗？还是说这是用户部署vllm时自行配置的？令人疑惑的是，这个max_tokens=300 和 报错信息的  `max_tokens must be at least 1, got -2815` 对不上。

**Comment by tuhahaha** [comment]
框架里没有这个设置，应该是模型自己的。 @JianxinMa

**Comment by Modas-Li** [comment]
> @tuhahaha 我看log里写了 max_tokens=300 ，框架里哪里有配置这个参数吗？还是说这是用户部署vllm时自行配置的？令人疑惑的是，这个max_tokens=300 和 报错信息的 `max_tokens must be at least 1, got -2815` 对不上。

我单独在llm/base.py中chat设置max_tokens，依然报错400 Bad Request，麻烦帮忙看看，谢谢！

INFO 04-02 17:13:25 async_llm_engine.py:508] Received request cmpl-f8c3f23ea7f1497c87d1ffff8b3226af: prompt: '<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n请提取问题中的关键词，需要中英文均有，可以适量补充不在问题中但相关的关键词。关键词尽量切分为动词/名词/形容词等类型，不要长词组。关键词以JSON的格式给出，比如{"keywords_zh": ["关键词1", "关键词2"], "keywords_en": ["keyword 1", "keyword 2"]}\n\nQuestion: 这篇文章的作者是谁？\nKeywords: {"keywords_zh": ["作者"], "keywords_en": ["author"]}\nObservation: ...\n\nQuestion: 解释下图一\nKeywords: {"keywords_zh": ["图一", "图 1"], "keywords_en": ["Figure 1"]}\nObservation: ...\n\nQuestion: 核心公式\nKeywords: {"keywords_zh": ["核心公式", "公式"], "keywords_en": ["core formula", "formula", "equation"]}\nObservation: ...\n\nQuestion: 市场一览有哪些\nKeywords:\n<|im_end|>\n<|im_start|>assistant\n', sampling_params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.7, top_p=1.0, top_k=-1, min_p=0.0, seed=None, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=['✿RESULT✿', '✿RESULT✿:', '✿RESULT✿:\n', 'Observation:', 'Observation:\n'], stop_token_ids=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=299, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt_token_ids: [151644, 8948, 198, 2610, 525, 264, 10950, 17847, 13, 151645, 198, 151644, 872, 198, 14880, 107439, 86119, 101047, 105291, 3837, 85106, 15946, 105205, 108549, 3837, 73670, 106968, 104361, 102972, 86119, 15946, 77288, 105470, 105291, 1773, 105291, 104638, 99322, 102239, 27733, 99689, 14, 113046, 14, 103196, 99689, 49567, 31905, 3837, 100148, 45861, 99689, 40027, 1773, 105291, 23031, 5370, 9370, 68805, 107485, 3837, 101912, 4913, 28995, 6415, 71, 788, 4383, 105291, 16, 497, 330, 105291, 17, 7914, 330, 28995, 6205, 788, 4383, 19863, 220, 16, 497, 330, 19863, 220, 17, 1341, 630, 14582, 25, 32181, 247, 113773, 9370, 57421, 105518, 94432, 43842, 25, 5212, 28995, 6415, 71, 788, 4383, 57421, 7914, 330, 28995, 6205, 788, 4383, 3094, 92010, 37763, 367, 25, 5468, 14582, 25, 85122, 68862, 16872, 28029, 14777, 198, 43842, 25, 5212, 28995, 6415, 71, 788, 4383, 28029, 14777, 497, 330, 28029, 220, 16, 7914, 330, 28995, 6205, 788, 4383, 22029, 220, 16, 92010, 37763, 367, 25, 5468, 14582, 25, 51461, 116, 63109, 110322, 198, 43842, 25, 5212, 28995, 6415, 71, 788, 4383, 100185, 110322, 497, 330, 110322, 7914, 330, 28995, 6205, 788, 4383, 2153, 14806, 497, 330, 59499, 497, 330, 25310, 367, 92010, 37763, 367, 25, 5468, 14582, 25, 4891, 116, 224, 82224, 113832, 104719, 198, 43842, 510, 151645, 198, 151644, 77091, 198], lora_request: None.
INFO 04-02 17:13:25 metrics.py:218] Avg prompt throughput: 31.0 tokens/s, Avg generation throughput: 0.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 13.6%, CPU KV cache usage: 0.0%
INFO 04-02 17:13:26 async_llm_engine.py:120] Finished request cmpl-f8c3f23ea7f1497c87d1ffff8b3226af.
INFO:     112.65.186.246:57432 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request

**Comment by Modas-Li** [comment]
> 框架里没有这个设置，应该是模型自己的。 @JianxinMa

按照qwen1.5的命令部署模型的，麻烦帮忙看看你们哪里没对应上：
python -m vllm.entrypoints.openai.api_server --served-model-name Qwen1.5-72B-Chat --model /data/Qwen1.5-72B-Chat --host x.x.x.x --port xxxxx --tensor-parallel-size 4 --gpu-memory-utilization 0.92 --max-model-len 512

qwen_agent启动命令:
python run_server.py --llm Qwen1.5-72B-Chat --model_server http://x.x.x.x:xxxxx/v1 --api_key EMPTY

**Comment by Modas-Li** [comment]
pure chat正常，其他chat报错

**Comment by Modas-Li** [comment]
pure chat正常，其他chat报错

**Comment by Modas-Li** [comment]
pure chat正常:
![image](https://github.com/QwenLM/Qwen-Agent/assets/40042370/f8febc9c-c20c-4ab7-ab1c-475bd696c5d4)

chat报错:
![image](https://github.com/QwenLM/Qwen-Agent/assets/40042370/cc003100-8cf0-4b11-a63a-280cbc2c53f8)

**Comment by JianxinMa** [comment]
> --max-model-len

看起来是启动vllm时 ` --max-model-len 512` 这个参数导致的。目前 qwen-agent 框架做 rag 的时候，默认用了 4k 长度的检索材料（再结合对话上下文，一般会需要 6k model len），512 长度不够用。4k 这个默认配置可以通过 run_server.py 的  `--max_ref_token` 改变 —— 但是即使如此，一般也会要求 `--max-model-len 2048` 以上。

**Comment by Modas-Li** [comment]
> > --max-model-len
> 
> 看起来是启动vllm时 ` --max-model-len 512` 这个参数导致的。目前 qwen-agent 框架做 rag 的时候，默认用了 4k 长度的检索材料（再结合对话上下文，一般会需要 6k model len），512 长度不够用。4k 这个默认配置可以通过 run_server.py 的 `--max_ref_token` 改变 —— 但是即使如此，一般也会要求 `--max-model-len 2048` 以上。

谢谢，我的单卡只有40G，max-model-len拉到4096会显存溢出，使用--enforce-eager之后，勉强运行，但遇到很多网页仍然会报错400 Bad Request。
然而使用6144长度，vllm报错：The model's max seq len (6144) is larger than the maximum number of tokens that can be stored in KV cache (5760)
请问，怎么优化vllm使用，如果不能可以替换使用什么方式启动模型服务，麻烦您付一下链接，谢谢。

**Comment by JianxinMa** [comment]
> > > --max-model-len
> > 
> > 
> > 看起来是启动vllm时 ` --max-model-len 512` 这个参数导致的。目前 qwen-agent 框架做 rag 的时候，默认用了 4k 长度的检索材料（再结合对话上下文，一般会需要 6k model len），512 长度不够用。4k 这个默认配置可以通过 run_server.py 的 `--max_ref_token` 改变 —— 但是即使如此，一般也会要求 `--max-model-len 2048` 以上。
> 
> 谢谢，我的单卡只有40G，max-model-len拉到4096会显存溢出，使用--enforce-eager之后，勉强运行，但遇到很多网页仍然会报错400 Bad Request。 然而使用6144长度，vllm报错：The model's max seq len (6144) is larger than the maximum number of tokens that can be stored in KV cache (5760) 请问，怎么优化vllm使用，如果不能可以替换使用什么方式启动模型服务，麻烦您付一下链接，谢谢。

显存有限的话，需要考虑用量化模型，比如 `Qwen1.5-72B-Chat` 换成 `Qwen/Qwen1.5-7B-Chat-AWQ`，详见 https://qwen.readthedocs.io/en/latest/deployment/vllm.html#serving-quantized-models

另一种方案就是不用vllm，改用ollama（也支持qwen1.5，见qwen1.5的readme），ollama在速度和吞吐上可能不如vllm，但它默认用量化模型、且可以混合使用cpu和gpu。

**Comment by ninoxjy** [comment]
> > --max-model-len
> 
> 看起来是启动vllm时 ` --max-model-len 512` 这个参数导致的。目前 qwen-agent 框架做 rag 的时候，默认用了 4k 长度的检索材料（再结合对话上下文，一般会需要 6k model len），512 长度不够用。4k 这个默认配置可以通过 run_server.py 的 `--max_ref_token` 改变 —— 但是即使如此，一般也会要求 `--max-model-len 2048` 以上。

您好，我的max-model-len 4096时，也遇到了同样的情况，我看了看我的instruction已经有3700token了，我猜测可能在generation的过程中总体超过了4096，所以返回了该Error，此时本地代码catch后raise了ModelServiceError。我在想是不是可以加个特性在catch到超出长度的这个error时，不raise error，利用历史信息在后续的对话里继续生成。我看oai和千问的网页版的功能上应当是有这个特性的。
