### ISSUE TITLE
按照demo演示，此处应该是要画图，请问没有调用的原因是什么，该如何调试，谢谢

### ISSUE THREAD

**Issue by Modas-Li** [QwenLM/Qwen-Agent#115]
![image](https://github.com/QwenLM/Qwen-Agent/assets/40042370/14c1b73b-fde4-4030-8695-a3e06778a7bf)

**Comment by tuhahaha** [comment]
目前在这里实现画图，需要/code 和后面的文本在同一行内（主要由于需要区分前面写了的文章），你这里应该是换行了，导致没有读取到/code这个命令
