### ISSUE TITLE
模型服务+工具调用

### ISSUE THREAD

**Issue by lyj555** [QwenLM/Qwen-Agent#118]
有两个问题请教下，

1）一个是如何基于qwen1.5模型启动open-ai的推理服务，同时具备function call的功能？
我看vLLM和SGLang可以启动服务，但是不支持function call，在qwen-agent项目中，没看到具体的文档介绍服务启动。

2）另外一个问题，目前function call的示例中，我发现和openai的调用方式类似，所以想确认下，qwen1.5训练和调优的时候，也是按照openai格式来的么？

**Comment by lyj555** [comment]
好的，多谢。
另外，上面提到的vllm和sglang，可以使用ollama代替么？

**Comment by JianxinMa** [comment]
> 好的，多谢。 另外，上面提到的vllm和sglang，可以使用ollama代替么？

可以。参考 https://github.com/QwenLM/Qwen-Agent/issues/94#issuecomment-1983410169

**Comment by lyj555** [comment]
嗯嗯，多谢。

**Comment by i-yoyocat** [comment]
> 有两个问题请教下，
> 
> 1）一个是如何基于qwen1.5模型启动open-ai的推理服务，同时具备function call的功能？ 我看vLLM和SGLang可以启动服务，但是不支持function call，在qwen-agent项目中，没看到具体的文档介绍服务启动。
> 
> 2）另外一个问题，目前function call的示例中，我发现和openai的调用方式类似，所以想确认下，qwen1.5训练和调优的时候，也是按照openai格式来的么？

vLLM启动1.5，langchain目前可以调用的~

**Comment by 315930399** [comment]
> > 有两个问题请教下，
> > 1）一个是如何基于qwen1.5模型启动open-ai的推理服务，同时具备function call的功能？ 我看vLLM和SGLang可以启动服务，但是不支持function call，在qwen-agent项目中，没看到具体的文档介绍服务启动。
> > 2）另外一个问题，目前function call的示例中，我发现和openai的调用方式类似，所以想确认下，qwen1.5训练和调优的时候，也是按照openai格式来的么？
> 
> vLLM启动1.5，langchain目前可以调用的~

请教一下怎么调用，用react agent的方式吗
