### ISSUE TITLE
多工具调用

### ISSUE THREAD

**Issue by DSXiangLi** [QwenLM/Qwen-Agent#119]
请问在Function Call的训练过程中是否不支持在一轮中调用多个工具？我看当前的prompt和代码似乎是只支持一次选择一个工具的

**Comment by JianxinMa** [comment]
目前的实现，"一轮对话"中可以多次调用llm，每次调用llm最多给出一个工具调用 —— 所以，单轮对话可以调用多次工具（串行调用），但还不支持并行调用（正在实现中）。

https://github.com/QwenLM/Qwen-Agent/issues/108#issuecomment-2028788603

**Comment by DSXiangLi** [comment]
@JianxinMa 感谢回复，是的我想要的就是单轮并行多工具调用，那等你们实现了求update~

**Comment by JianxinMa** [comment]
https://github.com/QwenLM/Qwen-Agent/issues/167#issuecomment-2182611633
