### ISSUE TITLE
如何使用agent添加自定义工具，实现文档智能问答

### ISSUE THREAD

**Issue by qingqinghu1026** [QwenLM/Qwen-Agent#122]

**Comment by qingqinghu1026** [comment]
如何调用qwen_agent/llm/function_calling.py

**Comment by JianxinMa** [comment]
参考 https://github.com/QwenLM/Qwen-Agent/blob/main/examples/assistant_add_custom_tool.py 或 https://github.com/QwenLM/Qwen-Agent/blob/main/examples/function_calling.py  （这两者有细微区别，请根据自己的需要选择。）

更多资料：
- https://github.com/QwenLM/Qwen-Agent/tree/main/examples
- https://github.com/QwenLM/Qwen-Agent/tree/main/docs

**Comment by qingqinghu1026** [comment]
https://github.com/QwenLM/Qwen-Agent/blob/main/docs/llm_cn.md
这个文档中的## 2. LLM 开发  没怎么看明白，有更具体的文档或参考example吗？

**Comment by qingqinghu1026** [comment]
https://github.com/QwenLM/Qwen-Agent/blob/main/examples/assistant_add_custom_tool.py 
example运行有错误，添加file项的example都会报同样的错误
`python examples/assistant_add_custom_tool.py 
2024-04-10 16:07:14,098 - memory.py - 84 - INFO - {"keywords_zh": ["画", "狗", "绘制"], "keywords_en": ["draw", "dog", "sketch", "illustrate"]}

2024-04-10 16:07:14,100 - doc_parser.py - 74 - INFO - Starting cache pages...
2024-04-10 16:07:14,125 - utils.py - 43 - ERROR - Traceback (most recent call last):
  File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/tools/doc_parser.py", line 167, in call
    record = self.db.get(hash_sha256(params['url']))
  File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/tools/storage.py", line 72, in get
    return read_text_from_file(os.path.join(path, key))
  File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/utils/utils.py", line 128, in read_text_from_file
    with open(path, 'r', encoding='utf-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'workspace/default_doc_parser_data_path/e9127095c5f02a5bcce7e796c132b893b1bfdc33d57a52023727f4d885ba1c7b'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/tools/doc_parser.py", line 97, in process_file
    pdf_content = parse_doc(pdf_path)
  File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/utils/doc_parser.py", line 38, in parse_doc
    from pdfminer.high_level import extract_text
  File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/pdfminer/high_level.py", line 8, in <module>
    from .converter import (
  File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/pdfminer/converter.py", line 18, in <module>
    from pdfminer.pdfcolor import PDFColorSpace
  File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/pdfminer/pdfcolor.py", line 4, in <module>
    from .psparser import LIT
  File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/pdfminer/psparser.py", line 22, in <module>
    from .utils import choplist
  File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/pdfminer/utils.py", line 31, in <module>
    import charset_normalizer  # For str encoding detection
  File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/charset_normalizer/__init__.py", line 23, in <module>
    from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
  File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/charset_normalizer/api.py", line 10, in <module>
    from charset_normalizer.md import mess_ratio
AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)

Traceback (most recent call last):
  File "/home/mmtech/qqhu/ml/OpenAI/Qwen-Agent/examples/assistant_add_custom_tool.py", line 78, in <module>
    test()
  File "/home/mmtech/qqhu/ml/OpenAI/Qwen-Agent/examples/assistant_add_custom_tool.py", line 72, in test
    for response in bot.run(messages=messages):
  File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/agent.py", line 88, in run
    for rsp in self._run(messages=new_messages, **kwargs):
  File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/agents/assistant.py", line 45, in _run
    new_messages = self._prepend_knowledge_prompt(messages, lang,
  File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/agents/assistant.py", line 65, in _prepend_knowledge_prompt
    knowledge = format_knowledge_to_source_and_content(knowledge)
  File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/utils/utils.py", line 310, in format_knowledge_to_source_and_content
    docs = json5.loads(result)
  File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/json5/lib.py", line 108, in loads
    raise ValueError(err)
ValueError: <string>:1 Unexpected "A" at column 1`

**Comment by JianxinMa** [comment]
> https://github.com/QwenLM/Qwen-Agent/blob/main/examples/assistant_add_custom_tool.py example运行有错误，添加file项的example都会报同样的错误 `python examples/assistant_add_custom_tool.py 2024-04-10 16:07:14,098 - memory.py - 84 - INFO - {"keywords_zh": ["画", "狗", "绘制"], "keywords_en": ["draw", "dog", "sketch", "illustrate"]}
> 
> 2024-04-10 16:07:14,100 - doc_parser.py - 74 - INFO - Starting cache pages... 2024-04-10 16:07:14,125 - utils.py - 43 - ERROR - Traceback (most recent call last): File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/tools/doc_parser.py", line 167, in call record = self.db.get(hash_sha256(params['url'])) File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/tools/storage.py", line 72, in get return read_text_from_file(os.path.join(path, key)) File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/utils/utils.py", line 128, in read_text_from_file with open(path, 'r', encoding='utf-8') as file: FileNotFoundError: [Errno 2] No such file or directory: 'workspace/default_doc_parser_data_path/e9127095c5f02a5bcce7e796c132b893b1bfdc33d57a52023727f4d885ba1c7b'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/tools/doc_parser.py", line 97, in process_file pdf_content = parse_doc(pdf_path) File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/utils/doc_parser.py", line 38, in parse_doc from pdfminer.high_level import extract_text File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/pdfminer/high_level.py", line 8, in from .converter import ( File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/pdfminer/converter.py", line 18, in from pdfminer.pdfcolor import PDFColorSpace File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/pdfminer/pdfcolor.py", line 4, in from .psparser import LIT File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/pdfminer/psparser.py", line 22, in from .utils import choplist File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/pdfminer/utils.py", line 31, in import charset_normalizer # For str encoding detection File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/charset_normalizer/**init**.py", line 23, in from charset_normalizer.api import from_fp, from_path, from_bytes, normalize File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/charset_normalizer/api.py", line 10, in from charset_normalizer.md import mess_ratio AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
> 
> Traceback (most recent call last): File "/home/mmtech/qqhu/ml/OpenAI/Qwen-Agent/examples/assistant_add_custom_tool.py", line 78, in test() File "/home/mmtech/qqhu/ml/OpenAI/Qwen-Agent/examples/assistant_add_custom_tool.py", line 72, in test for response in bot.run(messages=messages): File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/agent.py", line 88, in run for rsp in self._run(messages=new_messages, **kwargs): File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/agents/assistant.py", line 45, in _run new_messages = self._prepend_knowledge_prompt(messages, lang, File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/agents/assistant.py", line 65, in _prepend_knowledge_prompt knowledge = format_knowledge_to_source_and_content(knowledge) File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/utils/utils.py", line 310, in format_knowledge_to_source_and_content docs = json5.loads(result) File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/json5/lib.py", line 108, in loads raise ValueError(err) ValueError: :1 Unexpected "A" at column 1`

我这边的几个环境无法复现该问题。但是从该报错看，似乎是 pdfminer 这个依赖包出错了。请尝试更新下相关的依赖包再试试：
```sh
cd Qwen-Agent/;
pip install -U -r requirements.txt
```

**Comment by qingqinghu1026** [comment]
> > https://github.com/QwenLM/Qwen-Agent/blob/main/examples/assistant_add_custom_tool.py example运行有错误，添加file项的example都会报同样的错误 `python examples/assistant_add_custom_tool.py 2024-04-10 16:07:14,098 - memory.py - 84 - INFO - {"keywords_zh": ["画", "狗", "绘制"], "keywords_en": ["draw", "dog", "sketch", "illustrate"]}
> > 2024-04-10 16:07:14,100 - doc_parser.py - 74 - INFO - Starting cache pages... 2024-04-10 16:07:14,125 - utils.py - 43 - ERROR - Traceback (most recent call last): File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/tools/doc_parser.py", line 167, in call record = self.db.get(hash_sha256(params['url'])) File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/tools/storage.py", line 72, in get return read_text_from_file(os.path.join(path, key)) File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/utils/utils.py", line 128, in read_text_from_file with open(path, 'r', encoding='utf-8') as file: FileNotFoundError: [Errno 2] No such file or directory: 'workspace/default_doc_parser_data_path/e9127095c5f02a5bcce7e796c132b893b1bfdc33d57a52023727f4d885ba1c7b'
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/tools/doc_parser.py", line 97, in process_file pdf_content = parse_doc(pdf_path) File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/utils/doc_parser.py", line 38, in parse_doc from pdfminer.high_level import extract_text File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/pdfminer/high_level.py", line 8, in from .converter import ( File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/pdfminer/converter.py", line 18, in from pdfminer.pdfcolor import PDFColorSpace File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/pdfminer/pdfcolor.py", line 4, in from .psparser import LIT File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/pdfminer/psparser.py", line 22, in from .utils import choplist File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/pdfminer/utils.py", line 31, in import charset_normalizer # For str encoding detection File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/charset_normalizer/**init**.py", line 23, in from charset_normalizer.api import from_fp, from_path, from_bytes, normalize File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/charset_normalizer/api.py", line 10, in from charset_normalizer.md import mess_ratio AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
> > Traceback (most recent call last): File "/home/mmtech/qqhu/ml/OpenAI/Qwen-Agent/examples/assistant_add_custom_tool.py", line 78, in test() File "/home/mmtech/qqhu/ml/OpenAI/Qwen-Agent/examples/assistant_add_custom_tool.py", line 72, in test for response in bot.run(messages=messages): File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/agent.py", line 88, in run for rsp in self._run(messages=new_messages, **kwargs): File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/agents/assistant.py", line 45, in _run new_messages = self._prepend_knowledge_prompt(messages, lang, File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/agents/assistant.py", line 65, in _prepend_knowledge_prompt knowledge = format_knowledge_to_source_and_content(knowledge) File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/qwen_agent/utils/utils.py", line 310, in format_knowledge_to_source_and_content docs = json5.loads(result) File "/home/mmtech/anaconda3/envs/qqhu-py39/lib/python3.9/site-packages/json5/lib.py", line 108, in loads raise ValueError(err) ValueError: :1 Unexpected "A" at column 1`
> 
> 我这边的几个环境无法复现该问题。但是从该报错看，似乎是 pdfminer 这个依赖包出错了。请尝试更新下相关的依赖包再试试：
> 
> ```shell
> cd Qwen-Agent/;
> pip install -U -r requirements.txt
> ```

更新之后，还是同样的问题。
pdfminer.six              20231228
python 3.9.18

另外tests/agents/test_doc_qa.py加载文档也会出现问题，将其中file 内的html地址修改为pdf或txt，会输出以下内容：非常抱歉，作为文字交互的AI模型，我无法直接访问您上传的“×××××××.pdf”文件

**Comment by JianxinMa** [comment]
再试试 ` pip install -U charset_normalizer` 呢？

**Comment by JianxinMa** [comment]
或者参考下这个 https://github.com/chenfei-wu/TaskMatrix/issues/242#issuecomment-2009366434

**Comment by qingqinghu1026** [comment]
> 再试试 ` pip install -U charset_normalizer` 呢？

解决了，谢谢！

**Comment by qingqinghu1026** [comment]
> https://github.com/QwenLM/Qwen-Agent/blob/main/docs/llm_cn.md 这个文档中的## 2. LLM 开发 没怎么看明白，有更具体的文档或参考example吗？

这个有参考demo吗

**Comment by JianxinMa** [comment]
> > https://github.com/QwenLM/Qwen-Agent/blob/main/docs/llm_cn.md 这个文档中的## 2. LLM 开发 没怎么看明白，有更具体的文档或参考example吗？
> 
> 这个有参考demo吗

大部分人应该用不到"LLM开发“这节（这一节不是讲怎么使用一个LLM类的，而是讲怎么接入一个新的LLM，比如别的供应商提供的基础大模型的）。  大部分用户应该只用关心 tool 和 agent 的实现，而 llm 部分推荐用 dashscope 或 openai（vllm、ollama、lmstudio都有这种openai接口）接入。

**Comment by qingqinghu1026** [comment]
> > > https://github.com/QwenLM/Qwen-Agent/blob/main/docs/llm_cn.md 这个文档中的## 2. LLM 开发 没怎么看明白，有更具体的文档或参考example吗？
> > 
> > 
> > 这个有参考demo吗
> 
> 大部分人应该用不到"LLM开发“这节（这一节不是讲怎么使用一个LLM类的，而是讲怎么接入一个新的LLM，比如别的供应商提供的基础大模型的）。 大部分用户应该只用关心 tool 和 agent 的实现，而 llm 部分推荐用 dashscope 或 openai（vllm、ollama、lmstudio都有这种openai接口）接入。

好的，我再研究一下
