### ISSUE TITLE
关于function call

### ISSUE THREAD

**Issue by lyj555** [QwenLM/Qwen-Agent#123]
最近结合qwen-agent和业务 测试function call的能力，主要发现两个问题，
1）识别能力感觉还是相对较弱，对于用户提及的一些关键信息，会遗漏很多；
2）历史信息利用较弱，一些信息历史已经提及了，但是模型没有利用；

我是测试是7B和14B的模型，发现7B的工具调用竟然比14B的要好些（14B的模型很多时候都分不清是否要调用工具）
funciton大约是5个，仅一个function的参数量多些，10个多左右，其余的funcion都是一个参数；

PS：对比了gpt3.5，整体的体验会好很多，没有特别严重的卡点；

想问下，后续function call的功能还会继续优化么，这个能力有专门的测试数据吗？

**Comment by JianxinMa** [comment]
function call的能力会持续优化的。方便的话，可以大概说明下badcases长什么样（能给完整的prompt就更好了），在issues里提或者发邮件给我的邮箱都可以。
