### ISSUE TITLE
如何在示例visual_storytelling.py中上传本地图片进行分析？

### ISSUE THREAD

**Issue by J0eky** [QwenLM/Qwen-Agent#126]
将visual_storytelling.py中image的URL替换为本地图片路径，报错：
qwen_agent.llm.base.ModelServiceError: 
Error code: InvalidParameter. Error message: The url for downloading content has some problem

`def test(
    query: Optional[str] = '看图说话',
    image:
    str = '/resource/10.jpg'
):`

**Comment by JianxinMa** [comment]
`/resource/10.jpg` 是不是少了个点，我猜是 `./resource/10.jpg` ? 可以在命令行里`ls ./resource/` 确认下

**Comment by JianxinMa** [comment]
您是在使用 dashscope 的 qwen-vl 吗？目前 qwen-vl 部分暂时只支持传图片的url，还没支持传本地图片路径。我们研究下dashscope的文档，看怎么支持。

注：其他功能，比如 code interpreter 等，则是支持本地图片的。

**Comment by JianxinMa** [comment]
我看了下qwen-vl dashscope的文档，https://help.aliyun.com/zh/dashscope/developer-reference/tongyi-qianwen-vl-plus-api?disableWebsiteRedirect=true#8d583410d7so6

似乎只需要把本地路径改成以`file://`开头即可。比如：
```
       linux&mac file schema: file:///home/images/test.png
       windows file schema: file://D:/images/abc.png
```

我试一下，后面抽空兼容下本地图片。

**Comment by JianxinMa** [comment]
您好，刚更新了main分支，使qwen-vl支持了本地图片，请拉取最新代码再试下。

https://github.com/QwenLM/Qwen-Agent/commit/3f51838645a80c90ba3728e03fb08fd9701edeaa

**Comment by J0eky** [comment]
感谢回复
更新main分支后，按照下面这个格式可行了：
linux&mac file schema: file:///home/images/test.png
