### ISSUE TITLE
visual_storytelling.py中，将qwen-vl-max替换成qwen-vl-v1报错

### ISSUE THREAD

**Issue by J0eky** [QwenLM/Qwen-Agent#129]
visual_storytelling.py中，将qwen-vl-max替换成qwen-vl-v1报错，如下：
![报错](https://github.com/QwenLM/Qwen-Agent/assets/105731709/2448e87b-dcb0-4956-a810-8f530861f675)

**Comment by JianxinMa** [comment]
感谢反馈~ 我们之前也没注意到原来qwen-vl-v1的输出格式和qwen-vl-plus/max不一样。已在最新main修复：
https://github.com/QwenLM/Qwen-Agent/commit/00e17330d6df86c64ee6354511c0aa678dd14cf7
