### ISSUE TITLE
用vllm在服务器部署的Qwen1.5-32B-Chat-AWQ，api_key设置为EMPTY不起作用

### ISSUE THREAD

**Issue by sssuperrrr** [QwenLM/Qwen-Agent#130]
代码：
![1](https://github.com/QwenLM/Qwen-Agent/assets/46615660/af50d270-a2b6-4977-bd9d-06a110423101)

终端：
Qwen-Agent# python3 examples/function_calling.py 
# Assistant Response 1:
Traceback (most recent call last):
  File "/llm_model/Qwen-Agent/examples/function_calling.py", line 122, in <module>
    test()
  File "/llm_model/Qwen-Agent/examples/function_calling.py", line 79, in test
    for responses in llm.chat(messages=messages,
  File "/llm_model/Qwen-Agent/qwen_agent/llm/base.py", line 205, in _convert_messages_iterator_to_target_type
    for messages in messages_iter:
  File "/llm_model/Qwen-Agent/qwen_agent/llm/base.py", line 182, in _postprocess_messages_iterator
    for m in messages:
  File "/llm_model/Qwen-Agent/qwen_agent/llm/base.py", line 373, in retry_model_service_iterator
    raise e
  File "/llm_model/Qwen-Agent/qwen_agent/llm/base.py", line 367, in retry_model_service_iterator
    for rsp in it_fn():
  File "/llm_model/Qwen-Agent/qwen_agent/llm/qwen_dashscope.py", line 180, in _full_stream_output
    raise ModelServiceError(code=trunk.code, message=trunk.message)
qwen_agent.llm.base.ModelServiceError: 
Error code: InvalidApiKey. Error message: Invalid API-key provided.

**Comment by JianxinMa** [comment]
从代码上看，我看不太出问题： https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/llm/oai.py#L35

但我不太确定vllm启动的模型，model是否应该填“/llm/qwen/Qwen1.5-32B-Chat-AWQ”，如果是按qwen1.5的readme的说法应该是只填"Qwen1.5-32B-Chat-AWQ"即可？https://github.com/QwenLM/Qwen1.5?tab=readme-ov-file#vllm

如果不是按qwen1.5的说明启动的vllm，可能要确认下启动这个vllm服务时是否设置了密匙，导致'EMPTY'这个密匙无法使用。

**Comment by JianxinMa** [comment]
可以先类似qwen1.5的readme说明的，用如下代码测试下vllm的配置是否正确：
```py
from openai import OpenAI
openai_api_key = "EMPTY"    # 看情况判断是否需要改成您的配置
openai_api_base = "http://localhost:8000/v1"  # 改成您的配置

client = OpenAI(
    api_key=openai_api_key,
    base_url=openai_api_base,
)

chat_response = client.chat.completions.create(
    model="Qwen1.5-7B-Chat",   # 改成您的配置
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Tell me something about large language models."},
    ]
)
print("Chat response:", chat_response)
```

**Comment by sssuperrrr** [comment]
> 可以先类似qwen1.5的readme说明的，用如下代码测试下vllm的配置是否正确：
> 
> ```python
> from openai import OpenAI
> openai_api_key = "EMPTY"    # 看情况判断是否需要改成您的配置
> openai_api_base = "http://localhost:8000/v1"  # 改成您的配置
> 
> client = OpenAI(
>     api_key=openai_api_key,
>     base_url=openai_api_base,
> )
> 
> chat_response = client.chat.completions.create(
>     model="Qwen1.5-7B-Chat",   # 改成您的配置
>     messages=[
>         {"role": "system", "content": "You are a helpful assistant."},
>         {"role": "user", "content": "Tell me something about large language models."},
>     ]
> )
> print("Chat response:", chat_response)
> ```

按照以上的测试代码，可以正确返回结果
![1](https://github.com/QwenLM/Qwen-Agent/assets/46615660/f7ebd17a-8980-41a4-beff-da6d49798ae7)
但结果仍然是Error code: InvalidApiKey. Error message: Invalid API-key provided
![image](https://github.com/QwenLM/Qwen-Agent/assets/46615660/bac36304-7409-408f-beb5-1121f802f4ad)

**Comment by JianxinMa** [comment]
我看了半天，终于看出来错哪里了 —— 您调用qwen-agent时，model_server写成了`' http://...'` （在 http 前面多了个空格）。。。试试把这个空格strip下。。

我抽空也加下strip的逻辑，避免下这个问题。。

**Comment by sssuperrrr** [comment]
不好意思，我这边检查不仔细。。。现在是OK的
