### ISSUE TITLE
请问本项目的function call/agent能力与langchain框架中的流程区别大吗？

### ISSUE THREAD

**Issue by valkryhx** [QwenLM/Qwen-Agent#142]
之前使用langchain agent封装qwen1.5-7B，发现调用函数的能力并不稳定。
想请教一下如果使用本项目的话，效果能提升吗？ 
在langchain中主要是根据prompt来诱导模型在需要时使用函数并提取文中参数进行输入，
本项目也是这个思路吗？langchain和本项目的本质区别是不是fn call或者react模板不同？本项目的fn call和agent模板可以提供一下吗？
谢谢。

**Comment by JianxinMa** [comment]
本项目也是这个思路吗？——是的。
langchain和本项目的本质区别是不是fn call或者react模板不同？——模版不同。同时很多解析&后处理的处理上会比langchain做得更细些（至少对于qwen输出的一些细节处理，langchain做得并不好，甚至会跑不通。）

fncall模版见 https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/llm/function_calling.py 
agent模版见具体的 agent 实现。

**Comment by yoyofx** [comment]
那之后 这个项目会支持其它模型吗 比如兼容 openai

**Comment by JianxinMa** [comment]
> 那之后 这个项目会支持其它模型吗 比如兼容 openai

这个项目一直都是可以通过openai兼容方式接入其他开源模型的，见readme。但是问题在于：不同模型需要的最优function calling prompt可能不一样，目前的接入方式相当于用qwen的prompt去请求其他模型了，不一定是其他模型的最优prompt —— 这块的工作量较大，因为需要针对每个开源模型细致调整（但很大的强开源模型一般没问题）。
