### ISSUE TITLE
lang参数设置语言无效

### ISSUE THREAD

**Issue by rufeng-h** [QwenLM/Qwen-Agent#145]
FnCallAgent中lang设置语言无效，我查看源代码发现_run方法并没有用到lang参数，而是通过判断prompt中是否有中文字符来确定function_call的模板，但是我们的使用场景几乎都是中文，当message为 `1 + 1 = ?`时，用户希望中文回答结果，但程序会使用英文的模板。希望能够优先以lang参数为准，未设置再判断是否有中文字符。

![image](https://github.com/QwenLM/Qwen-Agent/assets/59313130/2b081be4-6371-40ff-8e0c-5961905c7818)

**Comment by JianxinMa** [comment]
希望模型回复中文的话，其实可以在agent的system_message里写上 “请默认使用中文回复。” 之类的要求。

代码这里lang没生效的问题，我近期修下。。

**Comment by rufeng-h** [comment]
> 希望模型回复中文的话，其实可以在agent的system_message里写上 “请默认使用中文回复。” 之类的要求。
> 
> 代码这里lang没生效的问题，我近期修下。。

今天我又发现了，传给Agent.run方法的关键字参数也没有传递到工具调用中，源代码中_call_tool方法是不是把**kwargs漏掉了。。

**Comment by rufeng-h** [comment]
> > 希望模型回复中文的话，其实可以在agent的system_message里写上 “请默认使用中文回复。” 之类的要求。
> > 代码这里lang没生效的问题，我近期修下。。
> 
> 今天我又发现了，传给Agent.run方法的关键字参数也没有传递到工具调用中，源代码中use_tool的时候self._call_tool方法把**kwargs漏掉了。。

**Comment by JianxinMa** [comment]
lang的问题在main分支修复了。

至于agnent.run的kwargs没有传给 self._call_tool的问题，这个是我们没想清楚的地方，所以故意没传的。我们没想清楚的点是：万一用户在agent.run提供的kwargs和某个tool希望模型生成的argument冲突了，该怎么解决。

请问您agent的kwargs一般需要传什么给tool？如果是session_id的话，应该是个很常见的需求，我们可以显示地加下。

**Comment by rufeng-h** [comment]
> agent.run的kwargs传递给sefl._call_tool进而传

如果工具的parameter和自己设置的kwargs冲突，我觉得这是用户自己的问题，框架不负责。
