### ISSUE TITLE
调用Agent最终结果打印问题

### ISSUE THREAD

**Issue by i-yoyocat** [QwenLM/Qwen-Agent#149]
实验采用了：ReActChat、Assistant--->Router的模式，
最终打印代码：

> *_, response = bot.run(messages=messages)
> messages.extend(response)
> print(response[0]["content"])

预期是只打印最后的“Final Answer”，但是返回却把整个思考过程的内容也返回了，返回内容如下：
---------------友好的分割线--------------------------

> Thought: 需要分别查询产值、税收和企业数量，因此需要使用三个工具。
> Action: VendinceTool
> Action Input: {"parkName": "高新区产业园", "month": "2024-02"}
> 
> Observation: 企业数量100家，产值1000亿
> Thought:  需要再次使用TaxTool查询税收信息。
> Action: TaxTool
> Action Input:{"parkName": "高新区产业园", "month": "2024-02"}
> 
> Observation: 税收：500万
> Thought:  产值、税收和企业数量的信息都已经获取了。
> Final Answer: 高新区产业园在2024年2月的产值为1000亿，税收为500万，园区内共有100家企业。

---------------友好的分割线--------------------------
@JianxinMa 请问如何只打印最后的“Final Answer”，感谢~~~

**Comment by JianxinMa** [comment]
用Assistant这个agent类、而不是ReActChat这个类的话，会方便一些。Assistant这个类的输出会以 function call 的格式给出response，将工具调用和模型想说的话区分开。

**Comment by i-yoyocat** [comment]
> 用Assistant这个agent类、而不是ReActChat这个类的话，会方便一些。Assistant这个类的输出会以 function call 的格式给出response，将工具调用和模型想说的话区分开。

如果用Assistant，会发现应该调用两个工具，但实际只调用了一个工具，应该是上下文不全，我再研究下~感谢！

**Comment by shadows-nhp** [comment]
请问有解决吗
