### ISSUE TITLE
为什么我的mac m1运行example的时候会报错

### ISSUE THREAD

**Issue by wucongshuai758** [QwenLM/Qwen-Agent#152]
examples/react_data_analysis.py:None (examples/react_data_analysis.py)
ImportError while importing test module '/Users/wcs/Desktop/Qwen/Qwen-Agent/examples/react_data_analysis.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_pytest/python.py:487: in importtestmodule
    mod = import_path(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_pytest/pathlib.py:591: in import_path
    importlib.import_module(module_name)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1387: in _gcd_import
    ???
<frozen importlib._bootstrap>:1360: in _find_and_load
    ???
<frozen importlib._bootstrap>:1331: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:935: in _load_unlocked
    ???
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_pytest/assertion/rewrite.py:178: in exec_module
    exec(co, module.__dict__)
react_data_analysis.py:6: in <module>
    from qwen_agent.agents import ReActChat
../qwen_agent/__init__.py:2: in <module>
    from .agent import Agent
../qwen_agent/agent.py:7: in <module>
    from qwen_agent.llm import get_chat_model
../qwen_agent/llm/__init__.py:3: in <module>
    from qwen_agent.llm.base import LLM_REGISTRY
../qwen_agent/llm/base.py:7: in <module>
    from qwen_agent.llm.schema import DEFAULT_SYSTEM_MESSAGE, SYSTEM, Message
../qwen_agent/llm/schema.py:3: in <module>
    from pydantic import BaseModel, field_validator, model_validator
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pydantic/__init__.py:395: in __getattr__
    module = import_module(module_name, package=package)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pydantic/main.py:12: in <module>
    import pydantic_core
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pydantic_core/__init__.py:6: in <module>
    from ._pydantic_core import (
E   ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pydantic_core/_pydantic_core.cpython-312-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pydantic_core/_pydantic_core.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

**Comment by JianxinMa** [comment]
看起来是 pydantic 这个依赖没有安装对、或者您改动过系统默认的一些PATH环境变量。请试试 ` pip install -U pydantic ` 重新安装下。然后在python里先试试 `from pydantic import BaseModel` 看看pydantic是否正常。
