### ISSUE TITLE
Tools should respect language as well

### ISSUE THREAD

**Issue by ligaz** [QwenLM/Qwen-Agent#155]
Currently the `BaseTool` class has hardcoded Chinese `args_format` with description that the input should be a JSON object. This requires all inheritors to override this property if they want to use English.

We should consider a better abstraction for the `BaseTool` class that takes the language into account. For example one option is to pass the language to the constructor and then all messages can be conditionally generated based on the language.

**Comment by JianxinMa** [comment]
Good suggestion! Just fixed, see https://github.com/QwenLM/Qwen-Agent/commit/902b0cfd7125ba8e38162de4628eca040806929f

**Comment by JianxinMa** [comment]
We have just released v0.0.4 and uploaded it to PyPI. Please execute `pip install -U "qwen-agent>=0.0.4"` to upgrade the package. If pip indicates that the version cannot be found, it might be because PyPI is still updating its index.

**Comment by ligaz** [comment]
Thanks.
