### ISSUE TITLE
add to qwen reading list

### ISSUE THREAD

**Issue by jmanhype** [QwenLM/Qwen-Agent#16]
not working everytime i add i get this error IndexError: list index out of range 

the inference works beteween qwen but its not able to add to reading list or read the list 

HELP

**Comment by JianxinMa** [comment]
@tuhahaha Let's discuss how we can address this issue when you return from your vacation.

A little more background on the cause of this issue:
> When a user clicks the Add button, (1) the URL is saved to a temporary file, and (2) the chatbot will look at that temporary file. The current implementation assumes that Step 1 finishes before Step 2 starts. However, this doesn't always seem to be the case. For example, what if Step 1 is blocked by some other operation? What if the write operation fails? In such scenarios, Step 2 will fail with an `IndexError: list index out of range`.

**Comment by JianxinMa** [comment]
I suspect that the frequent cause of this issue is either one of the following:
- (More likely) The user is clicking the Add button while having the popup page open. This can lead to a race condition. We need to add some precautions to prevent this.
- (Less likely) We are having a permission issue when dealing with that temporary file. Perhaps even the directory is not created properly.

**Comment by jmanhype** [comment]
https://github.com/QwenLM/Qwen-Agent/assets/56135400/22ca73f4-4697-49a4-969c-3bf535524123

**Comment by JianxinMa** [comment]
Oh, this is a different issue, not the same one that I am talking about in my previous comment. The IndexError occurs when executing te following code:
```py
...
data['content'] = parse_html_bs(...)  # Using bs4 inside? 
...
extract = data['content'][0]['metadata']['title']  # Here!
```

@tuhahaha It looks like bs4 fails to retrieve the content of the page. Using bs4 here seems like a bad idea. Can't we simply obtain the content throught the chrome extension? 

@tuhahaha Btw, we need to *automatically* detect the language and use English prompts when dealing with English requests.

**Comment by JianxinMa** [comment]
I haven't been able to reproduce the issue yet. I'll look through the code to see if there is any potential bug there.

Meanwhile, please try if upgrading langchain and beautiful soup helps. I'm using 
```bash
pip install "langchain==0.0.304" "beautifulsoup4==4.12.2"
```

If you have the time, please also check if `Qwen-Agent/workspace/browser_cache/tmp.html` contains any data after clicking the Add button. This temporary file is the one being passed into Beautiful Soup.
