### ISSUE TITLE
是否考虑将 function_call 的判断修改为官方文档提供的 function_call？

### ISSUE THREAD

**Issue by Leskur** [QwenLM/Qwen-Agent#160]

**Comment by JianxinMa** [comment]
请问可以具体说下要修改的是什么吗？官方文档指哪个？function call的判断指哪块逻辑？

**Comment by Leskur** [comment]
现在 function 判断的逻辑是依赖 [function_calling.py](https://github.com/QwenLM/Qwen-Agent/blob/d08abc2c18455cd3c278d2618ae993a211cb5345/qwen_agent/llm/function_calling.py#L265) 的 prompt 来实现的。

想询问的是能否新增或修改为 [通义千问 > Function call](https://help.aliyun.com/zh/dashscope/developer-reference/api-details?spm=a2c4g.11186623.0.0.3eff140bLcWtGl#8390a5c5aeueh) 实现？

目前官方文档只有通义千问支持这样调用。通义千问DL和通义千问VL文档里尚未提及。
