### ISSUE TITLE
[BUG] <title>evaluate_plugin中评测模型调用工具的能力  代码给出的6个指标和官方给的3个指标之间的对应关系是什么？

### ISSUE THREAD

**Issue by Plutowithcharon** [QwenLM/Qwen-Agent#161]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![1716260859932](https://github.com/QwenLM/Qwen/assets/48434090/4abb1ecb-8d39-44bd-9c37-5298af970a10)
yu与代码打印出来的
![3b5490eec3467af1f2de0f414500055](https://github.com/QwenLM/Qwen/assets/48434090/f69ba9b2-3bf9-4836-bc86-729cc12c8186)
指标之间的对应关系或者计算公式是什么

### 期望行为 | Expected Behavior

期待有一个公式的讲解

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

无

**Comment by JianxinMa** [comment]
bad rate 对应 1.0 - false positive；

action input rouge 对应 tool input；

action right rate 对应 tool selection；

**Comment by nanhui69** [comment]
> bad rate 对应 1.0 - false positive；
> 
> action input rouge 对应 tool input；
> 
> action right rate 对应 tool selection；

这个代码怎么没发现有
