### ISSUE TITLE
天气预报助手这个案例中，如何配置对应的api key

### ISSUE THREAD

**Issue by xxxgitzh** [QwenLM/Qwen-Agent#168]
python3.10/site-packages/qwen_agent/tools/amap_weather.py  文件报错
  File "***/.local/lib/python3.10/site-packages/qwen_agent/tools/amap_weather.py", line 29, in __init__
    assert self.token != '', 'weather api token must be acquired through ' \
AssertionError: weather api token must be acquired through https://lbs.amap.com/api/webservice/guide/create-project/get-key and set by AMAP_TOKEN

这行代码改成  assert self.token != '', '我的api key' 即可吗

**Comment by liyunhan** [comment]
`os.environ['AMAP_TOKEN'] =xxxxxxx`
