### ISSUE TITLE
想问下Assistant有没有方法直接返回工具结果，而不是将工具结果交由LLM，再由LLM生成最终结果？

### ISSUE THREAD

**Issue by mzgcz** [QwenLM/Qwen-Agent#169]
你好，问题的起源是这样的：
我们把资料搜索做成了工具由Assistant调用（为了统一资料搜索和工具调用接口），这样会导致两次调用LLM来生成资料结果。
1. 在工具执行时，将资料片段整合成回答
2. 在工具返回结果后，再由大模型生成最终回答

想问下有没有方法避免两次调用LLM来生成资料结果，或者有没有其他建议？

**Comment by JianxinMa** [comment]
改动下Assistant的父类FnCallAgent的_run里的while循环即可实现。
https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/agents/fncall_agent.py#L50

就这个case而言，也许只需要将 MAX_LLM_CALL_PER_RUN 这个参数改成1（表示每次run最多调用一次大模型）。

我们后面透出下这个MAX_LLM_CALL_PER_RUN供用户配置。

**Comment by mzgcz** [comment]
> 改动下Assistant的父类FnCallAgent的_run里的while循环即可实现。 https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/agents/fncall_agent.py#L50
> 
> 就这个case而言，也许只需要将 MAX_LLM_CALL_PER_RUN 这个参数改成1（表示每次run最多调用一次大模型）。
> 
> 我们后面透出下这个MAX_LLM_CALL_PER_RUN供用户配置。

修改父类FnCallAgent的_run里的while循环是可以实现的 :-)
要支持这种需求，整个代码的结构还得考虑下 :-)

**Comment by wo55555** [comment]
> > 改动下Assistant的父类FnCallAgent的_run里的while循环即可实现。 https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/agents/fncall_agent.py#L50
> > 就这个case而言，也许只需要将 MAX_LLM_CALL_PER_RUN 这个参数改成1（表示每次run最多调用一次大模型）。
> > 我们后面透出下这个MAX_LLM_CALL_PER_RUN供用户配置。
> 
> 修改父类FnCallAgent的_run里的while循环是可以实现的 :-) 要支持这种需求，整个代码的结构还得考虑下 :-)

可以尝试直接用llm类，然后写function交给llm，这样得到的回复就是function call得到的结果

**Comment by XiaoYu2022** [comment]
> > > 改动下Assistant的父类FnCallAgent的_run里的while循环即可实现。 https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/agents/fncall_agent.py#L50
> > > 就这个case而言，也许只需要将 MAX_LLM_CALL_PER_RUN 这个参数改成1（表示每次run最多调用一次大模型）。
> > > 我们后面透出下这个MAX_LLM_CALL_PER_RUN供用户配置。
> > 
> > 
> > 修改父类FnCallAgent的_run里的while循环是可以实现的 :-) 要支持这种需求，整个代码的结构还得考虑下 :-)
> 
> 可以尝试直接用llm类，然后写function交给llm，这样得到的回复就是function call得到的结果

大佬可以再讲详细一些吗？我刚开始使用Qwen_Agent，我想直接返回调用工具得到的结果，而不是让大模型再总结一下返回，那样速度太慢了，不过我对其中的一些类还比较疑惑，还望大佬帮忙指点一二，不胜感激

**Comment by wo55555** [comment]
> > > > 改动下Assistant的父类FnCallAgent的_run里的while循环即可实现。 https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/agents/fncall_agent.py#L50
> > > > 就这个case而言，也许只需要将 MAX_LLM_CALL_PER_RUN 这个参数改成1（表示每次run最多调用一次大模型）。
> > > > 我们后面透出下这个MAX_LLM_CALL_PER_RUN供用户配置。
> > > 
> > > 
> > > 修改父类FnCallAgent的_run里的while循环是可以实现的 :-) 要支持这种需求，整个代码的结构还得考虑下 :-)
> > 
> > 
> > 可以尝试直接用llm类，然后写function交给llm，这样得到的回复就是function call得到的结果
> 
> 大佬可以再讲详细一些吗？我刚开始使用Qwen_Agent，我想直接返回调用工具得到的结果，而不是让大模型再总结一下返回，那样速度太慢了，不过我对其中的一些类还比较疑惑，还望大佬帮忙指点一二，不胜感激

直接
```
llm = get_chat_model(llm_cfg)
response = llm.chat(messages=messages, functions=functions, stream=False)
print(response)
```
这样得到的就是函数调用的结果了，agent只是在llm上再包装了一层，所以应该调用回底层的东西，而不是改上层的东西

**Comment by XiaoYu2022** [comment]
> > > > > 改动下Assistant的父类FnCallAgent的_run里的while循环即可实现。 https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/agents/fncall_agent.py#L50
> > > > > 就这个case而言，也许只需要将 MAX_LLM_CALL_PER_RUN 这个参数改成1（表示每次run最多调用一次大模型）。
> > > > > 我们后面透出下这个MAX_LLM_CALL_PER_RUN供用户配置。
> > > > 
> > > > 
> > > > 修改父类FnCallAgent的_run里的while循环是可以实现的 :-) 要支持这种需求，整个代码的结构还得考虑下 :-)
> > > 
> > > 
> > > 可以尝试直接用llm类，然后写function交给llm，这样得到的回复就是function call得到的结果
> > 
> > 
> > 大佬可以再讲详细一些吗？我刚开始使用Qwen_Agent，我想直接返回调用工具得到的结果，而不是让大模型再总结一下返回，那样速度太慢了，不过我对其中的一些类还比较疑惑，还望大佬帮忙指点一二，不胜感激
> 
> 直接
> 
> ```
> llm = get_chat_model(llm_cfg)
> response = llm.chat(messages=messages, functions=functions, stream=False)
> print(response)
> ```
> 
> 这样得到的就是函数调用的结果了，agent只是在llm上再包装了一层，所以应该调用回底层的东西，而不是改上层的东西

理解了！谢谢大佬指点！Best Wishes！

**Comment by DAAworld** [comment]
倒不如直接从返回消息中取function角色的content
