### ISSUE TITLE
提高Assistant知识检索速度的方法？

### ISSUE THREAD

**Issue by mzgcz** [QwenLM/Qwen-Agent#174]
我们使用Assistant进行知识问答，13页的PDF文档获取到最终答案大约需要花 7~8s 的时间。
有没有什么方法能提升知识检索的速度？

**Comment by JianxinMa** [comment]
可能是因为默认使用了比较复杂的keyword生成方案。可以改下配置，改成使用简单些的方案（但可能影响效果）。

这个是默认的配置：
https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/settings.py#L15

可以通过Assistant的rag_cfg将rag_keygen_strategy从默认的SplitQueryThenGenKeyword修改为 'None' 或 'GenKeyword'：
https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/agents/assistant.py#L83
https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/memory/memory.py#L37

**Comment by mzgcz** [comment]
@tuhahaha 看RAG处理，每次都会做文件解析。在实际使用中，更多是提前准备好知识库，每次从已经解析过的知识库进行查询。
当前支持这种方式吗？
