### ISSUE TITLE
Move tools like `code_interpreter` in an optional package

### ISSUE THREAD

**Issue by ligaz** [QwenLM/Qwen-Agent#177]
Currently the Python package for qwen-agent has all the tools including `code_interpreter`. However if you are not using this tool in your setup there is no need to install its dependencies. 

Consider moving this tool into an optional package like: 
```
qwen-agent[code_interpreter]
```

**Comment by ligaz** [comment]
@JianxinMa Do you have any thoughts on this one?

**Comment by JianxinMa** [comment]
> @JianxinMa Do you have any thoughts on this one?

Hi, may I ask which dependency in the [requirements.txt](https://github.com/QwenLM/Qwen-Agent/blob/main/requirements.txt) you find to be particularly troublesome? I will check if it is related to the code interpreter and mark it as optional.

**Comment by ligaz** [comment]
They are:
* `matplotlib`
* `pillow`
* `jupyter_client`

**Comment by JianxinMa** [comment]
Hello,

Running `pip install qwen-agent` by default installs the dependencies for code interpreter.

However, if you prefer not to install these optional dependencies, you can now install qwen-agent with the commands below:

```bash
curl -O https://raw.githubusercontent.com/QwenLM/Qwen-Agent/main/requirements.txt
pip install -r requirements.txt
pip install -U --no-deps "qwen-agent>=0.0.6"
```

P.S.: I'm hesitant to make the code interpreter dependencies optional by default, as some users may voice complaints, particularly those who do not read the README.

**Comment by ligaz** [comment]
@JianxinMa Thanks. I have already workaround this on my end by installing `qwen-agent` with `--no-deps` and manually listing out all relevant dependencies that are needed for the core functionality. 

Nevertheless I do believe it makes more sense to extract different tools into different optional extra packages. For example `keywork_search` right now imports `jieba` and `snowballstemmer` which are not needed if your are not using RAG.

This way you will have the core agent framework and a couple of extra packages for `rag`, `code_interpreter`, etc.

**Comment by ligaz** [comment]
We should also note that currently the base agent module imports all tools (regarding of whether you are using them or not).

Importing the `Agent` class: https://github.com/QwenLM/Qwen-Agent/blob/94431706e5998ee6f4f1afcffc2bed7a7078c2dc/qwen_agent/agent.py#L11

which results in all those imports:
https://github.com/QwenLM/Qwen-Agent/blob/94431706e5998ee6f4f1afcffc2bed7a7078c2dc/qwen_agent/tools/__init__.py#L1-L30

**Comment by JianxinMa** [comment]
> We should also note that currently the base agent module imports all tools (regarding of whether you are using them or not).
> 
> Importing the `Agent` class:
> 
> https://github.com/QwenLM/Qwen-Agent/blob/94431706e5998ee6f4f1afcffc2bed7a7078c2dc/qwen_agent/agent.py#L11
> 
> which results in all those imports:
> 
> https://github.com/QwenLM/Qwen-Agent/blob/94431706e5998ee6f4f1afcffc2bed7a7078c2dc/qwen_agent/tools/__init__.py#L1-L30

Thanks for the reminder! In version 0.0.6, I have modified the code interpreter-related imports such that they are lazy, meaning they are only imported when actually needed. As for the RAG-related imports, I will make them lazy as well when I have the time.

**Comment by ligaz** [comment]
Hey @JianxinMa,

Did you have time to make the RAG related imports lazy? It would be great to push another version of Qwen Agent with these and all other new changes to PyPI.

**Comment by JianxinMa** [comment]
Sorry for the late reply. I've been busy working on other things lately.

Starting from v0.0.7, RAG and code interpreter dependencies are both optional. `pip install "qwen-agent>=0.0.7"` now only installs minimal dependencies for function calling. See https://github.com/QwenLM/Qwen-Agent/releases/tag/v0.0.7

**Comment by ligaz** [comment]
Thanks @JianxinMa. I have just tested the latest version and everything is working smoothly. With this change we have been able to optimize our bundle size almost 5x. 

Thanks for your great work!
