### ISSUE TITLE
不支持function calling功能？还是姿势不对？

### ISSUE THREAD

**Issue by luyu0816** [QwenLM/Qwen-Agent#187]
使用ollama部署qwen:7b模型，使用项目中function_calling.py的demo测试，测试结果如下：
![function-calling-test-result-1](https://github.com/QwenLM/Qwen-Agent/assets/47100639/0feb27a5-97c7-477a-a32e-e38bd0efa112)
![function-calling-test-result-2](https://github.com/QwenLM/Qwen-Agent/assets/47100639/c1f792e1-2589-4be0-8ed7-cb357ee92433)

**Comment by JianxinMa** [comment]
看截图，模型的输出比较异常，正常模型输出不该有 <|endoftext|> 。

**Comment by luyu0816** [comment]
这里估计有幻觉问题，我测试几次发现，偶尔是正常的回答，偶尔是多了一些多余的信息，比如：
![function-calling-test-result-4](https://github.com/QwenLM/Qwen-Agent/assets/47100639/ee474cfe-a32a-480b-b90f-f10c04fbe1e5)
电脑有点问题通过ollama pull qwen:7b拉取的文件总是提示sha265的值对不上
![function-calling-test-result-5](https://github.com/QwenLM/Qwen-Agent/assets/47100639/7b5ee408-b4f9-4793-b0f1-c718e6b27c74)
所以我在ModelScope社区上面拉取了qwen1.5:7b-q4_k_m的gguf文件进行转换，再使用ollama启动
![function-calling-test-result-3](https://github.com/QwenLM/Qwen-Agent/assets/47100639/4cf4f7a1-83f9-4118-8b52-d5974f675d87)
![function-calling-test-result-6](https://github.com/QwenLM/Qwen-Agent/assets/47100639/81116753-babc-40ea-81b3-455a1e7888b0)

**Comment by luyu0816** [comment]
使用ollama部署qwen1.5模型，再使用qwen-agent测试function calling功能这个流程是否有问题，我发现ollama项目本身不支持function calling功能
![Uploading function-calling-test-result-7.png…]()

**Comment by JianxinMa** [comment]
我这边用ollama run qwen:7b的结果是正常的。会如预期的先后输出：
```
[{'role': 'assistant', 'content': '', 'function_call': {'name': 'get_current_weather', 'arguments': '{"location": "San Francisco, CA", "unit": "celsius"}'}}]
```
```
[{'role': 'assistant', 'content': 'The current weather in San Francisco is 72°F with units being Fahrenheit.'}]
```

qwent-agent并没有用ollama的fn call功能，而是单独实现了fn call。

我正在尝试如何复现。

**Comment by JianxinMa** [comment]
也许尝试下qwen2的readme里关于ollama bug的说明：

- Upgrading ollama to at least 0.1.42.
- Enabling the flash attention implementation in the llama.cpp backend (for ollama over 0.1.39)

```
OLLAMA_FLASH_ATTENTION=1 ollama serve
```
or following the instructions at [ollama faq](https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-linux) to configure the environment variables in ollama service.
- Disabling running on GPU in the ollama app:

```
>>> /set parameter num_gpu 0
```

参考: https://github.com/QwenLM/Qwen2?tab=readme-ov-file#ollama

**Comment by gw00295510** [comment]
请问，有办法百分百调用function_calling吗？而不是让LLM自己思考是否调用function_calling？

**Comment by ye7love7** [comment]
直接写成链吧，把提示词抽出来



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月17日(周一) 下午2:28
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [QwenLM/Qwen-Agent] 不支持function calling功能？还是姿势不对？ (Issue #187)




 
请问，有办法百分百调用function_calling吗？而不是让LLM自己思考是否调用function_calling？
