### ISSUE TITLE
这个项目和ModelScopeGPT/Agent什么关系

### ISSUE THREAD

**Issue by liaoweiguo** [QwenLM/Qwen-Agent#19]

**Comment by JianxinMa** [comment]
ModelScopeGPT/Agent是ModelScope团队开发的ModelScope衍生产品。ModelScopeAgent是一个通用框架，可以集成各种开源模型，不仅限于Qwen，并且较少深入做应用层面的探索。ModelScopeGPT是基于Qwen通用模型微调而来的专用模型，主要用于调用ModelScope上的小模型，并且集成在ModelScopeAgent中。

Qwen-Agent是Qwen算法团队根据平时工作中写过的小脚本汇总而来的工具，专注于Qwen通用模型。它不会特别关注其他开源模型（虽然也支持GPT），主要目的是演示如何编写Qwen的prompts，并提供一些参考实现供使用。此外，Qwen-Agent还将持续探索一些应用层面的事物，如浏览器插件、代码解释器等实验性质较强的新应用，为行业伙伴们提供应用落地的思路。

**Comment by liaoweiguo** [comment]
谢谢

**Comment by JianxinMa** [comment]
两个项目是合作关系。近期 Qwen-Agent 的成员在参与开发 ModelScope-Agent 的 GPTs 项目，项目叫 AgentFabric 或 Agent Builder，见 ModelScope-Agent 的 [README ](https://github.com/modelscope/modelscope-agent/tree/master/apps/agentfabric) 或 ModelScope 网站的[创空间](https://modelscope.cn/studios/modelscope/AgentFabric/summary)，欢迎关注。

**Comment by chuanzhubin** [comment]
> ModelScopeGPT/Agent是ModelScope团队开发的ModelScope衍生产品。ModelScopeAgent是一个通用框架，可以集成各种开源模型，不仅限于Qwen，并且较少深入做应用层面的探索。ModelScopeGPT是基于Qwen通用模型微调而来的专用模型，主要用于调用ModelScope上的小模型，并且集成在ModelScopeAgent中。
> 
> Qwen-Agent是Qwen算法团队根据平时工作中写过的小脚本汇总而来的工具，专注于Qwen通用模型。它不会特别关注其他开源模型（虽然也支持GPT），主要目的是演示如何编写Qwen的prompts，并提供一些参考实现供使用。此外，Qwen-Agent还将持续探索一些应用层面的事物，如浏览器插件、代码解释器等实验性质较强的新应用，为行业伙伴们提供应用落地的思路。

学习了下example/下的几个程序, 确实挺有意思的.  有点像qwen cookbook, 又有点像一个框架. 
不知道是否有兼容openai api的function call接口(这个不确定是否已支持)?  这样就可以和其他框架无缝结合了.

**Comment by chuanzhubin** [comment]
和openai api的function call有一个区别: stream模式下, openai 是每次返回新增的delta tokens,  qwen function call演示代码里是每次返回当前已生成的all tokens

**Comment by EvilCalf** [comment]
> 两个项目是合作关系。近期 Qwen-Agent 的成员在参与开发 ModelScope-Agent 的 GPTs 项目，项目叫 AgentFabric 或 Agent Builder，见 ModelScope-Agent 的 [README ](https://github.com/modelscope/modelscope-agent/tree/master/apps/agentfabric) 或 ModelScope 网站的[创空间](https://modelscope.cn/studios/modelscope/AgentFabric/summary)，欢迎关注。

想请问下，因为我看两个agent包的使用方式很类似，你们主要开发的项目是modelscope agent么，是的话就使用那个去了

**Comment by JianxinMa** [comment]
> 
> 想请问下，因为我看两个agent包的使用方式很类似，你们主要开发的项目是modelscope agent么，是的话就使用那个去了

不是，两个开源项目是独立的、开发人员不同，没有主次之分。

使用类似是因为我们有段时间过去帮modelscope agent开发了一版agent、llm、tool的interface。但后来因为项目的一些开发目标不太一致，我们就回来qwen-agent继续开发了。qwen-agent这边相对更重视效果好不好，而不是功能多不多。
