### ISSUE TITLE
react输出结果控制

### ISSUE THREAD

**Issue by diligent321** [QwenLM/Qwen-Agent#195]
你好，我要使用react来调用查数工具，然后测试发现，当查数工具返回的数据行较多时，然后助手就做了很多内容总结，导致时间会很长。
我的想法是，当查数工具返回数据行小于一个阈值，比如10行时，就允许结果总结 ，否则不做总结，请教下，怎么实现这种二分类处理逻辑？

**Comment by JianxinMa** [comment]
https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/agents/react_chat.py#L85 在这个位置，根据observation（工具结果）判断下要不要提前break出这个while循环即可。

**Comment by diligent321** [comment]
明白了，感谢
