### ISSUE TITLE
python run_server.py missed jsonl file

### ISSUE THREAD

**Issue by jeffersyuan1976** [QwenLM/Qwen-Agent#197]
Hi,

When I run the run_server.py with
python run_server.py --llm qwen2 --model_server http://127.0.0.1:11434/v1

I got the following error:
FileNotFoundError: [Errno 2] No such file or directory: 'workspace/popup_url.jsonl'

The ollama and qwen2 is no problem.
Where should I get the popup_url.jsonl file?
Thanks.

**Comment by tuhahaha** [comment]
May I ask if you encountered this issue while using the chrome extension? Please do not directly click the link 127.0.0.1:7863, this service is intended to be used in conjunction with the chrome extension.
You can click on 127.0.0.1:7864 to enter the workstation.
Additionally, we will soon be updating with a more robust chrome extension, which will make it more convenient to use. @jeffersyuan1976

**Comment by jeffersyuan1976** [comment]
That's clear enough. Thanks a lot.
