### ISSUE TITLE
browser_qwen插件安装在windows上，模型和run_server.py运行在linux上，如何修改chrome插件访问远端？

### ISSUE THREAD

**Issue by wqlxx** [QwenLM/Qwen-Agent#20]
目前，在chrome里添加browser_qwen插件，一直要求访问127.0.0.1。请问，是否支持这样的部署方式。run_server.py和qwen-7b模型运行在linux端，chrome插件在windows上运行。

**Comment by JianxinMa** [comment]
`grep -r "127.0.0.1" browser_qwen/` 一下，可以发现需要修改以下这两处的ip地址，并重新安装浏览器插件：

- https://github.com/QwenLM/Qwen-Agent/blob/main/browser_qwen/src/popup.html#L111
- https://github.com/QwenLM/Qwen-Agent/blob/main/browser_qwen/background.js#L2

@tuhahaha 有空的时候请看下是否可以改成“可以通过ui配置ip”。

**Comment by wqlxx** [comment]
我改了，现在可以发送请求到server这边。
![微信截图_20231007103619](https://github.com/QwenLM/Qwen-Agent/assets/1592529/a07d8b5c-ca9b-4d5f-af37-d30aaaa03916)


但是又爆出
> INFO:     10.52.64.85:12257 - "GET /endpoint HTTP/1.1" 405 Method Not Allowed

**Comment by wqlxx** [comment]
![image](https://github.com/QwenLM/Qwen-Agent/assets/1592529/c7a2dd70-b4c2-4521-ab50-f5e02f94a93b)
修改了background.js和popup.html的地址后，还是对话的框体还会报错。但是server后台看，好像都收到了。

**Comment by JianxinMa** [comment]
哦，我知道了。server目前默认配置的127.0.0.1，只允许server访问server自己，需要把server的127.0.0.1改成0.0.0.0。具体为改 `grep -r "127.0.0.1" qwen_agent/` 和 `grep -r "127.0.0.1" qwen_server/` 找到的对应的值。

@tuhahaha 咱们需要花时间重构下，这个配置有点乱。

**Comment by JianxinMa** [comment]
更正，请改 qwen_agent/configs/config_browserqwen.py 下的 127.0.0.1 为 0.0.0.0。`qwen_server/`下的要不要改请 @tuhahaha 判断下。

**Comment by tuhahaha** [comment]
只需修改qwen_agent/configs/config_browserqwen.py 下的 127.0.0.1 为 0.0.0.0，重启run_server.py即可。

**Comment by tuhahaha** [comment]
目前的设置主要支持本地运行run_server，我改下配置文件，方便修改远程访问的情况。

**Comment by wqlxx** [comment]
> 目前的设置主要支持本地运行run_server，我改下配置文件，方便修改远程访问的情况。

好像不生效。我修改了qwen_agent/configs/config_browserqwen.py里fast_api_host，app_host和app_in_browser_host三个地址。
![image](https://github.com/QwenLM/Qwen-Agent/assets/1592529/c7789cbc-bcfc-45c5-bc88-f0567dfbec6a)
"Add to Qwen's Reading List"可以提交，run_server.py显示
![image](https://github.com/QwenLM/Qwen-Agent/assets/1592529/64dd168c-19ed-46aa-8b79-b59c56635896)
再点击，chrome里browser_qwen的按钮还是显示“127.0.0.1 拒绝了我们的连接请求”问题。

**Comment by JianxinMa** [comment]
> chrome里browser_qwen的按钮还是显示“127.0.0.1 拒绝了我们的连接请求"

这里显示127.0.0.1的话，说明chrome插件（browser_qwen目录下的东西）没有重新安装、或者没有将browser_qwen下的127.0.0.1改为run_server.py对应的服务器ip？

**Comment by wqlxx** [comment]
> > chrome里browser_qwen的按钮还是显示“127.0.0.1 拒绝了我们的连接请求"
> 
> 这里显示127.0.0.1的话，说明chrome插件（browser_qwen目录下的东西）没有重新安装、或者没有将browser_qwen下的127.0.0.1改为run_server.py对应的服务器ip？

我修改了popup.html和background.js里的127.0.0.1为远端服务器的地址。通过调试工具能看到，请求发送到远端了。
也试过卸载chrome的插件。修改上述两个文件的ip后，再次安装，好像会“显示”插件要求访问127.0.0.1。

**Comment by liaoweiguo** [comment]
还有一个小问题，web插件里面的滚动条会嵌套

**Comment by tuhahaha** [comment]
已修改为支持前端配置ip地址，稍后更新过来。

**Comment by tuhahaha** [comment]
请拉取最新代码，Step1: 在运行run_server时传入参数 --server_host 0.0.0.0（支持用ip地址访问服务器）；Step2: 刷新浏览器扩展程序（因为插件前后端代码有改动）；Step3: 在右上角交互页面【Customize Address:】输入你的服务器ip地址点击「Change」。这样就可以访问了，我这里可以跨机器访问，有问题再贴到issue，感谢～

**Comment by tuhahaha** [comment]
补充：Step3添加IP地址即可，默认是127.0.0.1，添加完ip以后重新打开交互框就可以刷新出聊天窗口。

**Comment by saler-1** [comment]
这种办法，在本地windows浏览器上打开PDF，点击添加的时候，无法根据pdf的文档进行问答，因为pdf无法上传到linux上

**Comment by MrRace** [comment]
> Change



> 请拉取最新代码，Step1: 在运行run_server时传入参数 --server_host 0.0.0.0（支持用ip地址访问服务器）；Step2: 刷新浏览器扩展程序（因为插件前后端代码有改动）；Step3: 在右上角交互页面【Customize Address:】输入你的服务器ip地址点击「Change」。这样就可以访问了，我这里可以跨机器访问，有问题再贴到issue，感谢～

@tuhahaha 如果是自定义ip和端口，上面的方式好像不支持端口吧？

**Comment by tuhahaha** [comment]
由于端口涉及较多地方，目前不支持在前端改端口，可以全局检索对应的端口替换下。

**Comment by tuhahaha** [comment]
@saler-1 由于浏览器扩展程序权限限制，传输本地文件较困难，针对远程服务的情况，目前更新了一版代码，可以在工作台上传本地pdf文件到浏览历史，可以勾选需要的浏览记录进行问答哈。（拉取最新代码后请刷新下浏览器扩展程序，因为前端代码有更新。
