### ISSUE TITLE
本项目与AgentScope有什么区别和优势呢?

### ISSUE THREAD

**Issue by leavegee** [QwenLM/Qwen-Agent#201]
Qwen-agent的核心竞争力是什么?
与AgentScope的关系是什么? 
以及Qwen-agent未来的计划是什么?

**Comment by JianxinMa** [comment]
qwen-agent由负责qwen模型的算法团队直接开发。

qwen-agent和agentscope是互补关系，目前两者的功能重叠度并不高、并且可以通过在agentscope里import qwen-agent进行融合（正如agentscope当前也会import langchain/llamaindex来支持rag一样，agentscope也可以改成import qwen-agent来支持rag、tooluse），agentscope实际更像langserve、langflow，而qwen-agent更像langchain的子集。

因为这两个框架的互补性质，有和agentscope合作的计划，但碍于人手，咱未有明确排期。

**Comment by leavegee** [comment]
非常感谢解惑, nice man , nice project
