### ISSUE TITLE
开源的qwen模型是否支持function call

### ISSUE THREAD

**Issue by robin-xl** [QwenLM/Qwen-Agent#216]
示例中用的是dashscope的qwen-max模型，是否有开源的或者私有化qwen模型支持这个协议呢

**Comment by JianxinMa** [comment]
开源模型 qwen1.5 qwen2 都支持的，参考 qwen2 的readme部署开源qwen2模型，然后以 openai api 兼容接口的方式接入即可。

https://github.com/QwenLM/Qwen-Agent/blob/main/README_CN.md#%E5%87%86%E5%A4%87%E6%A8%A1%E5%9E%8B%E6%9C%8D%E5%8A%A1

**Comment by robin-xl** [comment]
下载Qwen/Qwen2-7B-Instruct-GGUF内的qwen2-7b-instruct-q5_k_m.gguf模型文件，通过llama.server 启动后
通过postman调用问答可以，但是无法命中tool_calls，是什么原因呢？
**body**
```
{
    "model": "Qwen2-7B-Instruct",
    "messages": [
        {
            "role": "user",
            "content": "What's the weather like in San Francisco?"
        }
    ],
    "tools": [
        {
            "function": {
                "description": "Get the current weather in a given location",
                "name": "get_current_weather",
                "parameters": {
                    "properties": {
                        "location": {
                            "description": "The city and state, e.g. San Francisco, CA",
                            "type": "string"
                        },
                        "unit": {
                            "enum": [
                                "celsius",
                                "fahrenheit"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "location"
                    ],
                    "type": "object"
                }
            },
            "type": "function"
        }
    ],
    "temperature": 0.1,
    "tool_choice": "auto"
}
```
**response**
```
{
    "id": "chatcmpl-91acfb38-d8a5-4605-8ba8-b01d6621a0fa",
    "object": "chat.completion",
    "created": 1719404454,
    "model": "Qwen2-7B-Instruct",
    "choices": [
        {
            "index": 0,
            "message": {
                "content": "I'm sorry, as an AI I don't have real-time capabilities to provide current weather updates. Please check any reliable online weather forecasting platform for the most accurate and up-to-date information about the weather in San Francisco or any other location you're interested in.",
                "role": "assistant"
            },
            "logprobs": null,
            "finish_reason": "stop"
        }
    ],
    "usage": {
        "prompt_tokens": 28,
        "completion_tokens": 52,
        "total_tokens": 80
    }
}
```
故意把tools内的json写错大模型又是校验其格式的

**Comment by JianxinMa** [comment]
> @JianxinMa 下载Qwen/Qwen2-7B-Instruct-GGUF内的qwen2-7b-instruct-q5_k_m.gguf模型文件本地化部署，通过llama.server 启动后 通过postman调用问答可以，但是无法命中tool_calls，是什么原因呢？ **body**
> 
> ```
> {
>     "model": "Qwen2-7B-Instruct",
>     "messages": [
>         {
>             "role": "user",
>             "content": "What's the weather like in San Francisco?"
>         }
>     ],
>     "tools": [
>         {
>             "function": {
>                 "description": "Get the current weather in a given location",
>                 "name": "get_current_weather",
>                 "parameters": {
>                     "properties": {
>                         "location": {
>                             "description": "The city and state, e.g. San Francisco, CA",
>                             "type": "string"
>                         },
>                         "unit": {
>                             "enum": [
>                                 "celsius",
>                                 "fahrenheit"
>                             ],
>                             "type": "string"
>                         }
>                     },
>                     "required": [
>                         "location"
>                     ],
>                     "type": "object"
>                 }
>             },
>             "type": "function"
>         }
>     ],
>     "temperature": 0.1,
>     "tool_choice": "auto"
> }
> ```
> 
> **response**
> 
> ```
> {
>     "id": "chatcmpl-91acfb38-d8a5-4605-8ba8-b01d6621a0fa",
>     "object": "chat.completion",
>     "created": 1719404454,
>     "model": "Qwen2-7B-Instruct",
>     "choices": [
>         {
>             "index": 0,
>             "message": {
>                 "content": "I'm sorry, as an AI I don't have real-time capabilities to provide current weather updates. Please check any reliable online weather forecasting platform for the most accurate and up-to-date information about the weather in San Francisco or any other location you're interested in.",
>                 "role": "assistant"
>             },
>             "logprobs": null,
>             "finish_reason": "stop"
>         }
>     ],
>     "usage": {
>         "prompt_tokens": 28,
>         "completion_tokens": 52,
>         "total_tokens": 80
>     }
> }
> ```
> 
> 故意把tools内的json写错大模型又是校验其格式的

我不太了解 llama.server （这个具体是哪个github项目？）。但是大模型的tool calls是需要工程配套支持的，如果 llama.server 没针对qwen做相应实现的话，一般是不会有用的（校验格式可能是因为llama.server 针对其他模型做过支持吧）。

**Comment by JianxinMa** [comment]
tool calls一方面依赖模型的能力（这个qwen1.5&qwen2模型都有），另一方面需要工程的配套实现（qwen-agent的examples目录下有个function_calling.py的示例，qwen-agent这方面的支持）。但是其他的模型服务往往都缺少这方面的工程实现。

**Comment by robin-xl** [comment]
> tool calls一方面依赖模型的能力（这个qwen1.5&qwen2模型都有），另一方面需要工程的配套实现（qwen-agent的examples目录下有个function_calling.py的示例，qwen-agent提供了这方面的工程支持）。但是其他的很多部署模型的工程框架往往都缺少这方面的工程实现。

目前项目还在调研阶段，体验过openai的functioncall api可以满足业务需求，但是目前面临一个私有化部署的问题，考虑使用qwen2
```https://llama-cpp-python.readthedocs.io/en/latest/server/#function-calling```
是用这个项目```python -m llama_cpp.server --host 0.0.0.0 --model qwen2-7b-instruct-q5_k_m.gguf --n_ctx 20480```一条命令就可以很方便的启动大模型服务

面临的问题是需要在java项目里调用类似openai的```/v1/chat/completions```接口就可以使用functioncall能力
```Qwen-Agent```的示例看下来更像是一个客户端，是否提供api调用，或者完全使用```Qwen-Agent```如何能同样部署出来一个```/v1/chat/completions```接口来使用```function call```能力呢？

**Comment by JianxinMa** [comment]
> 或者如果完全使用`Qwen-Agent`如何能同样部署出来一个`/v1/chat/completions`接口来使用`function call`能力呢？

或者如果完全使用Qwen-Agent如何能同样部署出来一个/v1/chat/completions接口来使用function call能力呢？ —— 可以使用FastAPI+qwen-agent实现一个您说的这种api服务。（最近还在找人手实现这个，需要再等等，也欢迎社区贡献）。

**Comment by Vinke2** [comment]
> > 或者如果完全使用`Qwen-Agent`如何能同样部署出来一个`/v1/chat/completions`接口来使用`function call`能力呢？
> 
> 或者如果完全使用Qwen-Agent如何能同样部署出来一个/v1/chat/completions接口来使用function call能力呢？ —— 可以使用FastAPI+qwen-agent实现一个您说的这种api服务。（最近还在找人手实现这个，需要再等等，也欢迎社区贡献）。

+1 我们不想要qwen-agent,只想一个纯粹的http 接口来使用function call

**Comment by hvk687** [comment]
any progress on this ?

**Comment by JianxinMa** [comment]
> any progress on this ?

Related issues:
- hf: https://github.com/QwenLM/Qwen2/issues/805#issuecomment-2258310024 (almost done, not officially released yet)
- ollama: https://github.com/ollama/ollama/issues/6007#issuecomment-2262154658 (almost done, not officially released yet)
- vllm: https://github.com/vllm-project/vllm/pull/5649 (not working yet)

Future releases (such as Qwen2.5) likely would have progress on this.

**Comment by zhanghuanhuanlive** [comment]
> 开源模型 qwen1.5 qwen2 都支持的，参考 qwen2 的readme部署开源qwen2模型，然后以 openai api 兼容接口的方式接入即可。
> 
> https://github.com/QwenLM/Qwen-Agent/blob/main/README_CN.md#%E5%87%86%E5%A4%87%E6%A8%A1%E5%9E%8B%E6%9C%8D%E5%8A%A1

只有Function Calling的例子，没有Tools（Function Calling的升级版）的例子，不知道基于function_calling.py怎么改才能支持到Tools？
因为感觉到了qwen2很强，所以想顺便问一下，qwen2.5预计会在什么时候发布呢，很期待呀？

**Comment by jumalmu** [comment]
This is a WIP-labeled issue that was completed.
