### ISSUE TITLE
复杂问题，需要依次调用多个工具

### ISSUE THREAD

**Issue by nuocheng** [QwenLM/Qwen-Agent#219]
如何实现，对一个复杂问题，依次调用多个工具，将得到的结果进行整合，然后得到结论
这样的场景如何实现

**Comment by freedomRen** [comment]
现在不是支持嘛，链式调用。但是qwen2  72b模型不咋地，你可以试试qwen -max

**Comment by nuocheng** [comment]
> 现在不是支持嘛，链式调用。但是qwen2 72b模型不咋地，你可以试试qwen -max

链式调用有demo吗？没找到相关测试案例

**Comment by JianxinMa** [comment]
https://github.com/QwenLM/Qwen-Agent/tree/main/examples

底层LLM接口：参考 examples/function_calling.py function_calling_in_parallel.py

高级封装Agent抽象：建议先读下README的例子。参考 examples/assistant_add_custom_tool.py 或 qwen_agent/agents/fncall_agent.py
