### ISSUE TITLE
启动 run_server.py 报错，web访问提示“无法访问此页面，127.0.01 已拒绝连接”

### ISSUE THREAD

**Issue by tomy2502** [QwenLM/Qwen-Agent#223]
(qwen-agent) C:\qwen-agent\Qwen-Agent>python run_server.py --model_server http://localhost:11434/v1/ --api_key ollama --llm qwen2:latest  --server_host 0.0.0.0 --workstation_port 7864
2024-06-25 16:50:35,172 - run_server.py - 101 - INFO - path=PathConfig(work_space_root='workspace/', download_root='workspace/download/', code_interpreter_ws='workspace/tools/code_interpreter/') server=ServerConfig(server_host='0.0.0.0', fast_api_port=7866, app_in_browser_port=7863, workstation_port=7864, model_server='http://localhost:11434/v1/', api_key='ollama', llm='qwen2:latest', max_ref_token=4000, max_days=7)
2024-06-25 16:50:36,766 - database_server.py - 34 - INFO - 198.18.0.1
2024-06-25 16:50:36,776 - database_server.py - 34 - INFO - 198.18.0.1
INFO:     Started server process [9900]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:7866 (Press CTRL+C to quit)
Running on local URL:  http://0.0.0.0:7863
Running on local URL:  http://0.0.0.0:7864
IMPORTANT: You are using gradio version 4.21.0, however version 4.29.0 is available, please upgrade.
--------
IMPORTANT: You are using gradio version 4.21.0, however version 4.29.0 is available, please upgrade.
--------
Traceback (most recent call last):
  File "C:\qwen-agent\Qwen-Agent\qwen_server\assistant_server.py", line 137, in <module>
    demo.queue().launch(server_name=server_config.server.server_host, server_port=server_config.server.app_in_browser_port)
  File "C:\Users\asus\.conda\envs\qwen-agent\lib\site-packages\gradio\blocks.py", line 2165, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.
Traceback (most recent call last):
  File "C:\qwen-agent\Qwen-Agent\qwen_server\workstation_server.py", line 602, in <module>
    demo.queue().launch(server_name=server_config.server.server_host, server_port=server_config.server.workstation_port)
  File "C:\Users\asus\.conda\envs\qwen-agent\lib\site-packages\gradio\blocks.py", line 2165, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.

--------------------------------------------------------------------------
浏览器访问：http://127.0.0.1:7864/   提示错误

嗯… 无法访问此页面127.0.0.1 已拒绝连接。
请尝试：

在 web 上搜索 127 0 0 1
检查连接
检查代理和防火墙
ERR_CONNECTION_REFUSED

---------------------------------------------------------------------------

Windows11
Python 3.10

请问如何解决？谢谢

**Comment by tomy2502** [comment]
解决办法：

更改requirement，删除一行：numpy，同时增加：
scikit-image>=0.16.1
protobuf>=3.20.2
numpy<1.28.0,>=1.21.6

pip install -e ./

pip install -U "gradio==4.21.0" "modelscope-studio>=0.2.1"

修改代码：
workstation_server.py
最后一行：demo.queue().launch() ，增加参数share=True
assistant_server.py
workstation_server.py
最后一行：demo.queue().launch() ，增加参数share=True

运行：
python run_server.py --model_server http://localhost:11434/v1 --api_key ollama --llm qwen2:latest  --server_host 0.0.0.0 --workstation_port 7864

**Comment by tomy2502** [comment]
但是：

ollama对 openai的api兼容，在windows下、或者说这爱wsl2下，是不能正常工作的
比方访问 http://127.0.0.1:11434/v1/  会返回404

**Comment by Accurio** [comment]
### 原因

设置了系统代理时，由于 Gradio 使用的 HTTPX 库不支持读取系统代理排除列表，HTTPX 会将对 `localhost` 和 `127.0.0.1/8` 的请求发至代理服务器；当代理服务器无法访问客户端发布的 Gradio 网站时，`networking.url_ok(self.local_url)` 会返回 `False` 并抛出 `ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.` 错误。

### 解决方案

使用 `urllib.request.getproxies()` 获取代理配置，通过 `os.environ` 设置代理服务器和代理排除列表。

```
import os
from urllib.request import getproxies

proxies = getproxies()
os.environ["http_proxy"] = proxies["http"]
os.environ["https_proxy"] = proxies["https"]
os.environ["no_proxy"] = "localhost, 127.0.0.1, ::1"
```
