### ISSUE TITLE
parallel_function_calls 报错TypeError: create() got an unexpected keyword argument 'parallel_function_calls'

### ISSUE THREAD

**Issue by conan0x00** [QwenLM/Qwen-Agent#225]
这个参数在get_chat_model()中可以使用，在llm.chat()中调用报题目错误

**Comment by JianxinMa** [comment]
有更具体的脚本供复现吗？

example里就是通过llm.chat传的，https://github.com/QwenLM/Qwen-Agent/blob/main/examples/function_calling_in_parallel.py#L68 我看看能不能复现您遇到的问题。

另：这个还没有发布到pip。目前需要拉取main分支，并pip install -e ./ 的方式安装main分支的代码（见readme）。我今天看下来不来得及发布到pypi

**Comment by conan0x00** [comment]
> 有更具体的脚本供复现吗？
> 
> example里就是通过llm.chat传的，https://github.com/QwenLM/Qwen-Agent/blob/main/examples/function_calling_in_parallel.py#L68 我看看能不能复现您遇到的问题。
> 
> 另：这个还没有发布到pip。目前需要拉取main分支，并pip install -e ./ 的方式安装main分支的代码（见readme）。我今天看下来不来得及发布到pypi

谢谢回复！我之前用清华源安装的是0.0.5版本，现在git的main分支0.0.6，问题解决了。
