### ISSUE TITLE
RAG文档长度对模型生成正确率的影响

### ISSUE THREAD

**Issue by Wijipedia** [QwenLM/Qwen-Agent#227]
模型：本地部署的`qwen2:7b`--int4量化版本
使用了示例中的`assistant_rag`：https://github.com/QwenLM/Qwen-Agent/blob/main/examples/assistant_rag.py
以及`parallel_doc_qa`：https://github.com/QwenLM/的Qwen-Agent/blob/main/examples/parallel_doc_qa.py
分别测试了2k，3k，4k，5k，10k字符的中文文档，该中文文档是从维基百科直接复制的梅西的介绍（其它文档都是10k的精简版）。我发现二者生成的回复没有任何区别，不存在`parallel_doc_qa`比`assistat_rag`效果好一些的情况，除了parallel回复的慢一些。

此外，`assistant_rag`和`parallel_doc_qa`在检索3k文档时还能正常回答问题，4k及以上的文档就开始乱说了。
比如我的问题是：根据文档告诉我梅西的父亲是谁，并给出原文中的参考。
3k及以下的回复都是对的，原文的参考也是对的。4k及以上的就开始瞎说了。
![assistant_rag_3k](https://github.com/QwenLM/Qwen-Agent/assets/42368923/db06fca9-1e3d-4519-ada5-1f439ab48efa)
![assistant_rag_4k](https://github.com/QwenLM/Qwen-Agent/assets/42368923/c6757891-5b7a-4f22-9761-852b01250257)

我不知道是我本地模型的问题，还是说别的问题，希望有大佬能给我解疑。谢谢。

**Comment by JianxinMa** [comment]
方便给一下截图中这两个示例文件吗？我们查下。cc @JialinWangPKU

**Comment by JianxinMa** [comment]
第二个胡说八道的case有点离谱，我有点怀疑是 int4量化 导致模型表现大幅下降。我试试看

**Comment by JianxinMa** [comment]
![image](https://github.com/QwenLM/Qwen-Agent/assets/7543016/5b1af215-dccc-4a44-a428-16ffec0b6674)

我这边用dashscope提供的qwen2-7b-instruct模型，查询wiki页面下载下来的整个html，得到的答复是正常的。

请问您的int4模型是怎么部署的，用的什么框架，checkpoint的来源是？

**Comment by Wijipedia** [comment]
> ![image](https://private-user-images.githubusercontent.com/7543016/343600857-5b1af215-dccc-4a44-a428-16ffec0b6674.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NzU4MTksIm5iZiI6MTcxOTQ3NTUxOSwicGF0aCI6Ii83NTQzMDE2LzM0MzYwMDg1Ny01YjFhZjIxNS1kY2NjLTRhNDQtYTQyOC0xNmZmZWMwYjY2NzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjdUMDgwNTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDM3MzJlYjI0ZGY3OTQzYjQ5MzNlZjM4Njk2NGNjZWJiMjgyMTg0MzIwZGExZDBhZTM2MTU1YTIzOTY2MmQ1ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PlBYJP7U0Qdn4_UY2BnbYEGsyU-iOwUbsa1s-T9vRmA)
> 
> 我这边用dashscope提供的qwen2-7b-instruct模型，查询wiki页面下载下来的整个html，得到的答复是正常的。
> 
> 请问您的int4模型是怎么部署的，用的什么框架，checkpoint的来源是？

我用的`ollama`部署的`qwen2:7b`，这个版本就是`qwen2:7b-instruct`，链接：https://ollama.com/library/qwen2:7b
另外，我刚刚也尝试了使用`dashscope`提供的`qwen2-7b-instruct`，发现模型都能识别并正确回复了。
我感觉是ollama部署的模型有问题。
