### ISSUE TITLE
我是用ollama运行qwen2的，请问启动server的api_key如何获得？

### ISSUE THREAD

**Issue by qu66958** [QwenLM/Qwen-Agent#233]
如题

**Comment by JianxinMa** [comment]
ollama部署的api key可以随便填。见 qwen2 的readme https://github.com/QwenLM/Qwen2?tab=readme-ov-file#ollama

**Comment by qu66958** [comment]
![iShot_2024-06-30_21 49 14](https://github.com/QwenLM/Qwen-Agent/assets/38848216/d252a85b-8e57-4c55-bc8d-fcc12fbffb0a)
<img width="1589" alt="iShot_2024-06-30_21 50 04" src="https://github.com/QwenLM/Qwen-Agent/assets/38848216/97429e8e-712b-493c-8a79-51839cc27f3c">

**Comment by qu66958** [comment]
谢谢[JianxinMa](https://github.com/JianxinMa)，请看我的错误贴图，好像不能随便填

**Comment by JianxinMa** [comment]
试试`--model_server 'http://localhost:11434/v1/'` 改成`--model_server http://localhost:11434/v1/` （去掉单引号）。

原因：我看日志，发现实际配置的config是`''http://...` 多了单引号，导致某些 if 语句判断失败、走到了dashscope而非ollama的服务去了，这个api key报错是dashscope的不是ollama的。

**Comment by JianxinMa** [comment]
仔细看了下截图，您贴的这个截图里的单引号可能是中文的单引号、而不是英文的单引号，所以会出现这个问题。

**Comment by qu66958** [comment]
> 仔细看了下截图，您贴的这个截图里的单引号可能是中文的单引号、而不是英文的单引号，所以会出现这个问题。

已经解决了，使用如下命令即可
python run_server.py --llm 'qwen2:7b' --model_server 'http://localhost:11434/v1/' --workstation_port 7864 --api_key 'ollama'
