### ISSUE TITLE
哪里有支持的模型id列表

### ISSUE THREAD

**Issue by AME430** [QwenLM/Qwen-Agent#253]
本地vllm部署qwen2-7b模型，找不到id

qwen_agent.llm.base.ModelServiceError: Error code: 404 - {'object': 'error', 'message': 'The model `qwen2-7b-instruct` does not exist.', 'type': 'NotFoundError', 'param': None, 'code': 404}

**Comment by JianxinMa** [comment]
关于vllm部署的模型的id列表，这个需要您看一下vllm部署的文档。。。。

比如按 https://github.com/QwenLM/Qwen2?tab=readme-ov-file#vllm 的命令启动的话，就是 model="Qwen2-7B-Instruct",

**Comment by AME430** [comment]
> 关于vllm部署的模型的id列表，这个需要您看一下vllm部署的文档。。。。
> 
> 比如按 https://github.com/QwenLM/Qwen2?tab=readme-ov-file#vllm 的命令启动的话，就是 model="Qwen2-7B-Instruct",

好的，感谢
