### ISSUE TITLE
追问机制

### ISSUE THREAD

**Issue by liyunhan** [QwenLM/Qwen-Agent#255]
如果用户的指令中缺少工具所需的某个属性，该怎么设计让Model自行追问缺失的属性呢？希望大伙儿提供点思路

**Comment by liyunhan** [comment]
我发现内置的天气查询等工具，如果没有提供具体的城市和地区，它会追问让提供位置信息。但是在使用自定义工具时，当缺失某项信息时，Assistant不仅不会进行追问，还会把description中提供的案例数据当成用户提供的数据处理..

**Comment by liyunhan** [comment]
又测试了下，ReActChat可以做到暂不执行并追问

**Comment by liyunhan** [comment]
FnCall更是直接根据缺失项的Description编造数据回答

**Comment by liyunhan** [comment]
function_calling好像没法单独提供system_prompt，导致缺失数据项后编造数据的问题没办法解决

**Comment by XiaoYu2022** [comment]
> 又测试了下，ReActChat可以做到暂不执行并追问

大佬您好，想请教您ReActChat这个如何使用呢，有没有相关的参考QwQ

**Comment by liyunhan** [comment]
> > 又测试了下，ReActChat可以做到暂不执行并追问
> 
> 大佬您好，想请教您ReActChat这个如何使用呢，有没有相关的参考QwQ

啊...我也不是大佬，还在研究。可以看下这几个类的继承关系，跟着debug下代码执行顺序大概就清楚思路了。

大致说一下的话，这几个提供的功能类，包括ReActChat和Assistant都继承的FnCallAgent，FnCallAgent继承的Agent，Agent对外暴露的是run方法，又留了一个_run要求继承类必须实现。因此FnCallAgent实际上实现了一个通用的_run方法，用来做工具调用。

FnCallAgent的核心就是`while True and num_llm_calls_available > 0:`里面的代码，这里面就是一个循环调用，大致的思路就是先把外部传进来的message发给llm，LLM决定调用哪个工具并得到对应的工具ouput（将output通过yield输出出去），然后下面根据output调用具体的工具，并把结果拼接成固定的格式继续塞到message里，然后while循环没结束嘛，就把上面的这些构成的message再次塞给llm进行生成，直到不调用工具了就退出while了，其实就是让llm充当一个agent，决定调用工具和调用的顺序。

根据这个思路再看ReActChat和Assistant类，其实ReActChat是没有用FnCallAgent的内容，而是自己实现了_run方法，但是实现思路和FnCallAgent几乎一样，只是自己定义了Prompt让LLM做思维链操作。Assistant就比较简单了，它直接super()._run()使用了父类FnCallAgent的实现，无非是多拼接了一个File（文档阅读能力）进去。

**Comment by liyunhan** [comment]
> > 又测试了下，ReActChat可以做到暂不执行并追问
> 
> 大佬您好，想请教您ReActChat这个如何使用呢，有没有相关的参考QwQ

补充：Agent类的run方法，其实也是调用了_run，又把_run做成抽象方法留给子类实现自己的功能逻辑。所有继承Agent的子类们，比如example中的那些bot.run，其实最终调用的都是各个子类实现的_run。

所以你想对Agent做一些控制的话，就可以考虑某个子类实现，或者继承Agent类，更大自由度的实现自己的调用逻辑了。

又或者完全舍弃这一套逻辑（比如@registry_tool就很方便制作工具类），自己按照官方function_calling.py的例子去做。

**Comment by XiaoYu2022** [comment]
> > > 又测试了下，ReActChat可以做到暂不执行并追问
> > 
> > 
> > 大佬您好，想请教您ReActChat这个如何使用呢，有没有相关的参考QwQ
> 
> 补充：Agent类的run方法，其实也是调用了_run，又把_run做成抽象方法留给子类实现自己的功能逻辑。所有继承Agent的子类们，比如example中的那些bot.run，其实最终调用的都是各个子类实现的_run。
> 
> 所以你想对Agent做一些控制的话，就可以考虑某个子类实现，或者继承Agent类，更大自由度的实现自己的调用逻辑了。
> 
> 又或者完全舍弃这一套逻辑（比如@registry_tool就很方便制作工具类），自己按照官方function_calling.py的例子去做。

感谢您的回答！您讲解的很棒，对我启发很多，我现在就是在按照官方的function_calling.py例子在做，然后我根据我的工具逻辑自己写了一套针对参数的追问逻辑，不过在面对用户输入时，Qwen2-7B对我指定的function中的description的理解不好，不能从用户输入中提取我的外部接口所需的参数值。为此我更换成了Qwen2-72B模型，72B相比7B在问题理解和参数提取的效果上比7B好很多，但是72B的响应时间很长，虽然采用的是量化后的72B模型，但是时间还是远远长于7B（7B约1-2s，72B约10s）。为此，我在找有没有什么可以自动追问的方法，能够自动化的追问，而不是依赖我设置的追问逻辑，或许效果会好一些。
我根据您的回答再研究研究ReActChat，谢谢您！

**Comment by liyunhan** [comment]
> > 又测试了下，ReActChat可以做到暂不执行并追问
> 
> 大佬您好，想请教您ReActChat这个如何使用呢，有没有相关的参考QwQ

至于ReActChat不追问这个...我测了也不行~我目前自己测的，

> > > > 又测试了下，ReActChat可以做到暂不执行并追问
> > > 
> > > 
> > > 大佬您好，想请教您ReActChat这个如何使用呢，有没有相关的参考QwQ
> > 
> > 
> > 补充：Agent类的run方法，其实也是调用了_run，又把_run做成抽象方法留给子类实现自己的功能逻辑。所有继承Agent的子类们，比如example中的那些bot.run，其实最终调用的都是各个子类实现的_run。
> > 所以你想对Agent做一些控制的话，就可以考虑某个子类实现，或者继承Agent类，更大自由度的实现自己的调用逻辑了。
> > 又或者完全舍弃这一套逻辑（比如@registry_tool就很方便制作工具类），自己按照官方function_calling.py的例子去做。
> 
> 感谢您的回答！您讲解的很棒，对我启发很多，我现在就是在按照官方的function_calling.py例子在做，然后我根据我的工具逻辑自己写了一套针对参数的追问逻辑，不过在面对用户输入时，Qwen2-7B对我指定的function中的description的理解不好，不能从用户输入中提取我的外部接口所需的参数值。为此我更换成了Qwen2-72B模型，72B相比7B在问题理解和参数提取的效果上比7B好很多，但是72B的响应时间很长，虽然采用的是量化后的72B模型，但是时间还是远远长于7B（7B约1-2s，72B约10s）。为此，我在找有没有什么可以自动追问的方法，能够自动化的追问，而不是依赖我设置的追问逻辑，或许效果会好一些。 我根据您的回答再研究研究ReActChat，谢谢您！

72b-gptq的话，我是放在了vllm两张卡支撑，速度还可以挺快的。
你提到的自动追问我也在尝试...我的思路还是依赖llm自身的能力，比如多加一个LLM查验参数的步骤，返回一个结果手动控制break出去。当用户补充完信息后，把所有的message再传进来从头开始执行，其实就是假定LLM会根据历史信息决定继续执行哪一步，但目前看效果比较差，不论怎么控制system_prompt，LLM都会固执的输出function_call的信息，并且自己编造一个地名（天气查询）拼接进去。

其实function_calling和自己继承Agent实现的思路都差不多，都是可以自己施加控制，可以自己制定步骤和Prompt强制模型去验证参数完整性（可能需要一个固定的输出格式，方便自己return出去），当然这种情况可能比较适合工具执行顺序比较固定的业务，明确的会调用某几个工具并且严格按照顺序调用。
|
目前测试看，比如天气工具类，ReActChat的final_answer里有一定几率会说“我缺少某个xx信息，需要用户补充”，但也有一定概率直接就把amap_weather里面的“北京市海淀区”当成数据直接就调用工具去了。如果是我自己写的工具，description中如果有“例子”，那么大概率就直接当成数据填到工具表里调用工具去了....

**Comment by liyunhan** [comment]
> > > > 又测试了下，ReActChat可以做到暂不执行并追问
> > > 
> > > 
> > > 大佬您好，想请教您ReActChat这个如何使用呢，有没有相关的参考QwQ
> > 
> > 
> > 补充：Agent类的run方法，其实也是调用了_run，又把_run做成抽象方法留给子类实现自己的功能逻辑。所有继承Agent的子类们，比如example中的那些bot.run，其实最终调用的都是各个子类实现的_run。
> > 所以你想对Agent做一些控制的话，就可以考虑某个子类实现，或者继承Agent类，更大自由度的实现自己的调用逻辑了。
> > 又或者完全舍弃这一套逻辑（比如@registry_tool就很方便制作工具类），自己按照官方function_calling.py的例子去做。
> 
> 感谢您的回答！您讲解的很棒，对我启发很多，我现在就是在按照官方的function_calling.py例子在做，然后我根据我的工具逻辑自己写了一套针对参数的追问逻辑，不过在面对用户输入时，Qwen2-7B对我指定的function中的description的理解不好，不能从用户输入中提取我的外部接口所需的参数值。为此我更换成了Qwen2-72B模型，72B相比7B在问题理解和参数提取的效果上比7B好很多，但是72B的响应时间很长，虽然采用的是量化后的72B模型，但是时间还是远远长于7B（7B约1-2s，72B约10s）。为此，我在找有没有什么可以自动追问的方法，能够自动化的追问，而不是依赖我设置的追问逻辑，或许效果会好一些。 我根据您的回答再研究研究ReActChat，谢谢您！

Emm...其实可以在while外面加一个判断的步骤，写个SYSTEM_PRMOPT负责判断用不用调用工具，是否缺少必要的参数，然后固定输出格式，不满足的直接return出去。当用户再给出信息以后，就把这些所有的Message继续丢给这个判断工具，当信息满足以后，剩下的就和Agent里面的思路一样，一个while干剩下的所有。

**Comment by XiaoYu2022** [comment]
> 72b-gptq的话，我是放在了vllm两张卡支撑，速度还可以挺快的。 你提到的自动追问我也在尝试...我的思路还是依赖llm自身的能力，比如多加一个LLM查验参数的步骤，返回一个结果手动控制break出去。当用户补充完信息后，把所有的message再传进来从头开始执行，其实就是假定LLM会根据历史信息决定继续执行哪一步，但目前看效果比较差，不论怎么控制system_prompt，LLM都会固执的输出function_call的信息，并且自己编造一个地名（天气查询）拼接进去。
> 
> 其实function_calling和自己继承Agent实现的思路都差不多，都是可以自己施加控制，可以自己制定步骤和Prompt强制模型去验证参数完整性（可能需要一个固定的输出格式，方便自己return出去），当然这种情况可能比较适合工具执行顺序比较固定的业务，明确的会调用某几个工具并且严格按照顺序调用。 | 目前测试看，比如天气工具类，ReActChat的final_answer里有一定几率会说“我缺少某个xx信息，需要用户补充”，但也有一定概率直接就把amap_weather里面的“北京市海淀区”当成数据直接就调用工具去了。如果是我自己写的工具，description中如果有“例子”，那么大概率就直接当成数据填到工具表里调用工具去了....

您的72b的响应速度大概几秒，我因为72b的响应速度太慢，所以采用了7b+72b混合的方式，先用7b实现工具调用，然后72b进行参数解析。我在调用百度的天气查询API时也出现了和您类似的情况，会在解析不了地点或者没给地点的时候自动生成北京的内容同时我出现了无论我在description中怎么强调某种规则或者指定参数值，LLM就是不听，给出None或者错误的值。。。QwQ

刚正在写回复的时候看见了您的最新回答，我就是这么做的，我通过在while内设置一旦调用了我编写的function时，直接设置flag=True，记录这段对话期间的message，然后再while外层对这个flag进行判定，在LLM回复之前，一旦为True，直接默认调用工具进行提问，直到function在我的追问逻辑下补充满了所有标准规范格式的接口参数值后，才将flag设置为false，离开这段function对话流程。不过现在除了上面的问题之外，也出现了明明不是需要调用某个tools的问题，但是就因为用户的问题中出现了该tools的funciton的description中的某些字段，就自动调用该tools，导致产生了错误调用。。。

**Comment by liyunhan** [comment]
> > 72b-gptq的话，我是放在了vllm两张卡支撑，速度还可以挺快的。 你提到的自动追问我也在尝试...我的思路还是依赖llm自身的能力，比如多加一个LLM查验参数的步骤，返回一个结果手动控制break出去。当用户补充完信息后，把所有的message再传进来从头开始执行，其实就是假定LLM会根据历史信息决定继续执行哪一步，但目前看效果比较差，不论怎么控制system_prompt，LLM都会固执的输出function_call的信息，并且自己编造一个地名（天气查询）拼接进去。
> > 其实function_calling和自己继承Agent实现的思路都差不多，都是可以自己施加控制，可以自己制定步骤和Prompt强制模型去验证参数完整性（可能需要一个固定的输出格式，方便自己return出去），当然这种情况可能比较适合工具执行顺序比较固定的业务，明确的会调用某几个工具并且严格按照顺序调用。 | 目前测试看，比如天气工具类，ReActChat的final_answer里有一定几率会说“我缺少某个xx信息，需要用户补充”，但也有一定概率直接就把amap_weather里面的“北京市海淀区”当成数据直接就调用工具去了。如果是我自己写的工具，description中如果有“例子”，那么大概率就直接当成数据填到工具表里调用工具去了....
> 
> 您的72b的响应速度大概几秒，我因为72b的响应速度太慢，所以采用了7b+72b混合的方式，先用7b实现工具调用，然后72b进行参数解析。我在调用百度的天气查询API时也出现了和您类似的情况，会在解析不了地点或者没给地点的时候自动生成北京的内容同时我出现了无论我在description中怎么强调某种规则或者指定参数值，LLM就是不听，给出None或者错误的值。。。QwQ
> 
> 刚正在写回复的时候看见了您的最新回答，我就是这么做的，我通过在while内设置一旦调用了我编写的function时，直接设置flag=True，记录这段对话期间的message，然后再while外层对这个flag进行判定，在LLM回复之前，一旦为True，直接默认调用工具进行提问，直到function在我的追问逻辑下补充满了所有标准规范格式的接口参数值后，才将flag设置为false，离开这段function对话流程。不过现在除了上面的问题之外，也出现了明明不是需要调用某个tools的问题，但是就因为用户的问题中出现了该tools的funciton的description中的某些字段，就自动调用该tools，导致产生了错误调用。。。

我是双卡A6000支撑VLLM部署，走整个Agent流程查3个地区的天气，1s~2s没问题。
目前看纯粹的依赖Model昨Agent还是有一定难度的...

**Comment by liyunhan** [comment]
> > 72b-gptq的话，我是放在了vllm两张卡支撑，速度还可以挺快的。 你提到的自动追问我也在尝试...我的思路还是依赖llm自身的能力，比如多加一个LLM查验参数的步骤，返回一个结果手动控制break出去。当用户补充完信息后，把所有的message再传进来从头开始执行，其实就是假定LLM会根据历史信息决定继续执行哪一步，但目前看效果比较差，不论怎么控制system_prompt，LLM都会固执的输出function_call的信息，并且自己编造一个地名（天气查询）拼接进去。
> > 其实function_calling和自己继承Agent实现的思路都差不多，都是可以自己施加控制，可以自己制定步骤和Prompt强制模型去验证参数完整性（可能需要一个固定的输出格式，方便自己return出去），当然这种情况可能比较适合工具执行顺序比较固定的业务，明确的会调用某几个工具并且严格按照顺序调用。 | 目前测试看，比如天气工具类，ReActChat的final_answer里有一定几率会说“我缺少某个xx信息，需要用户补充”，但也有一定概率直接就把amap_weather里面的“北京市海淀区”当成数据直接就调用工具去了。如果是我自己写的工具，description中如果有“例子”，那么大概率就直接当成数据填到工具表里调用工具去了....
> 
> 您的72b的响应速度大概几秒，我因为72b的响应速度太慢，所以采用了7b+72b混合的方式，先用7b实现工具调用，然后72b进行参数解析。我在调用百度的天气查询API时也出现了和您类似的情况，会在解析不了地点或者没给地点的时候自动生成北京的内容同时我出现了无论我在description中怎么强调某种规则或者指定参数值，LLM就是不听，给出None或者错误的值。。。QwQ
> 
> 刚正在写回复的时候看见了您的最新回答，我就是这么做的，我通过在while内设置一旦调用了我编写的function时，直接设置flag=True，记录这段对话期间的message，然后再while外层对这个flag进行判定，在LLM回复之前，一旦为True，直接默认调用工具进行提问，直到function在我的追问逻辑下补充满了所有标准规范格式的接口参数值后，才将flag设置为false，离开这段function对话流程。不过现在除了上面的问题之外，也出现了明明不是需要调用某个tools的问题，但是就因为用户的问题中出现了该tools的funciton的description中的某些字段，就自动调用该tools，导致产生了错误调用。。。

追问这个，我最终还是选择基于ReAct做了修改。我发现几个点：
1. 工具里description最好不要放真实的案例，比如“北京市海淀区”就修改成“xxx市xxx区”比较好。
2. ReAct的PROMPT，可以在Final Answer这一项下面加入“Notice! If parameter for 'Action Input' is missing, you must ask user in 'Final Answer' and stop doing anything.”  目前看qwen2-72b-chat-gptq是能够理解的。测试了：多参数缺项、单参数缺项，均通过单轮或多轮追问的方式成功调用function。
3. 我把ReAct的PROMPT放在了role:system，然后将PROMPT中Begin下面的Question放到了role:user的位置，在每次用户输入的时候都变成Question: xxxxx，一并修改PROMPT中的Question为“Question: the input question you must answer or info to help you answer question”，其中"or info to help you answer question"是修改添加的内容
