### ISSUE TITLE
functioncall 与 ReAct处理结果不一致

### ISSUE THREAD

**Issue by lucasjinreal** [QwenLM/Qwen-Agent#26]
就codeinterpretor而言，看起来二者逻辑差不多，但是目前测试的functioncall 虽然能正确调用并执行，但是 FinalAnswer总结的一直是英文，感觉丢失了一些上下文，

这是functioncall的debug信息：

````
Q: /code 计算1974年的3月23号是星期几
begin: no stream in qwen_chat_func
--------- turn: 0, messages: [{'role': 'user', 'content': '计算1974年的3月23号是星期几, 必须使用code_interpreter工具'}]
--------- turn: 0, rsp: {'role': 'assistant', 'content': 'Thought: 我需要使用code_interpreter来运行代码，计算1974年3月23日是星期几。', 'function_call': {'name': 'code_interpreter', 'arguments': '```py\nimport datetime\n\n# 设置日期\ndate = datetime.datetime(1974, 3, 23)\n\n# 获取星期几\nweekday = date.strftime("%A")\n\nweekday\n```'}}
INFO: kernel process's PID = 15008
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.

Observation: execute_result:


'Saturday'

begin: no stream in qwen_chat_func
--------- turn: 1, messages: [{'role': 'user', 'content': '计算1974年的3月23号是星期几, 必须使用code_interpreter工具'}, {'role': 'assistant', 'content': 'Thought: 我需要使用code_interpreter来运行代码，计算1974年3月23日是星期几。', 'function_call': {'name': 'code_interpreter', 'arguments': '```py\nimport datetime\n\n# 设置日期\ndate = datetime.datetime(1974, 3, 23)\n\n# 获取星期几\nweekday = date.strftime("%A")\n\nweekday\n```'}}, {'role': 'function', 'name': 'code_interpreter', 'content': "execute_result:\n\n```\n'Saturday'\n```"}]
--------- turn: 1, rsp: {'role': 'assistant', 'content': "The result of the execution is 'Saturday'.\n", 'function_call': None}
Observation: execute_result:


'Saturday'

Thought: I now know the final answer.
Observation: execute_result:


'Saturday'

Thought: I now know the final answer.
Final Answer: The result of the execution is 'Saturday'.
````

这是ReAct的信息：

````
Q: /code 计算1974年的3月23号是星期几
Now using locally deployed qwen
begin: no stream in qwen
Thought: 我需要使用code_interpreter来运行代码以计算日期。
Action: code_interpreter
Action Input:
```py
import datetime

# 定义日期
date = datetime.datetime(1974, 3, 23)

# 获取星期几
weekday = date.strftime("%A")

weekday
```

INFO: kernel process's PID = 25340
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.

execute_result:


'Saturday'

Now using locally deployed qwen
begin: no stream in qwen
 代码解释器返回了结果，1974年3月23日是星期六。
Final Answer: 1974年的3月23号是星期六。

Thought: 我需要使用code_interpreter来运行代码以计算日期。
Action: code_interpreter
Action Input:
```py
import datetime

# 定义日期
date = datetime.datetime(1974, 3, 23)

# 获取星期几
weekday = date.strftime("%A")

weekday
```
Observation: execute_result:


'Saturday'

Thought: 代码解释器返回了结果，1974年3月23日是星期六。
Final Answer: 1974年的3月23号是星期六。
````

可以看到，ReAct总结的FinalAnswer合理得多。

看起来是cuntioncall 上下文拼接的时候漏掉了一些上下文？

**Comment by JianxinMa** [comment]
是的，function calling与ReAct并非100%对应。具体而言，function calling会丢弃Final Answer前的那一次Thought，这个thought的内容一般是"I now know the final answer."。

至于出现英文回复，原因是：我在将 function calling 转换成 ReAct 时，会自动补一个“Thought: I now know the final answer.”或其中文版本 （见 https://github.com/QwenLM/Qwen/blob/main/openai_api.py#L212 ） ——  原本是应该根据中文请求就补一个中文的Thought的，但是我这里的判断写得疏忽了，导致实际补了个英文的Thought。

等我有空了会去完善下 openai_api.py 里的这部分逻辑。

**Comment by lucasjinreal** [comment]
@JianxinMa 感谢。加一个thought 他可能能回答中文，但看起来他好像忘记了问题，加一个thought感觉不一定能弥补回来

**Comment by lucasjinreal** [comment]
@JianxinMa 大佬， 
> 等我有空了会去完善下 openai_api.py 里的这部分逻辑。

这个问题可以优先修复一下吗

**Comment by JianxinMa** [comment]
我尝试了Qwen-14B-Chat，Qwen-7B-Chat没能复现出最终回答“忘记问题”的现象。请问有更多信息以供复现吗？

**Comment by lucasjinreal** [comment]
@tuhahaha  你可以打印出每一个turn的output吗，你第一个thought不应该是： Thought: 我需要使用code_interpreter来运行代码，计算1974年3月23日是星期几。？

我这边用Qwen14b openaiserver，没有办法得到 最终的结果。

@JianxinMa  > 是的，function calling与ReAct并非100%对应。具体而言，function calling会丢弃Final Answer前的那一次Thought，这个thought的内容一般是"I now know the final answer."。

至于出现英文回复，原因是：我在将 function calling 转换成 ReAct 时，会自动补一个“Thought: I now know the final answer.”或其中文版本 （见 https://github.com/QwenLM/Qwen/blob/main/openai_api.py#L212 ） —— 原本是应该根据中文请求就补一个中文的Thought的，但是我这里的判断写得疏忽了，导致实际补了个英文的Thought。

等我有空了会去完善下 openai_api.py 里的这部分逻辑。



我还以为大佬理解了我的问题，，，

**Comment by tuhahaha** [comment]
我这边用14B跑function call的输出是：
------- turn  0 [{"role": "user", "content": " 计算1974年的3月23号是星期几, 必须使用code_interpreter工具"}]
------- turn  0 {"role": "assistant", "content": "Thought: 我需要使用code_interpreter来运行代码，计算1974年3月23日是星期几。", "function_call": {"name": "code_interpreter", "arguments": "```py\nimport datetime\n\n# 设置日期\ndate = datetime.datetime(1974, 3, 23)\n\n# 计算星期几\nweekday = date.weekday()\n\n# 星期几的对应字典\nweekday_dict = {\n    0: '星期一',\n    1: '星期二',\n    2: '星期三',\n    3: '星期四',\n    4: '星期五',\n    5: '星期六',\n    6: '星期日'\n}\n\n# 输出结果\nweekday_dict[weekday]\n```"}}


------- turn  1 [{"role": "user", "content": " 计算1974年的3月23号是星期几, 必须使用code_interpreter工具"}, {"role": "assistant", "content": "Thought: 我需要使用code_interpreter来运行代码，计算1974年3月23日是星期几。", "function_call": {"name": "code_interpreter", "arguments": "```py\nimport datetime\n\n# 设置日期\ndate = datetime.datetime(1974, 3, 23)\n\n# 计算星期几\nweekday = date.weekday()\n\n# 星期几的对应字典\nweekday_dict = {\n    0: '星期一',\n    1: '星期二',\n    2: '星期三',\n    3: '星期四',\n    4: '星期五',\n    5: '星期六',\n    6: '星期日'\n}\n\n# 输出结果\nweekday_dict[weekday]\n```"}}, {"role": "function", "name": "code_interpreter", "content": "execute_result:\n\n```\n'星期六'\n```"}]
------- turn  1 {"role": "assistant", "content": "1974年3月23日是星期六。", "function_call": null}


最终答案也是正常的。
也许你可以看下你是否拉了BrowserQwen和Qwen 最新的代码？

**Comment by lucasjinreal** [comment]
@tuhahaha  感觉丢给模型的都是差不多的，为啥最后 一个返回的，我的总是英文，而且回答 没有 `1974年3月23日是` 这一部分？
我用的就是官方最新的代码呢

**Comment by tuhahaha** [comment]
你换一个其他问题也是英文？

**Comment by lucasjinreal** [comment]
对的，从原理上分析，可能是哪一部分缺失了？
