### ISSUE TITLE
运行run_server后，文件上传成功，问答之后显示无法读取

### ISSUE THREAD

**Issue by guhao17** [QwenLM/Qwen-Agent#267]
![image](https://github.com/QwenLM/Qwen-Agent/assets/116614355/25e6f734-2bbf-41e0-942a-6fc2bd76feaf)

**Comment by guhao17** [comment]
会不会是读取路径出了问题

**Comment by guhao17** [comment]
我在qwen_agent/utils/utils.py里面将163行的url = sanitize_chrome_file_path(path)注释掉后，问题解决

**Comment by JianxinMa** [comment]
感谢提供的线索，已尝试在main分支修复该bug。https://github.com/QwenLM/Qwen-Agent/commit/06fcd08a11c75e2467bc60c74856c367656e1205
