### ISSUE TITLE
Function Calling 串行调用如何实现

### ISSUE THREAD

**Issue by Miguitian** [QwenLM/Qwen-Agent#273]
在写好tools工具后，进行提问，调用单个工具是成功的。但是有个需求是 我要实现用户的提问，需要先进行一个函数的调用，拿到结果后，模型需要判断是否获取到了最后的答案，如果没有的话，需要判断是否需要调用第二个函数，并进行调用。 在实际使用中，往往第一个函数会进行调用，但是并不会触发第二个函数的调用。  尝试测试了[assistant_weather_bot.py](https://github.com/QwenLM/Qwen-Agent/blob/main/examples/assistant_weather_bot.py)，但是貌似也并没有调用第二个函数。  如果遇到这种情况，应该去调整哪里可以实现需求。

**Comment by JianxinMa** [comment]
串行调用的逻辑实现在这里：https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/agents/fncall_agent.py#L46 （Assistant类=FnCallAgent类+RAG功能）

**Comment by Miguitian** [comment]
我尝试直接使用FnCallAgent 开发智能体。 针对一次性问两个问题时，是可以针对这两个问题找到对应的函数并调用总结。但是如果我问需要推理的问题貌似就不会调用第二个函数。例如： 张三负责的服务器内存分别是多少。 应该先查询张三负责了哪些服务器，在根据查询到的服务器信息分别在查询内存是多少。 但是往往只能查询到负责了哪些服务器，并不会再去查询服务器的配置是什么。需要我来告诉他去查询哪个服务器才行。 我是应该调整提示词还是模型呢？还是串行调用并不支持这样查询呢？谢谢

**Comment by JianxinMa** [comment]
> 我尝试直接使用FnCallAgent 开发智能体。 针对一次性问两个问题时，是可以针对这两个问题找到对应的函数并调用总结。但是如果我问需要推理的问题貌似就不会调用第二个函数。例如： 张三负责的服务器内存分别是多少。 应该先查询张三负责了哪些服务器，在根据查询到的服务器信息分别在查询内存是多少。 但是往往只能查询到负责了哪些服务器，并不会再去查询服务器的配置是什么。需要我来告诉他去查询哪个服务器才行。 我是应该调整提示词还是模型呢？还是串行调用并不支持这样查询呢？谢谢

有条件的话可以试试qwen2-72b-instruct（或阿里云dashscope上比较大的模型的效果；需要注意的是，开源社区有些量化版本的72b会比非量化的表现差）。这类依赖推理的任务，调整提示词要调挺久的，如果能通过换模型、工程手段解决还是建议先靠换模型、上工程手段。
