### ISSUE TITLE
插件安装后，不能添加浏览记录

### ISSUE THREAD

**Issue by xman1991** [QwenLM/Qwen-Agent#28]
google浏览器，插件安装后，点击添加浏览记录后，并没有生成browse.jsonl和popup_url.jsonl

**Comment by JianxinMa** [comment]
请问方便贴一下 terminal 里的 log 吗？我们看下什么原因

**Comment by xman1991** [comment]
python run_server.py  --model_server  http://192.168.59.123:8000/v1  --workstation_port 7864
INFO:     Will watch for changes in these directories: ['/shawn/2532/Qwen-Agent']
ERROR:    [Errno 98] Address already in use
/shawn/2532/Qwen-Agent/qwen_server/app_in_browser.py:169: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.7 will cause issues.
  with gr.Column(scale=0.7):
/shawn/2532/Qwen-Agent/qwen_server/app_in_browser.py:175: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  with gr.Column(scale=0.1, min_width=0):
/shawn/2532/Qwen-Agent/qwen_server/app.py:442: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.3 will cause issues.
  with gr.Column(scale=0.3, min_width=0):
/shawn/2532/Qwen-Agent/qwen_server/app_in_browser.py:177: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  with gr.Column(scale=0.1, min_width=0):
/shawn/2532/Qwen-Agent/qwen_server/app_in_browser.py:179: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  with gr.Column(scale=0.1, min_width=0):
/shawn/2532/Qwen-Agent/qwen_server/app.py:447: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.7 will cause issues.
  with gr.Column(scale=0.7, min_width=0):
/shawn/2532/Qwen-Agent/qwen_server/app.py:536: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.05 will cause issues.
  with gr.Column(scale=0.05, min_width=0):
/shawn/2532/Qwen-Agent/qwen_server/app.py:538: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.16 will cause issues.
  with gr.Column(scale=0.16, min_width=0):
/shawn/2532/Qwen-Agent/qwen_server/app.py:540: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.02 will cause issues.
  with gr.Column(scale=0.02, min_width=0):
/shawn/2532/Qwen-Agent/qwen_server/app.py:544: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.65 will cause issues.
  with gr.Column(scale=0.65):
/shawn/2532/Qwen-Agent/qwen_server/app.py:548: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.05 will cause issues.
  with gr.Column(scale=0.05, min_width=0):
/shawn/2532/Qwen-Agent/qwen_server/app.py:551: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.05 will cause issues.
  with gr.Column(scale=0.05, min_width=0):
/shawn/2532/Qwen-Agent/qwen_server/app.py:553: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.05 will cause issues.
  with gr.Column(scale=0.05, min_width=0):
Running on local URL:  http://127.0.0.1:7863

Thanks for being a Gradio user! If you have questions or feedback, please join our Discord server and chat with us: https://discord.gg/feTf9x3ZSB
Running on local URL:  http://127.0.0.1:7864

To create a public link, set `share=True` in `launch()`.

To create a public link, set `share=True` in `launch()`.

**Comment by xman1991** [comment]
> python run_server.py --model_server http://192.168.59.123:8000/v1 --workstation_port 7864 INFO: Will watch for changes in these directories: ['/shawn/2532/Qwen-Agent'] ERROR: [Errno 98] Address already in use /shawn/2532/Qwen-Agent/qwen_server/app_in_browser.py:169: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.7 will cause issues. with gr.Column(scale=0.7): /shawn/2532/Qwen-Agent/qwen_server/app_in_browser.py:175: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.1 will cause issues. with gr.Column(scale=0.1, min_width=0): /shawn/2532/Qwen-Agent/qwen_server/app.py:442: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.3 will cause issues. with gr.Column(scale=0.3, min_width=0): /shawn/2532/Qwen-Agent/qwen_server/app_in_browser.py:177: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.1 will cause issues. with gr.Column(scale=0.1, min_width=0): /shawn/2532/Qwen-Agent/qwen_server/app_in_browser.py:179: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.1 will cause issues. with gr.Column(scale=0.1, min_width=0): /shawn/2532/Qwen-Agent/qwen_server/app.py:447: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.7 will cause issues. with gr.Column(scale=0.7, min_width=0): /shawn/2532/Qwen-Agent/qwen_server/app.py:536: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.05 will cause issues. with gr.Column(scale=0.05, min_width=0): /shawn/2532/Qwen-Agent/qwen_server/app.py:538: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.16 will cause issues. with gr.Column(scale=0.16, min_width=0): /shawn/2532/Qwen-Agent/qwen_server/app.py:540: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.02 will cause issues. with gr.Column(scale=0.02, min_width=0): /shawn/2532/Qwen-Agent/qwen_server/app.py:544: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.65 will cause issues. with gr.Column(scale=0.65): /shawn/2532/Qwen-Agent/qwen_server/app.py:548: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.05 will cause issues. with gr.Column(scale=0.05, min_width=0): /shawn/2532/Qwen-Agent/qwen_server/app.py:551: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.05 will cause issues. with gr.Column(scale=0.05, min_width=0): /shawn/2532/Qwen-Agent/qwen_server/app.py:553: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.05 will cause issues. with gr.Column(scale=0.05, min_width=0): Running on local URL: http://127.0.0.1:7863
> 
> Thanks for being a Gradio user! If you have questions or feedback, please join our Discord server and chat with us: https://discord.gg/feTf9x3ZSB Running on local URL: http://127.0.0.1:7864
> 
> To create a public link, set `share=True` in `launch()`.
> 
> To create a public link, set `share=True` in `launch()`.

添加浏览记录时，terminal没有仍和反应

**Comment by JianxinMa** [comment]
请问您部署 run_server.py 的机器和打开浏览器的机器是同一台吗？如果不是，需要参考 https://github.com/QwenLM/Qwen-Agent/issues/20#issuecomment-1751890499 操作。

如果是同一台机器，可以检查：
1. 点击浏览器插件的图标（地址栏右侧的那个图标，不是页面的那个Add按钮），检查是否能正常看到对话界面。
2. 如果1正常，则在网页右键点击“Inspect（检查）”，然后看弹出的Chrome debug界面的“Console”里是否有任何报错。

**Comment by xman1991** [comment]
1是正常的，2检查的时候，看到Console有这个报错：A cookie was not sent to a secure origin from an insecure context. Because this cookie would have been sent across schemes on the same site, it was not sent. This behavior enhances the SameSite attribute’s protection of user data from request forgery by network attackers.
Resolve this issue by migrating your site (as defined by the eTLD+1) entirely to HTTPS. It is also recommended to mark the cookie with the Secure attribute if that is not already the case.

**Comment by xman1991** [comment]
1是正常的，2检查的时候也没看到报错。

**Comment by xman1991** [comment]
方便远程看下么？

**Comment by xman1991** [comment]
> 请问您部署 run_server.py 的机器和打开浏览器的机器是同一台吗？如果不是，需要参考 [#20 (comment)](https://github.com/QwenLM/Qwen-Agent/issues/20#issuecomment-1751890499) 操作。
> 
> 如果是同一台机器，可以检查：
> 
>     1. 点击浏览器插件的图标（地址栏右侧的那个图标，不是页面的那个Add按钮），检查是否能正常看到对话界面。
> 
>     2. 如果1正常，则在网页右键点击“Inspect（检查）”，然后看弹出的Chrome debug界面的“Console”里是否有任何报错。
run_server.py和打开浏览器是同一台机器

**Comment by xman1991** [comment]
可以了，是runserver的服务端口被占用了，之前没注意。
