### ISSUE TITLE
网页上chatbot窗口不能滚动

### ISSUE THREAD

**Issue by wolfcx5** [QwenLM/Qwen-Agent#287]
![QWEN滚动条](https://github.com/user-attachments/assets/53ce1530-ccc9-4e7b-8cd1-64265e1b477d)
运行这个Qwen-Agent-main/examples/assistant_rag.py，然后图中红框里边的滚动条不能动是咋回事啊，是不是modelscope_studio.Chatbot出的问题

**Comment by JianxinMa** [comment]
一般是gradio版本兼容性问题。试试` pip install "gradio==4.21.0" "modelscope-studio>=0.4.0"`
