### ISSUE TITLE
怎么注册自定义的tool呢？

### ISSUE THREAD

**Issue by 332123342** [QwenLM/Qwen-Agent#299]

**Comment by JianxinMa** [comment]
https://github.com/QwenLM/Qwen-Agent/blob/main/README_CN.md#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%8F%91
https://github.com/QwenLM/Qwen-Agent/blob/main/docs/tool_cn.md
https://github.com/QwenLM/Qwen-Agent/blob/main/examples/assistant_add_custom_tool.py#L17
