### ISSUE TITLE
web chat貌似很费显存

### ISSUE THREAD

**Issue by liaoweiguo** [QwenLM/Qwen-Agent#3]
随便带一个页面就爆了，14B-Int4，RTX4090，用的单显卡

**Comment by liaoweiguo** [comment]
readme上那几个演示，用的是什么硬件配置？

**Comment by JianxinMa** [comment]
演示用的A100 40G，跑的Qwen-7B-Chat。关于14B-int4费显存，我们看下，在看是不是要缩减下输入输出文本的字数。

**Comment by liaoweiguo** [comment]
换7B不爆，理论上14B-Int4不会比7B要求更高的显存？
