### ISSUE TITLE
function_call 调用不稳定，有时候能调用，有时候不会调用，有没有什么技巧实现稳定调用呢？

### ISSUE THREAD

**Issue by 332123342** [QwenLM/Qwen-Agent#302]
测试代码如下

**Comment by 332123342** [comment]
```
import os
import sys
import json
from typing import Dict, Optional, Union

sys.path.insert(0, "/data/workspace/modelscope-agent")

from modelscope_agent.agents import RolePlay
from modelscope_agent.tools.base import BaseTool
from modelscope_agent.tools import register_tool


@register_tool("UserDatabase")
class UserDatabase(BaseTool):
    description = "企业员工数据库，包含员工的性别、生日、职位信息"
    name = "UserDatabase"
    parameters: list = [
        {
            "name": "name",
            "type": "string",
            "description": "员工名字，所属查阅信息的员工姓名，如`张三",
            "required": True,
        }
    ]

    def __init__(self, cfg: Optional[Dict] = None):
        super().__init__(cfg)

        # 数据库存有员工基本信息
        self.database = {
            "李四": {"性别": "女", "生日": "10月3日", "职位": "画师"},
            "张三": {"性别": "男", "生日": "5月5日", "职位": "业务员"},
            "王五": {"性别": "男", "生日": "12月19日", "职位": "业务经理"},
        }

    def call(self, params: Union[str, dict], **kwargs) -> str:
        params = self._verify_args(params)

        name = params["name"]
        # 输入姓名返回员工信息
        return json.dumps(self.database.get(name, "查无此人"), ensure_ascii=False)


role_template = ""
llm_config = {
    "model": "qwen2:7b-instruct",
    "model_server": "ollama",
}
function_list = ["UserDatabase"]

bot = RolePlay(function_list=function_list, llm=llm_config, instruction=role_template)

response = bot.run(
    "职工张三的生日是在今年10月份吗？现在是2月份，距离张三的生日还有几个月？",
    remote=False,
    print_info=True,
)
text = ""
for chunk in response:
    text += chunk
print(text)
```

**Comment by JianxinMa** [comment]
您好，您这个是modelscope_agent的代码，和qwen-agent不是一个项目（虽然两者用法确实很像，因为有段时间合作过；但用的prompts和细节不太一样）。

我改成qwen-agent测了几次能调用：
```py
import os
import sys
import json
from typing import Dict, Optional, Union

from qwen_agent.agents import FnCallAgent
from qwen_agent.tools.base import BaseTool, register_tool


@register_tool("UserDatabase")
class UserDatabase(BaseTool):
    description = "企业员工数据库，包含员工的性别、生日、职位信息"
    name = "UserDatabase"
    parameters: list = [
        {
            "name": "name",
            "type": "string",
            "description": "员工名字，所属查阅信息的员工姓名，如`张三",
            "required": True,
        }
    ]

    def __init__(self, cfg: Optional[Dict] = None):
        super().__init__(cfg)

        # 数据库存有员工基本信息
        self.database = {
            "李四": {"性别": "女", "生日": "10月3日", "职位": "画师"},
            "张三": {"性别": "男", "生日": "5月5日", "职位": "业务员"},
            "王五": {"性别": "男", "生日": "12月19日", "职位": "业务经理"},
        }

    def call(self, params: Union[str, dict], **kwargs) -> str:
        params = self._verify_json_format_args(params)

        name = params["name"]
        # 输入姓名返回员工信息
        return json.dumps(self.database.get(name, "查无此人"), ensure_ascii=False)


llm_config = {
    "model": "qwen2:7b",
    "model_server": "http://localhost:11434/v1/",
    "api_key": "ollama",
}
function_list = ["UserDatabase"]
bot = FnCallAgent(function_list=function_list, llm=llm_config)

for response in bot.run(
        messages=[{'role': 'user', 'content': "职工张三的生日是在今年10月份吗？现在是2月份，距离张三的生日还有几个月？"}]
):
    print(response)

```

预期输出：
```
[{'role': 'assistant', 'content': '', 'function_call': {'name': 'UserDatabase', 'arguments': '{"name": "张三"}'}}, {'role': 'function', 'content': '{"性别": "男", "生日": "5月5日", "职位": "业务员"}', 'name': 'UserDatabase'}, {'role': 'assistant', 'content': '职工张三的生日并不是在10月份，而是5月5日。现在是2月份，从2月份到5月份共有3个月的时间间隔。所以距离张三的生日还有3个月。'}]
```

**Comment by 332123342** [comment]
> 您好，您这个是modelscope_agent的代码，和qwen-agent不是一个项目（虽然两者用法确实很像，因为有段时间合作过；但用的prompts和细节不太一样）。
> 
> 我改成qwen-agent测了几次能调用：
> 
> ```python
> import os
> import sys
> import json
> from typing import Dict, Optional, Union
> 
> from qwen_agent.agents import FnCallAgent
> from qwen_agent.tools.base import BaseTool, register_tool
> 
> 
> @register_tool("UserDatabase")
> class UserDatabase(BaseTool):
>     description = "企业员工数据库，包含员工的性别、生日、职位信息"
>     name = "UserDatabase"
>     parameters: list = [
>         {
>             "name": "name",
>             "type": "string",
>             "description": "员工名字，所属查阅信息的员工姓名，如`张三",
>             "required": True,
>         }
>     ]
> 
>     def __init__(self, cfg: Optional[Dict] = None):
>         super().__init__(cfg)
> 
>         # 数据库存有员工基本信息
>         self.database = {
>             "李四": {"性别": "女", "生日": "10月3日", "职位": "画师"},
>             "张三": {"性别": "男", "生日": "5月5日", "职位": "业务员"},
>             "王五": {"性别": "男", "生日": "12月19日", "职位": "业务经理"},
>         }
> 
>     def call(self, params: Union[str, dict], **kwargs) -> str:
>         params = self._verify_json_format_args(params)
> 
>         name = params["name"]
>         # 输入姓名返回员工信息
>         return json.dumps(self.database.get(name, "查无此人"), ensure_ascii=False)
> 
> 
> llm_config = {
>     "model": "qwen2:7b",
>     "model_server": "http://localhost:11434/v1/",
>     "api_key": "ollama",
> }
> function_list = ["UserDatabase"]
> bot = FnCallAgent(function_list=function_list, llm=llm_config)
> 
> for response in bot.run(
>         messages=[{'role': 'user', 'content': "职工张三的生日是在今年10月份吗？现在是2月份，距离张三的生日还有几个月？"}]
> ):
>     print(response)
> ```
> 
> 预期输出：
> 
> ```
> [{'role': 'assistant', 'content': '', 'function_call': {'name': 'UserDatabase', 'arguments': '{"name": "张三"}'}}, {'role': 'function', 'content': '{"性别": "男", "生日": "5月5日", "职位": "业务员"}', 'name': 'UserDatabase'}, {'role': 'assistant', 'content': '职工张三的生日并不是在10月份，而是5月5日。现在是2月份，从2月份到5月份共有3个月的时间间隔。所以距离张三的生日还有3个月。'}]
> ```

sorry, 粘错代码了。。。
