### ISSUE TITLE
【与bug无关但不吐不快】关于example的选取

### ISSUE THREAD

**Issue by lilichennn** [QwenLM/Qwen-Agent#306]
很感谢各位的辛勤研发，qwen在我们的项目中各个方面表现的都很突出，也很自豪我们国内的模型有这么好的能力。

但是/example中
女孩：长痘，催婚，带孩子，身材走形。
女友：生气得哄，”你身材真好“，”你真好看“

我请问呢？
1. 男人呢？
2. 只要用女性举例就是 生气，身材，美貌？

女性的任何其他存在意义和价值仍然无法作为一个在您们脑海里一触即发，一提就有的存在是吗？

不得不说您们这俩个例子点醒了我为什么大模型这么会擦边。

说了跟大家关注点无关的话题我很抱歉。

以上。

**Comment by JianxinMa** [comment]
感谢您的提醒，我们抽空换掉。

PS：我们绝不鼓励刻板印象、无意贬低女性、也不希望这些示例给大家带来任何方面的焦虑。实际上，我们团队有不少优秀的女性同事，她们的技术水平在计算机这个刻板印象里男多女少的行业吊打绝大部分同事。

**Comment by lilichennn** [comment]
> 感谢您的提醒，我们抽空换掉。
> 
> PS：我们绝不鼓励刻板印象、无意贬低女性、也不希望这些示例给大家带来任何方面的焦虑。实际上，我们团队有不少优秀的女性同事，她们的技术水平在计算机这个刻板印象里男多女少的行业吊打绝大部分同事。

谢谢您的关注，我也十分认同后半段话，读博期间cs办公室一半的博士生都是很女生。

我也相信在计算机这一个不依靠体能的领域会有越来越多的女性大放异彩。

期待后续更新
