### ISSUE TITLE
Support uploading local PDFs when the browser and the server are on two different machines.

### ISSUE THREAD

**Issue by JianxinMa** [QwenLM/Qwen-Agent#31]
I'm opening this issue to track this: https://github.com/QwenLM/Qwen-Agent/issues/20#issuecomment-1758855494

**Comment by tuhahaha** [comment]
Currently, it supports uploading local PDF files on the workstation.

**Comment by JianxinMa** [comment]
Does it work if I open a local PDF in the browser and ask the Qwen Assistant (not Workstation) deployed on a remote machine?
