### ISSUE TITLE
qwen-agent博客所说的分块阅读，采用暴力机制对每一个分块进行LLM判别，是否性能存在问题？

### ISSUE THREAD

**Issue by pengyuxiang1** [QwenLM/Qwen-Agent#315]
看到qwen-agent在博客中提到，对于每一个分块都进行阅读，请问这是否合理呀？百万长度的文档，一个子问题就需要1*10^6/512 =2000 次的LLM调用了。

![image](https://github.com/user-attachments/assets/8f4e20f7-e527-4db2-bc63-e3d84e10d3e8)

还是说，这里其实指的是：先BM25进关键字粗筛，再用LLM重排的策略？

**Comment by JianxinMa** [comment]
“百万长度的文档，一个子问题就需要1*10^6/512 =2000 次的LLM调用了。”—— 是的，目前会有性能问题。 但这个是大模型领域的新趋势了，目前大模型的调用成本开始大幅下降，一两年后大家就会对对此感到稀松平常了（GraphRAG等工作调用llm的次数更加离谱。）

此外，这个方法我们主要是用来离线做合成训练数据的，因此不是很在意性能。

**Comment by pengyuxiang1** [comment]
soga，如果你们也是离线的用途，那我没有什么问题了。

GraphRAG也是离线建立的全局关系图，然后实时回答问题时，直接是走的图数据库索引，它兼具了全文信息和快速的优点，我觉得那种方案是可行的。

你们这个方案如果用在离线场景，那我觉得也挺好的。也许你们也可以考虑，不仅用来合成训练数据，也可以离线跑一些的全文的问答对，然后写一个算法去保证生成的问答对的质量。质量ok的存到向量数据库也好，其他数据库也好。覆盖面足够的时候，对智能客服实时场景感觉也是很有帮助的，也能回答很多问题了。

**Comment by pengyuxiang1** [comment]
qwen-agent博客所说的分块阅读适用于离线场景。
