### ISSUE TITLE
uncheckd browser list items are  still included as prompt info

### ISSUE THREAD

**Issue by wangyanbn** [QwenLM/Qwen-Agent#32]
In the workstation web page,  after I uncheckd some browser list items, they are  still included as prompt info when  chating with the LLM.
Is there no process for browser list item uncheck?

**Comment by tuhahaha** [comment]
Hello, we have implemented the process of canceling browsing items. Perhaps you can refresh the page to see if the browsing item you cancelled still shows a checked status. If it is not checked, it indicates that the operation is correct. If it is checked, please paste the debugging information here. Thank you.

**Comment by wangyanbn** [comment]
Great job! @tuhahaha 
I have found the codes about browsing item check/uncheck processing in [main.js](https://github.com/QwenLM/Qwen-Agent/blob/d1a7ca9b4b45e27ca6da4432fde6edb0c4960f0d/qwen_server/js/main.js#L30C3-L30C3)

The ip is fixed as `127.0.0.1`, if the service is on other machine, this will cause network error.
When my service is on my local machine, if I use `127.0.0.1` to access the app page,  this works fine; 
But when I access the app page with the machine's real ip, the js fetch of `http://127.0.0.1:7866/endpoint` will cause CORS error. 
I changed the `127.0.0.1` as real page ip in main.js ( use location.hostname), it is still CORS error. The [allow_origins of `http://0.0.0.0`](https://github.com/QwenLM/Qwen-Agent/blob/d1a7ca9b4b45e27ca6da4432fde6edb0c4960f0d/qwen_server/main.py#L42C11-L42C11 ) seems doesn't work. 

When I add the real machine ip into the allow_origins , it is ok now now.
I don't know well about the fastapi CORSMiddleware, maybe there is a general config  for it (no need adding the real machine ip).

**Comment by tuhahaha** [comment]
Thank you for your suggestion. I am modifying the code to make it more suitable for remote server scenarios. Additionally, if your server is remote, the current version does not support uploading and analyzing local PDF files. Web pages and online PDFs are acceptable. (The main reason is that the Google Extension have some limitations when processing local file uploads.) For this situation, we have implemented an interface for directly uploading PDF files, which may soon become available.

**Comment by tuhahaha** [comment]
@wangyanbn Hello , we have pushed the code to solve this problem. Please pull the latest code and update the Google Extension.
