### ISSUE TITLE
RAG会走LLM嘛？

### ISSUE THREAD

**Issue by RyanOvO** [QwenLM/Qwen-Agent#330]
[assistant_rag](https://github.com/QwenLM/Qwen-Agent/blob/main/examples/assistant_rag.py)  文档中的RAG，取到文档数据后，会再调用LLM返回响应嘛？

**Comment by JianxinMa** [comment]
会

**Comment by RyanOvO** [comment]
> 会

就是说，用户提问时，qwen-agent先到文档中检索匹配到数据块，再拿到数据块去LLM中做query，由LLM返回response给用户。
