### ISSUE TITLE
Feature request: Copy button, Select a text span, More Interactive Options

### ISSUE THREAD

**Issue by JianxinMa** [QwenLM/Qwen-Agent#34]
As suggested by some users in our wechat group:

Gradio有，因此容易加的：
- 回答的小窗口增加一个“复制”按钮。

需要前端开发工作量：
- 框定一段文本，针对这段文本进行处理、问答。

需要算法、UI/UX设计：
- “基于知识生成的增量扩展：交互少的时候粗粒度但准确；需要更精细内容时，可以多交互以获得更高准确性。”

**Comment by JianxinMa** [comment]
@tuhahaha copy button可以下次更新顺便加了。其余两个功能工作量较大，我想想。

**Comment by tuhahaha** [comment]
copy button我曾经加过，但可能是插件的popup页面是引入iframe页面，导致copy button失效了，我再看下～
