### ISSUE TITLE
Start Date cannot update automatically

### ISSUE THREAD

**Issue by hustwyk** [QwenLM/Qwen-Agent#35]
In the WorkStation page, the `Start Date` and `End Date` cannot update automatically after one day. 
The code in `app.py` is 
```python
date1 = gr.Dropdown([str(datetime.date.today()-datetime.timedelta(days=i)) for i in range(config_browserqwen.max_days)], value=str(datetime.date.today()), label='Start Date')
date2 = gr.Dropdown([str(datetime.date.today()-datetime.timedelta(days=i)) for i in range(config_browserqwen.max_days)], value=str(datetime.date.today()), label='End Date')
```
It can be loaded only when I run this script.
Is there any idea to update the date automatically?

**Comment by tuhahaha** [comment]
Under the current settings, the date can be automatically updated every time the page is refreshed. Perhaps you could try refreshing the page?

**Comment by hustwyk** [comment]
I've tried refreshing the page, however the date cannot update automatically. I have to restart the `run_server.py` to make the date refreshed.

**Comment by tuhahaha** [comment]
Sorry, I made a mistake. The current date cannot be updated. We can update the date by calling a function, and I will update it soon.

**Comment by tuhahaha** [comment]
Hello, I have pushed the code to support date updates and use [this function](https://github.com/QwenLM/Qwen-Agent/blob/41c184514f5b8322cc5c0cbb9dd24afe25c8208e/qwen_server/workstation_server.py#L127). Please refresh the Google Extension after pulling the latest code, as we have updated the corresponding code.
