### ISSUE TITLE
求教大佬，RGA如何设置取分数最高的reference chunk?如何设置top_k

### ISSUE THREAD

**Issue by GreatWildFire** [QwenLM/Qwen-Agent#353]
目前我看到了DEFAULT_MAX_REF_TOKEN和DEFAULT_PARSER_PAGE_SIZE。
1.请问是只能使用这种方式设置ref chunk么？
2.检索工具的sort_by_scores功能似乎没起作用，不管我问什么问题，排序的先后顺序都一样。

劳烦大佬有空指导一下， 谢谢了

**Comment by JianxinMa** [comment]
1. 还可以通过给Assistant类的__init__传个rag_cfg来配置，给rag_cfg会传递给Memory类，rag_cfg可填的内容见注释：https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/memory/memory.py#L33 
2. sort_by_scores是在筛选chunks时用的，筛选完后会按原文里chunk的顺序对筛选出来的chunks进行排序（复原位置）。
