### ISSUE TITLE
在远程服务器上跑的，但是本地链接上去问一个问题就报连接错误

### ISSUE THREAD

**Issue by iaoxuesheng** [QwenLM/Qwen-Agent#37]
![2](https://github.com/QwenLM/Qwen-Agent/assets/94165844/37f1f1b4-8b50-4834-8345-cae087d85686)
请问这个怎么解决

**Comment by tuhahaha** [comment]
python run_server.py --model_server http://127.0.0.1:7905/v1，这里把127.0.0.1改成你的服务器ip

**Comment by iaoxuesheng** [comment]
还是拒绝连接，而且我发现在启动Qwen时返回的那个连接也上不去，不知道是不是这个原因

**Comment by tuhahaha** [comment]
启动Qwen那里的命令不用改，上不去的具体报错是什么？

**Comment by tuhahaha** [comment]
@iaoxuesheng 目前更新了一版代码，我这边测试可以比较好的支持远程服务的情况，你可以先用dashscope api访问qwen，来测试是否是qwen部署问题。

**Comment by cheng18175030250** [comment]
> python run_server.py --model_server [http://127.0.0.1:7905/v1，这里把127.0.0.1改成你的服务器ip](http://127.0.0.1:7905/v1%EF%BC%8C%E8%BF%99%E9%87%8C%E6%8A%8A127.0.0.1%E6%94%B9%E6%88%90%E4%BD%A0%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8ip)

能否出一个本地部署qwen-agent并使用的完整案例，我看网上本地部署的教程中，都有“启动模型服务 这一步骤，python openai_api.py --server-name 0.0.0.0 --server-port 7905 -c Qwen/Qwen-7B-Chat，但是现在的仓库中 并没有openai_api.py这个文件”？

**Comment by JianxinMa** [comment]
> > python run_server.py --model_server [http://127.0.0.1:7905/v1，这里把127.0.0.1改成你的服务器ip](http://127.0.0.1:7905/v1%EF%BC%8C%E8%BF%99%E9%87%8C%E6%8A%8A127.0.0.1%E6%94%B9%E6%88%90%E4%BD%A0%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8ip)
> 
> 能否出一个本地部署qwen-agent并使用的完整案例，我看网上本地部署的教程中，都有“启动模型服务 这一步骤，python openai_api.py --server-name 0.0.0.0 --server-port 7905 -c Qwen/Qwen-7B-Chat，但是现在的仓库中 并没有openai_api.py这个文件”？

openai_api.py是Qwen1用的，不支持Qwen1.5。我们现在推荐大家参考 Qwen1.5 的文档部署一个 openai 兼容的 api，就能使用了。vllm、ollama等等框架都能提供这个 openai 兼容的api。

**Comment by cheng18175030250** [comment]
> > > python run_server.py --model_server [http://127.0.0.1:7905/v1，这里把127.0.0.1改成你的服务器ip](http://127.0.0.1:7905/v1%EF%BC%8C%E8%BF%99%E9%87%8C%E6%8A%8A127.0.0.1%E6%94%B9%E6%88%90%E4%BD%A0%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8ip)
> > 
> > 
> > 能否出一个本地部署qwen-agent并使用的完整案例，我看网上本地部署的教程中，都有“启动模型服务 这一步骤，python openai_api.py --server-name 0.0.0.0 --server-port 7905 -c Qwen/Qwen-7B-Chat，但是现在的仓库中 并没有openai_api.py这个文件”？
> 
> openai_api.py是Qwen1用的，不支持Qwen1.5。我们现在推荐大家参考 Qwen1.5 的文档部署一个 openai 兼容的 api，就能使用了。vllm、ollama等等框架都能提供这个 openai 兼容的api。

谢谢，能否出一个完整的部署案例教程

**Comment by JianxinMa** [comment]
> > > > python run_server.py --model_server [http://127.0.0.1:7905/v1，这里把127.0.0.1改成你的服务器ip](http://127.0.0.1:7905/v1%EF%BC%8C%E8%BF%99%E9%87%8C%E6%8A%8A127.0.0.1%E6%94%B9%E6%88%90%E4%BD%A0%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8ip)
> > > 
> > > 
> > > 能否出一个本地部署qwen-agent并使用的完整案例，我看网上本地部署的教程中，都有“启动模型服务 这一步骤，python openai_api.py --server-name 0.0.0.0 --server-port 7905 -c Qwen/Qwen-7B-Chat，但是现在的仓库中 并没有openai_api.py这个文件”？
> > 
> > 
> > openai_api.py是Qwen1用的，不支持Qwen1.5。我们现在推荐大家参考 Qwen1.5 的文档部署一个 openai 兼容的 api，就能使用了。vllm、ollama等等框架都能提供这个 openai 兼容的api。
> 
> 谢谢，能否出一个完整的部署案例教程

vllm参考 https://qwen.readthedocs.io/en/latest/deployment/vllm.html#openai-api-compatible-api-service ，启动 `python -m vllm.entrypoints.openai.api_server     --model Qwen/Qwen1.5-7B-Chat ` 后就能有 openai 兼容的服务了。

ollama参考 https://github.com/ollama/ollama/blob/main/docs/openai.md 。

我们近期找时间更新下文档补充下。如果您跑vllm、ollama遇到困难也可以随时提issues（vllm支持高吞吐、ollama则支持本地cpu&gpu部署）

**Comment by qingqinghu1026** [comment]
> > > > > python run_server.py --model_server [http://127.0.0.1:7905/v1，这里把127.0.0.1改成你的服务器ip](http://127.0.0.1:7905/v1%EF%BC%8C%E8%BF%99%E9%87%8C%E6%8A%8A127.0.0.1%E6%94%B9%E6%88%90%E4%BD%A0%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8ip)
> > > > 
> > > > 
> > > > 能否出一个本地部署qwen-agent并使用的完整案例，我看网上本地部署的教程中，都有“启动模型服务 这一步骤，python openai_api.py --server-name 0.0.0.0 --server-port 7905 -c Qwen/Qwen-7B-Chat，但是现在的仓库中 并没有openai_api.py这个文件”？
> > > 
> > > 
> > > openai_api.py是Qwen1用的，不支持Qwen1.5。我们现在推荐大家参考 Qwen1.5 的文档部署一个 openai 兼容的 api，就能使用了。vllm、ollama等等框架都能提供这个 openai 兼容的api。
> > 
> > 
> > 谢谢，能否出一个完整的部署案例教程
> 
> vllm参考 https://qwen.readthedocs.io/en/latest/deployment/vllm.html#openai-api-compatible-api-service ，启动 `python -m vllm.entrypoints.openai.api_server --model Qwen/Qwen1.5-7B-Chat ` 后就能有 openai 兼容的服务了。
> 
> ollama参考 https://github.com/ollama/ollama/blob/main/docs/openai.md 。
> 
> 我们近期找时间更新下文档补充下。如果您跑vllm、ollama遇到困难也可以随时提issues（vllm支持高吞吐、ollama则支持本地cpu&gpu部署）

>使用ollama 部署qwen模型，以下方式可以成功调用qwen模型。
response = ollama.chat(
 model = 'qwen:7b-chat',
 messages = messages）

>但是在Agent使用时，
`def test(query='hello'):
    llm = get_chat_model(
       
        # Use your own model service compatible with OpenAI API:
        'model': 'qwen:7b-chat',
        'model_server': 'http://127.0.0.1:11434',  # api_base
        'api_key': 'EMPTY',
    })

    # Chat
    messages = []

    messages.append({'role': 'user', 'content': query})

    responses = []
    for responses in llm.chat(messages=messages,
                            #   functions=functions,
                              stream=True):
        print(responses)`
调用不成功。在执行代码前，已执行如下命令：
ollama serve
ollama run qwen:7b-chat
python run_server.py --llm qwen:7b-chat --model_server http://127.0.0.1:11434/v1
2024-04-12 09:51:54,522 - run_server.py - 85 - INFO - path=PathConfig(work_space_root='workspace/', database_root='workspace/database/', download_root='workspace/download/', code_interpreter_ws='workspace/ci_workspace/') server=ServerConfig(server_host='127.0.0.1', fast_api_port=7866, app_in_browser_port=7863, workstation_port=7864, model_server='http://127.0.0.1:11434/v1', api_key='', llm='qwen:7b-chat', max_ref_token=4000, max_days=7, functions=['code_interpreter', 'image_gen'])
2024-04-12 09:51:56,788 - database_server.py - 35 - INFO - 192.168.127.36
2024-04-12 09:51:56,802 - database_server.py - 35 - INFO - 192.168.127.36
INFO:     Started server process [472857]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:7866 (Press CTRL+C to quit)
Running on local URL:  http://127.0.0.1:7863

To create a public link, set `share=True` in `launch()`.
Running on local URL:  http://127.0.0.1:7864

To create a public link, set `share=True` in `launch()`.

报错信息如下：
File "/home/mmtech/anaconda3/envs/py39/lib/python3.9/site-packages/openai/_base_client.py", line 993, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: 404 page not found

During handling of the above exception, another exception occurred:
File "/home/mmtech/anaconda3/envs/py39/lib/python3.9/site-packages/qwen_agent/llm/oai.py", line 99, in _chat_stream
    raise ModelServiceError(exception=ex)
qwen_agent.llm.base.ModelServiceError: 404 page not found
