### ISSUE TITLE
如果给Agent配置Proxy？

### ISSUE THREAD

**Issue by dickens88** [QwenLM/Qwen-Agent#393]
假设我需要给Agent配置openai的接口，但是我的环境无法直接调用openai API，我需要让AGENT通过一个HTTP PROXY访问API，所以如果给Agent配置Proxy？

**Comment by tuhahaha** [comment]
建议新注册一个llm class，可以参考现在的oai，把调用openai API的地方（self._chat_complete_create）替换成访问HTTP PROXY即可。应该改动几行代码就行。

**Comment by dickens88** [comment]
> 建议新注册一个llm class，可以参考现在的oai，把调用openai API的地方（self._chat_complete_create）替换成访问HTTP PROXY即可。应该改动几行代码就行。

感谢回复，我觉得这个方法可行！
