### ISSUE TITLE
Agent支持循环调用吗？

### ISSUE THREAD

**Issue by joyvw** [QwenLM/Qwen-Agent#396]
请问使用多Agent路由时，有多个Agent循环调用，或者是多个 Agent 自动协作处理问题的功能吗

**Comment by tuhahaha** [comment]
有的，Agent可以灵活的嵌套调用Agent，例如[这个](https://github.com/QwenLM/Qwen-Agent/blob/main/examples/visual_storytelling.py)例子是一个固定好流程的Agent嵌套

**Comment by tuhahaha** [comment]
此外，如果你想多个 Agent 自动协作，可以使用GroupChat Agent，参考这个[例子](https://github.com/QwenLM/Qwen-Agent/blob/main/examples/group_chat_chess.py)

**Comment by joyvw** [comment]
> 此外，如果你想多个 Agent 自动协作，可以使用GroupChat Agent，参考这个[例子](https://github.com/QwenLM/Qwen-Agent/blob/main/examples/group_chat_chess.py)

好的，我参考一下看看。
