### ISSUE TITLE
是否有计划支持 model context protocol？

### ISSUE THREAD

**Issue by jesenzhang** [QwenLM/Qwen-Agent#397]
如题

**Comment by tuhahaha** [comment]
您好，据我所知model context protocol主要提供一种工具共享的平台，而qwen-agent支持注册工具的形式来调用工具，事实上工具可以在任何服务器上。也就是说如果MCP提供的工具可以足够方便的调用，那可以接入。但我们现在还没有这个计划。

**Comment by jesenzhang** [comment]
感谢回复
