### ISSUE TITLE
请问windows版本何时提供

### ISSUE THREAD

**Issue by BUPTLdy** [QwenLM/Qwen-Agent#4]

**Comment by tuhahaha** [comment]
现在的版本也是支持windows的，可以按照readme尝试安装一遍，如果遇到问题请贴到这里

**Comment by JianxinMa** [comment]
> 现在的版本也是支持windows的，可以按照readme尝试安装一遍，如果遇到问题请贴到这里

Windows没测试过，不排除有坑，正在配置Windows环境测试。WSL2倒是测试过，是能work的，因为WSL本质上是linux。

**Comment by JianxinMa** [comment]
btw，如果是代码解释器（Code Interpreter）功能的话，Qwen模型生成的代码大部分默认是按Linux/MacOS的环境写的，所以Windows下可能容易出问题。

**Comment by JianxinMa** [comment]
Windows下自测发现的问题已修复。如果有新的问题，欢迎提issues~
