### ISSUE TITLE
网页问答异常

### ISSUE THREAD

**Issue by MrRace** [QwenLM/Qwen-Agent#40]
工作台可以正常使用，但是直接添加网页后点击插件异常，无法直接网页问答。

服务部署后可以进入工作台，能够进行正常chat：
![image](https://github.com/QwenLM/Qwen-Agent/assets/10300313/9fa96a4b-83bc-4bf5-8f6b-03e8a0ed33a1)
但是效仿[官方demo视频](https://qianwen-res.oss-cn-beijing.aliyuncs.com/assets/qwen_agent/showcase_write_article_based_on_webpages_and_pdfs.mp4)的操作失败，即在添加网页到Reading List之后，点击插件出现的界面无法聊天，具体界面如下：

![image](https://github.com/QwenLM/Qwen-Agent/assets/10300313/febc61e8-3e41-4799-a92d-2d6cfb2b8eb8)

**Comment by MrRace** [comment]
@JianxinMa 求助

**Comment by tuhahaha** [comment]
看起来是交互页面的服务没起成功，你是在本地部署的服务吗？如果服务部署在本地，那请粘贴后台输出到这里我看看报什么错；如果服务部署在远程，那需要在Customize Address那里输入你的ip地址

**Comment by ye7love7** [comment]
遇到了相同的问题，服务部署在远程服务器上，输入远程服务器的地址http://192.168.9.9:7864或者7863，均不起作用。

**Comment by tcexeexe** [comment]
+1我也遇到了这个问题

**Comment by ye7love7** [comment]
> +1我也遇到了这个问题

这个问题新版本已经解决了，我已经没有碰到这个问题了，你可以尝试更新代码。
