### ISSUE TITLE
agent 测试 ollama本地 502  API 测试 成功不知道怎么原因

### ISSUE THREAD

**Issue by FANBOCHENG** [QwenLM/Qwen-Agent#410]
![image](https://github.com/user-attachments/assets/cce025fc-72f3-43f8-b67a-2404ce274718)
![image](https://github.com/user-attachments/assets/32bab3e4-7adf-4fde-9a24-8c85ec165a65)

**Comment by FANBOCHENG** [comment]
有时候成功有失败 完全找不到原因

**Comment by tuhahaha** [comment]
失败的query和成功的query一样吗？是不是api接口不稳定？换dashscope接口正常吗？

**Comment by FANBOCHENG** [comment]
> 失败的query和成功的query一样吗？是不是api接口不稳定？换dashscope接口正常吗？

已解决 是代理的问题 本地开启了翻墙 关闭之后就好了
