### ISSUE TITLE
agent重新初始化仍会受到之前聊天的影响

### ISSUE THREAD

**Issue by LouieBHLu** [QwenLM/Qwen-Agent#411]
请问一下，我想通过Assistant重新初始化来使两次对话完全独立，但是现在发现agent重新初始化仍会受到之前聊天的影响。请问有什么类似于reset之类的接口可以确保在不结束后端应用的前提下，可以让Assistant完全初始化的吗？样例代码如下：
``` python

answer = ask(question)

def ask(question):
......
agent = Assistant(
        llm=llm_cfg,
        name="humanize_agent",
    )
......
```

**Comment by tuhahaha** [comment]
Assistant对话的历史完全取决于输入的messages，它自己不会存储任何历史对话信息。所以只要保证在应用侧输入的messages参数是新的就行。
