### ISSUE TITLE
多agent中，description和instructions的作用分别是什么？起强调或专注作用的prompt写在哪里？还是system里？

### ISSUE THREAD

**Issue by DAAworld** [QwenLM/Qwen-Agent#413]
低参数模型比如32b的模型，我目前把强调或专注作用的prompt写了如上的3个地方。高参数的模型理解能力还不错。
比较好奇description和instructions的区别是什么？

**Comment by tuhahaha** [comment]
instructions: 会放在agent的system里，指导当前agent的行为。我理解你说的‘强调或专注作用’，就是这个。
description：可以理解成agent的身份信息，被用于groupchat的调度
