### ISSUE TITLE
网页问答错误

### ISSUE THREAD

**Issue by yumingfan-0219** [QwenLM/Qwen-Agent#44]
请问出现如上图的问题可能是什么原因

**Comment by tuhahaha** [comment]
没粘贴上图片？

**Comment by yumingfan-0219** [comment]
![f36dd934a69cbd0f8db0de681cc01d93](https://github.com/QwenLM/Qwen-Agent/assets/84659130/0b713a7d-8a4c-441e-a09e-8ce7b4ac935f)

**Comment by yumingfan-0219** [comment]
似乎浏览器抽风了，图片没传上去，抱歉

**Comment by yumingfan-0219** [comment]
可能的原因：
RuntimeError: Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
'FieldInfo' object has no attribute 'required'
https://github.com/microsoft/DeepSpeed/issues/3963
降级pydantic版本解决该问题

我先前遇到上述bug，降级了pydantic，似乎和gradio4.0.2不兼容


是否有办法可以在不降级pydantic的前提下解决该问题？

**Comment by tuhahaha** [comment]
我本地gradio版本3.41.1， pydantic版本2.4.2，也许你可以重新安装一个gradio版本

**Comment by yumingfan-0219** [comment]
![d63f0ed3680f36d88cfc48d5c21fbec1](https://github.com/QwenLM/Qwen-Agent/assets/84659130/a6705cae-fb09-4744-abf4-e603724d10e6)
界面变成了这样的情况，不知道您是否遇到过

**Comment by tuhahaha** [comment]
我没有遇到过，看起来像是网络问题诶

**Comment by tuhahaha** [comment]
你是在本地开启的服务吗？还是远程呢？
