### ISSUE TITLE
如何自己添加工具？

### ISSUE THREAD

**Issue by qiezikuangge** [QwenLM/Qwen-Agent#5]
有工具模板吗，可以自己添加工具

**Comment by tuhahaha** [comment]
有，这里是添加工具的模版https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/agents/tools/tools.py，对应工具也可以实现在这个目录下，然后将你的tool入口加到call_plugin函数，之后就可以调用了

**Comment by JianxinMa** [comment]
> 有，这里是添加工具的模版 [tools.py](https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/agents/tools/tools.py)，对应工具也可以实现在这个目录下，然后将你的tool入口加到call_plugin函数，之后就可以调用了

@tuhahaha 我们需要先把代码架构稳定下来，然后写个step-by-step的文档说明下如何加新工具。

**Comment by gcxamy** [comment]
您好，我看您说那个开源数据集的写法在https://github.com/QwenLM/Qwen/blob/main/examples/function_call_finetune_examples.py请问是用这个文件生成对应的调用工具开源数据集，然后用您说的在tool里加入自己的类的call调用，再训练就可以了吗？有对应的每个步骤吗？

**Comment by JianxinMa** [comment]
> 您好，我看您说那个开源数据集的写法在[https://github.com/QwenLM/Qwen/blob/main/examples/function_call_finetune_examples.py请问是用这个文件生成对应的调用工具开源数据集，然后用您说的在tool里加入自己的类的call调用，再训练就可以了吗？有对应的每个步骤吗？](https://github.com/QwenLM/Qwen/blob/main/examples/function_call_finetune_examples.py%E8%AF%B7%E9%97%AE%E6%98%AF%E7%94%A8%E8%BF%99%E4%B8%AA%E6%96%87%E4%BB%B6%E7%94%9F%E6%88%90%E5%AF%B9%E5%BA%94%E7%9A%84%E8%B0%83%E7%94%A8%E5%B7%A5%E5%85%B7%E5%BC%80%E6%BA%90%E6%95%B0%E6%8D%AE%E9%9B%86%EF%BC%8C%E7%84%B6%E5%90%8E%E7%94%A8%E6%82%A8%E8%AF%B4%E7%9A%84%E5%9C%A8tool%E9%87%8C%E5%8A%A0%E5%85%A5%E8%87%AA%E5%B7%B1%E7%9A%84%E7%B1%BB%E7%9A%84call%E8%B0%83%E7%94%A8%EF%BC%8C%E5%86%8D%E8%AE%AD%E7%BB%83%E5%B0%B1%E5%8F%AF%E4%BB%A5%E4%BA%86%E5%90%97%EF%BC%9F%E6%9C%89%E5%AF%B9%E5%BA%94%E7%9A%84%E6%AF%8F%E4%B8%AA%E6%AD%A5%E9%AA%A4%E5%90%97%EF%BC%9F)

您贴的这个链接是和“微调”相关的。但是只是想让模型使用自定义新工具的话，通常不需要微调，只需要提供下工具的描述和输入参数描述（描述是否清楚非常重要，这个描述会作为输入给模型的prompt的一部分，相当于是在做prompt engineering）。如果你在使用qwen-max，可以参考本repo的readme添加自定义工具（后续开源的新模型版本也将支持）；如果是在使用之前开源的模型，可以参考Qwen主仓库的 openai_api.py 或 examples 下的 function_call_examples.py
