### ISSUE TITLE
请支持chatGLM3通用的openai接口，谢谢

### ISSUE THREAD

**Issue by coderwpf** [QwenLM/Qwen-Agent#54]
请支持chatGLM3通用的openai接口，谢谢

**Comment by JianxinMa** [comment]
欢迎提PR，我们会merge的。本职工作负担重，开源项目靠爱发电，很难面面俱到。。

**Comment by yumingfan-0219** [comment]
同类问题，借楼提问
请问类似baichuan这样的模型是不是暂时也还无法支持？

**Comment by xunyuw** [comment]
chatGLM3和baichuan这样的模型没经过agent对其，支持了效果也不行，这个项目是从langchain改的吧，langchain主分支上有支持，你们可以测试了看看效果去
