### ISSUE TITLE
windows使用Browser Assistant出错

### ISSUE THREAD

**Issue by XuHao777** [QwenLM/Qwen-Agent#58]
您好，我启动了QWEN的服务，按照要求配置了环境，下面为问题截图，我重新安装了openai的0.28.1版本，但是还是有问题，请帮忙看一下，谢谢！
![微信图片_20231121165853](https://github.com/QwenLM/Qwen-Agent/assets/40559193/17428c25-670f-4409-9efe-26677135b883)
![2](https://github.com/QwenLM/Qwen-Agent/assets/40559193/06a3dbd6-0b25-434c-975d-e0c1515e7fab)
![3](https://github.com/QwenLM/Qwen-Agent/assets/40559193/ca02258c-4911-4473-a746-d97053dfa617)

**Comment by SolarKnight1** [comment]
+1,我也是这样

**Comment by tuhahaha** [comment]
看起来是qwen没部署成功，可以贴一下qwen服务那边的后台输出吗？

**Comment by JianxinMa** [comment]
oai的pip提示不太优化，它说 `pip install openai==0.28`，但其实应该 `pip install "openai==0.28"`

**Comment by XuHao777** [comment]
> 看起来是qwen没部署成功，可以贴一下qwen服务那边的后台输出吗？

你好，我现在部署没问题了。我的服务是部署在远程服务器上，想在本地windows浏览器上使用浏览器助手，远程服务启动时server_host='0.0.0.0'，fast_api_port=7866, app_in_browser_port=19005, workstation_port=7864，其中19005为服务器开放端口。我在本地浏览器输入服务器ip:19005打开了一个很奇怪的界面，如图一所示。而且在不同的网页端点击“add to qwen reading list”时，远程服务器上显示的access page一直是同一个地址。并且我在弹出的“自定义网址”中也输入了服务器ip，但是没反应，这是怎么回事呢
ps：我将workstation_port设置为19005，就可以在浏览器正常使用工作站
![1](https://github.com/QwenLM/Qwen-Agent/assets/40559193/fc5707c4-73c8-4283-abc9-b9ec3bfa46ab)
![2](https://github.com/QwenLM/Qwen-Agent/assets/40559193/e14e599c-af62-4710-b944-16630c4035aa)
![3](https://github.com/QwenLM/Qwen-Agent/assets/40559193/1941af71-ecbe-4ffc-a523-36d4291afe5c)

**Comment by tuhahaha** [comment]
这是因为目前的代码没有直接支持修改端口，你可以保持app_in_browser_port运行在7863端口，也可以把这个文件里的7863替换成19005。如果是后者，需要刷新浏览器扩展程序。

**Comment by XuHao777** [comment]
> 这是因为目前的代码没有直接支持修改端口，你可以保持app_in_browser_port运行在7863端口，也可以把[这个文件](https://github.com/QwenLM/Qwen-Agent/blob/main/browser_qwen/src/popup.js)里的7863替换成19005。如果是后者，需要刷新浏览器扩展程序。

首先感谢您的及时回复。
我将browser_qwen/src/popup.js里的7863替换成19005，如下图所示。
![5](https://github.com/QwenLM/Qwen-Agent/assets/40559193/6bd86f8e-db62-40d2-8310-526d420577fa)
然后重新加载了扩展程序，但是打开还是有问题，请问还需要更改其他地方吗
![6](https://github.com/QwenLM/Qwen-Agent/assets/40559193/eca03eaa-263c-4583-acc3-e40c6ee1cfa2)
下面是我打印出的参数配置：
023-11-23 16:04:53,998 - run_server.py - 90 - INFO - path=PathConfig(work_space_root='workspace/', cache_root='workspace/browser_cache/', download_root='workspace/download/', code_interpreter_ws='workspace/ci_workspace/') server=ServerConfig(server_host='0.0.0.0', fast_api_port=7866, app_in_browser_port=19005, workstation_port=7864, model_server='http://10.158.231.66:10007/v1', api_key='', llm='Qwen-14B-Chat', max_ref_token=4000, max_days=7)

**Comment by XuHao777** [comment]
> 这是因为目前的代码没有直接支持修改端口，你可以保持app_in_browser_port运行在7863端口，也可以把[这个文件](https://github.com/QwenLM/Qwen-Agent/blob/main/browser_qwen/src/popup.js)里的7863替换成19005。如果是后者，需要刷新浏览器扩展程序。


另外，我使用工作台加载整篇PDF时，给定prompt时发现有两个问题：
1、无法参考整篇文档的内容给回答，我打印了prompt，发现"text: "中只有文档的一小部分；
2、回答的答案很乱。

下图为回答截图：
![2](https://github.com/QwenLM/Qwen-Agent/assets/40559193/2ff114bd-8b8d-4b0f-a8ac-cb06479b1d9c)

**Comment by tuhahaha** [comment]
1. 需要填写你远程服务器的ip地址；2. 我这边排查下是否是最近更新引入了bug

**Comment by XuHao777** [comment]
> 1. 需要填写你远程服务器的ip地址；2. 我这边排查下是否是最近更新引入了bug

1.填写服务器ip地址仍然无效，且点击“added to the Qwen's reading list”在程序服务中没有任何反应（表示没有增加该网页）；
2.max_ref_token不宜太大，我现在限制为2000，另外在qwen_agent/actions/base.py中的_call_llm函数中增加了stop，问题2已经得到解决；

老师，对于问题1还有什么建议嘛

**Comment by tuhahaha** [comment]
正常是填写ip地址以后，再次打开popup页面会刷新出对话框。你可以检查网页后台输出，查看是否配置正确ip。另外，点击“added to the Qwen's reading list”点击成功后会在弹出框确认是否添加，点击时候不要拖动按钮。
<img width="560" alt="image" src="https://github.com/QwenLM/Qwen-Agent/assets/37433392/0fa3096d-dc3e-41ab-8af7-ed90f8ad6fc4">

**Comment by XuHao777** [comment]
> 正常是填写ip地址以后，再次打开popup页面会刷新出对话框。你可以检查网页后台输出，查看是否配置正确ip。另外，点击“added to the Qwen's reading list”点击成功后会在弹出框确认是否添加，点击时候不要拖动按钮。 <img alt="image" width="560" src="https://private-user-images.githubusercontent.com/37433392/285372060-0fa3096d-dc3e-41ab-8af7-ed90f8ad6fc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNTYzMTUsIm5iZiI6MTcwMTE1NjAxNSwicGF0aCI6Ii8zNzQzMzM5Mi8yODUzNzIwNjAtMGZhMzA5NmQtZGMzZS00MWFiLThhZjctZWQ5MGY4YWQ2ZmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA3MjAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NWIzYjVkNTUwZTQ0YzIwYzQzZWExZjhlZTM3MWRjZTUwMzM4OTYzMjg1MDNjNzQzNGE3NTdhZTE0ZDhlYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WrGbt-j7AsckIWEePGNVDyPSVpYxJccdhNdPEsfczPg">

解决了，谢谢！
