### ISSUE TITLE
启动run_server成功，但是无法问答

### ISSUE THREAD

**Issue by SolarKnight1** [QwenLM/Qwen-Agent#59]
问题复现步骤：1.python openai_api.py --server-name 0.0.0.0 --server-port 7905 -c /home/wyxx/warBackup/ner/qwen/model/
2.python run_server.py --model_server http://{MODEL_SERVER_IP}:7905/v1 --workstation_port 7864  -s 0.0.0.0，成功启动，在成功上传文件之后，输入问题
3.报错openai.lib._old_api.APIRemovedInV1:
You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.
You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface.
Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`
4.pip install openai==0.28
5.报错requests.exceptions.ConnectionError: HTTPConnectionPool(host='%7bmodel_server_ip%7d', port=7905): Max retries exceeded with url: /v1/chat/completions (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f75df9ea380>: Failed to resolve '%7bmodel_server_ip%7d' ([Errno -2] Name or service notknown)"))

**Comment by tuhahaha** [comment]
python run_server.py --model_server http://{MODEL_SERVER_IP}:7905/v1 --workstation_port 7864 -s 0.0.0.0需要将{MODEL_SERVER_IP}替换成你真正的ip地址

**Comment by JianxinMa** [comment]
oai的pip提示不太友好，它说 `pip install openai==0.28`，但其实应该 `pip install "openai==0.28"`，否则openai版本实际不会降级。

**Comment by SolarKnight1** [comment]
> oai的pip提示不太友好，它说 `pip install openai==0.28`，但其实应该 `pip install "openai==0.28"`，否则openai版本实际不会降级。

我已经确认了版本，也改了IP之后启动，发现会卡在 ========================= 
> Use Default plans: 
{"action1": "summarize", "action2": "outline", "action3": "expand"}
========================= 
> Summarize Browse Content: 

然后过个一会就回报错openai.error.APIConnectionError: Error communicating with OpenAI: HTTPConnectionPool(host='116.62.199.56', port=7905): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6241639520>: Failed to establish a new connection: [Errno 110] Connection timed out'))，这是怎么回事呢，还请大佬指点啊

**Comment by tuhahaha** [comment]
你的qwen服务那边的报错是什么？是不是oom了？ @SolarKnight1

**Comment by SolarKnight1** [comment]
> 你的qwen服务那边的报错是什么？是不是oom了？ @SolarKnight1

openai.py没报错。。。
也没oom。。。

**Comment by SolarKnight1** [comment]
> 你的qwen服务那边的报错是什么？是不是oom了？ @SolarKnight1
