### ISSUE TITLE
请问可以增加阿里平台调用API吗

### ISSUE THREAD

**Issue by xs818818** [QwenLM/Qwen-Agent#6]
这样可以先测试体验效果

**Comment by JianxinMa** [comment]
正在开发中~

**Comment by JianxinMa** [comment]
已增加对 [阿里云dashscope](https://help.aliyun.com/zh/dashscope/developer-reference/model-square/) 的支持，使用 dashscope 部署的 qwen 模型服务，可省去自己部署模型的步骤。详见 readme。

使用过程中有任何问题，欢迎提 issue 反馈。

**Comment by liaoweiguo** [comment]
ubuntu上agent挺好，Mac上不行
