### ISSUE TITLE
请教大佬，在调用工具的时候，如何实现多轮对话呢

### ISSUE THREAD

**Issue by SolarKnight1** [QwenLM/Qwen-Agent#63]

**Comment by JianxinMa** [comment]
如果问的是“实现”，而不是“用法”，那可以参考 Qwen 项目下的 openai_ap.py https://github.com/QwenLM/Qwen/blob/main/openai_api.py#L139 （内部将 ReAct 封装成了 function calling），或者参考 https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/actions/react.py#L70 （和 openai_api.py 的实现有一些差异）

**Comment by SolarKnight1** [comment]
> 如果问的是“实现”，而不是“用法”，那可以参考 Qwen 项目下的 openai_ap.py https://github.com/QwenLM/Qwen/blob/main/openai_api.py#L139 （内部将 ReAct 封装成了 function calling），或者参考 https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/actions/react.py#L70 （和 openai_api.py 的实现有一些差异）

那请问用法又是如何呢

**Comment by JianxinMa** [comment]
建议使用 Qwen 项目下 openai_api.py 起一个模型服务，可以用和调用 chatgpt 一样的方法使用 qwen，见 Qwen 项目 README 关于 openai_api 的内容（需注意 `pip install "openai<1.0.0"`因为openai新版本更改了协议）。

工具调用这块，就按 function calling 接口的用法使用，建议先搜索相关教程学习下 function calling 的用法。我们也提供了一个（可能写得不太清楚的）示例在 https://github.com/QwenLM/Qwen/blob/main/examples/function_call_examples.py

Qwen-Agent下虽然也有使用 function calling 的例子，但是代码写得很丑不易读，我们有空了会改进下。

使用过程中遇到问题，可以提issue或翻看Qwen项目的往期issues。
