### ISSUE TITLE
建议修复一个README说明错误

### ISSUE THREAD

**Issue by alexjuchina** [QwenLM/Qwen-Agent#64]
一个小建议：

- 文件：README_CN.md
- 位置：
![image](https://github.com/QwenLM/Qwen-Agent/assets/18329894/8281380c-8df5-46ee-a9a5-ba7c79c523fe)

- 原因：按照文档里面的写法，运行这条命令的时候会再次尝试下载大模型，我滴乖乖。我刚刚部署+测试都没问题，为啥运行个api程序，就要再下载一遍？仔细看了下，是原文文档里面`QWen/QWen-14B-Chat`中的`W`大写了，改成小写就好了。
- 建议：要么W改为小写，要么在源代码里面不要区分这个参数的大小写。

**Comment by JianxinMa** [comment]
感谢反馈~ 已修改。
