### ISSUE TITLE
Upload failed: only adding ['.pdf', '.docx', '.pptx'] documents as references is supported!

### ISSUE THREAD

**Issue by ye7love7** [QwenLM/Qwen-Agent#68]
更新版本后，对csv和xlsx等文件格式不支持上传了吗？

**Comment by tuhahaha** [comment]
你好，你应该是在左下角选择了Document QA选项上传的文件，这里和以前一样仅支持上传['.pdf', '.docx', '.pptx']类型到知识库。如果需要上传csv和xlsx等文件进行数据分析，请在左下角选择Code Interpreter选项。 @ye7love7

**Comment by ye7love7** [comment]
> 你好，你应该是在左下角选择了Document QA选项上传的文件，这里和以前一样仅支持上传['.pdf', '.docx', '.pptx']类型到知识库。如果需要上传csv和xlsx等文件进行数据分析，请在左下角选择Code Interpreter选项。 @ye7love7

谢谢大佬，请问如何删除浏览记录？我看到只有绿色的√按钮，能否直接删除？

**Comment by tuhahaha** [comment]
是的，取消那个勾选狂就可以把对应记录从知识库中排除，如果需要加回来，再选上即可

**Comment by ye7love7** [comment]
> 是的，取消那个勾选狂就可以把对应记录从知识库中排除，如果需要加回来，再选上即可

请问每条记录后面增加一个x，让用户点击完全删除，是否有可能？

**Comment by ye7love7** [comment]
> 是的，取消那个勾选狂就可以把对应记录从知识库中排除，如果需要加回来，再选上即可

求教大佬，不知如何联系你，我提了一个issue，是关于max_ref_token没有作用于similar的问题，同时，manul参数是否可调？几乎全部都是相似的，导致前两页充满了窗口，叩谢！
