### ISSUE TITLE
remaining slots机制

### ISSUE THREAD

**Issue by ye7love7** [QwenLM/Qwen-Agent#71]
版本：2024/1/22最新
使用chat上传两篇pdf到历史，长度分别为13859和20905，使用editor开始写作后，后台信息如图：
![2024-01-22_144632](https://github.com/QwenLM/Qwen-Agent/assets/72247118/8664134a-74de-49f7-97da-dea9c5b40b40)
remaining slots: 2000，始终未变，测试继续放入一篇小的，发现remaining slots变化了，对同一份pdf不同反应，如下图：
![2024-01-22_145511](https://github.com/QwenLM/Qwen-Agent/assets/72247118/d815c970-69c6-46a2-b1b1-853ad451c989)
查看源代码后，仍然不明白，jieba分词后都是词语，如何重新组成一段话，manul参数=2，是否可以调？谢谢大佬！
注：server_config.json使用默认，内容如下：
{
    "path": {
        "work_space_root": "workspace/",
        "database_root": "workspace/database/",
        "download_root": "workspace/download/",
        "code_interpreter_ws": "workspace/ci_workspace/"
    },
    "server": {
        "server_host": "0.0.0.0",
        "fast_api_port": 7866,
        "app_in_browser_port": 7863,
        "workstation_port": 7864,
        "model_server": "http://127.0.0.1:8000/v1",
        "api_key": "EMPTY",
        "llm": "Qwen-7B-Chat",
        "max_ref_token": 4000,
        "max_days": 7,
        "functions": [
            "code_interpreter",
            "image_gen"
        ]
    }
}

**Comment by ye7love7** [comment]
使用新版本，还是这样，2000

**Comment by tuhahaha** [comment]
你好，这应该是manul设置的问题，我这边看下怎么调整

**Comment by ye7love7** [comment]
请问大佬，max_ref没有作用于memory，是因为没有传入参数吗？
jac算法是交集除以并集，我觉得是不是可以加入rag的项目？



---原始邮件---
发件人: "Jianhong ***@***.***&gt;
发送时间: 2024年1月25日(周四) 中午12:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [QwenLM/Qwen-Agent] remaining slots机制 (Issue #71)




 
你好，这应该是manul设置的问题，我这边看下怎么调整

**Comment by tuhahaha** [comment]
max_ref是要作用于memory的，传参了，应该是被manual的规则给弄失效了，我一会儿看下。rag策略我们也在看，也欢迎提PR！

**Comment by ye7love7** [comment]
T_T 还没有能力提rag的pr，可以资金支持，我们有个私有化项目需要这样的框架



---原始邮件---
发件人: "Jianhong ***@***.***&gt;
发送时间: 2024年1月25日(周四) 中午12:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [QwenLM/Qwen-Agent] remaining slots机制 (Issue #71)




 
max_ref是要作用于memory的，传参了，应该是被manual的规则给弄失效了，我一会儿看下。rag策略我们也在看，也欢迎提PR！

**Comment by ye7love7** [comment]
大佬，传递参数时，workstation的bot用了max_ref_token，memory是max_token，接收不到，用了默认的4000，这个问题应该解决了，但是remaining slots的机制不知道怎么解决。

---原始邮件---
发件人: "Jianhong ***@***.***&gt;
发送时间: 2024年1月25日(周四) 中午12:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [QwenLM/Qwen-Agent] remaining slots机制 (Issue #71)




 
max_ref是要作用于memory的，传参了，应该是被manual的规则给弄失效了，我一会儿看下。rag策略我们也在看，也欢迎提PR！

**Comment by tuhahaha** [comment]
你好，我修复了这个哈，暂时关掉了minor，仅通过相似性来查找，这只是一个基础方案，我们这边也在探索更佳的RAG策略
