### ISSUE TITLE
请问下有没有相关微信群

### ISSUE THREAD

**Issue by lichtud** [QwenLM/Qwen-Agent#74]
请问下有没有相关微信群可以请教交流

**Comment by JianxinMa** [comment]
在Qwen微信群交流就好。不过阿里员工看微信不方便，微信不一定能比github issue响应快。

**Comment by lichtud** [comment]
> 在Qwen微信群交流就好。不过阿里员工看微信不方便，微信不一定能比github issue响应快。

好的，谢谢。感觉你们用钉钉可能多一点
