### ISSUE TITLE
AttributeError: 'Qwen2ForCausalLM' object has no attribute 'chat_stream'

### ISSUE THREAD

**Issue by ruifengma** [QwenLM/Qwen-Agent#78]
用openai_api.py部署Qwen1.5-72B-Chat版本，Qwen-agent调用报错

**Comment by JianxinMa** [comment]
openai_api.py 目前只支持 qwen1，还没适配 qwen1.5。qwen1.5 我们目前建议参考 https://github.com/QwenLM/Qwen1.5?tab=readme-ov-file#deployment 部署 vllm 来获得 openai 兼容的接口。如果 vllm 部署遇到问题，可以提相关 issues，我们会争取尽量简化流程。

vllm更适合部署在服务器上，应对高吞吐的情况。如果您只是个人电脑本地使用，也可以考虑 ollama，它似乎也提供了 openai 兼容的接口，参见 https://ollama.com/blog/openai-compatibility

**Comment by xrenaissance** [comment]
> openai_api.py 目前只支持 qwen1，还没适配 qwen1.5。qwen1.5 我们目前建议参考 https://github.com/QwenLM/Qwen1.5?tab=readme-ov-file#deployment 部署 vllm 来获得 openai 兼容的接口。如果 vllm 部署遇到问题，可以提相关 issues，我们会争取尽量简化流程。
> 
> vllm更适合部署在服务器上，应对高吞吐的情况。如果您只是个人电脑本地使用，也可以考虑 ollama，它似乎也提供了 openai 兼容的接口，参见 https://ollama.com/blog/openai-compatibility

![04ee9fd4-a070-4375-ab3a-084c78b34c03](https://github.com/QwenLM/Qwen-Agent/assets/8351204/040846b4-a798-4302-be39-9b66b720445d)
我用的vllm 0.3 deploy的openai的api server，也是不支持，我用的是qwen1.5-14b-chat

**Comment by JianxinMa** [comment]
> > openai_api.py 目前只支持 qwen1，还没适配 qwen1.5。qwen1.5 我们目前建议参考 https://github.com/QwenLM/Qwen1.5?tab=readme-ov-file#deployment 部署 vllm 来获得 openai 兼容的接口。如果 vllm 部署遇到问题，可以提相关 issues，我们会争取尽量简化流程。
> > vllm更适合部署在服务器上，应对高吞吐的情况。如果您只是个人电脑本地使用，也可以考虑 ollama，它似乎也提供了 openai 兼容的接口，参见 https://ollama.com/blog/openai-compatibility
> 
> ![04ee9fd4-a070-4375-ab3a-084c78b34c03](https://private-user-images.githubusercontent.com/8351204/307676716-040846b4-a798-4302-be39-9b66b720445d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NDkxODksIm5iZiI6MTcwODk0ODg4OSwicGF0aCI6Ii84MzUxMjA0LzMwNzY3NjcxNi0wNDA4NDZiNC1hNzk4LTQzMDItYmUzOS05YjY2YjcyMDQ0NWQuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDEyMDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxYzg3MTk4N2Q3OGRhZDFhN2ZhNjQwYzdkNTAxNzcwMzA3NDg5YzY5NWZlZmJkYjlkOWY0NDdmMTIyMTgyMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BN4vC2j6_zmHzq8SG-wOyMRofDRP4F6QI5jZMaFcKFc) 我用的vllm 0.3 deploy的openai的api server，也是不支持，我用的是qwen1.5-14b-chat

看起来是vllm的服务报错了，然后qwen-agent的error handling没做好，没把vllm服务的错误报出来。我们研究下。

**Comment by JianxinMa** [comment]
> > openai_api.py 目前只支持 qwen1，还没适配 qwen1.5。qwen1.5 我们目前建议参考 https://github.com/QwenLM/Qwen1.5?tab=readme-ov-file#deployment 部署 vllm 来获得 openai 兼容的接口。如果 vllm 部署遇到问题，可以提相关 issues，我们会争取尽量简化流程。
> > vllm更适合部署在服务器上，应对高吞吐的情况。如果您只是个人电脑本地使用，也可以考虑 ollama，它似乎也提供了 openai 兼容的接口，参见 https://ollama.com/blog/openai-compatibility
> 
> ![04ee9fd4-a070-4375-ab3a-084c78b34c03](https://private-user-images.githubusercontent.com/8351204/307676716-040846b4-a798-4302-be39-9b66b720445d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMDgzODYsIm5iZiI6MTcwOTIwODA4NiwicGF0aCI6Ii84MzUxMjA0LzMwNzY3NjcxNi0wNDA4NDZiNC1hNzk4LTQzMDItYmUzOS05YjY2YjcyMDQ0NWQuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDEyMDEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNzg3MDUxZGFhMjAzMWM0MzRhOWNiZmRkYWNjNzJiZDc2YzdjOTIzODBkMGU1ZjMwNjczNTgxM2IxYmMzNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t6enzBnMCzIex34hqAgwXhpaHluaXnzk3Vp9hyUee50) 我用的vllm 0.3 deploy的openai的api server，也是不支持，我用的是qwen1.5-14b-chat

您好，经过排查，是部分oai api实现会输出 content=None 导致，我们已经更新了相关代码处理这个情况。可以拉取最新代码再次尝试下。
