### ISSUE TITLE
上传xls文件，使用代码解释器，提问报错，无法读取文件

### ISSUE THREAD

**Issue by ye7love7** [QwenLM/Qwen-Agent#81]
![image](https://github.com/QwenLM/Qwen-Agent/assets/72247118/9edd933b-8e18-4046-8367-fda02aae711f)

![image](https://github.com/QwenLM/Qwen-Agent/assets/72247118/fd7894d9-7978-469f-80b9-d46fa12350d3)

我上传的xls文件，也是一样的报错，现在表格是被上传到/tmp/gradio/下面了，但是还是读不到，是什么原因？

_Originally posted by @ye7love7 in https://github.com/QwenLM/Qwen-Agent/issues/57#issuecomment-1958814902_

**Comment by tuhahaha** [comment]
你好，请问是拉取的最新的代码吗？我刚测了下可以读到文件

**Comment by ye7love7** [comment]
我是早上拉取的代码，我测试一下，没问题我就close



---原始邮件---
发件人: "Jianxin ***@***.***&gt;
发送时间: 2024年2月22日(周四) 下午3:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [QwenLM/Qwen-Agent] 上传xls文件，使用代码解释器，提问报错，无法读取文件 (Issue #81)




 
请问有拉取最新代码尝试吗？中午的时候在合并了您的PR后，我们发现了这个bug，也修了。
