### ISSUE TITLE
每次更新就会有新的bug出现

### ISSUE THREAD

**Issue by xrenaissance** [QwenLM/Qwen-Agent#84]
只是一个提议，每次有新的更新，就会有更多的bug，感觉刚发布的时候最起码可以用，现在基本上跑不起来，
项目本身蛮好的，开源也不容易，就是bug有点多

**Comment by 1ChachA** [comment]
我已经遇到了

**Comment by JianxinMa** [comment]
> 我已经遇到了

辛苦开个issue报下具体遇到的bug。。
