### ISSUE TITLE
[FR] 支持 LM studio

### ISSUE THREAD

**Issue by wwjCMP** [QwenLM/Qwen-Agent#86]
LM studio 对 Qwen1.5支持得很好，希望BrowserQwen可以支持直接调用它的代理

**Comment by JianxinMa** [comment]
lm studio 提供了 openai api 兼容接口（见文档 https://lmstudio.ai/docs/local-server ），可以通过 openai api 的方式接入 lm studio。

类似的，和lm studio定位类似的ollama也可以通过openai api方式接入，见 https://github.com/QwenLM/Qwen-Agent/issues/94#issuecomment-1983410169
