### ISSUE TITLE
使用open ai格式接口问题

### ISSUE THREAD

**Issue by goupaishalujiqi** [QwenLM/Qwen-Agent#87]
使用open ai格式api连接不上 总是error 不是connection error 就是 ValueError: can only concatenate str (not "NoneType") to str

**Comment by JianxinMa** [comment]
我们自测 together ai 提供的 api 能通。请问具体使用的是什么代码或框架提供的open ai格式api，是 vllm、fastchat、或者其他？我们排查下

**Comment by JianxinMa** [comment]
您好，经过排查，是部分oai api实现会输出 content=None 导致，我们已经更新了相关代码处理这个情况。可以拉取最新代码再次尝试下。
