### ISSUE TITLE
ReAct模式下，如何自行实现方法`_chat_no_stream`

### ISSUE THREAD

**Issue by lyj555** [QwenLM/Qwen-Agent#92]
目的：想运行ReAct，与本机的大模型的交互（未生成模型服务）；

看了一下代码，核心需要实现方法`_chat_no_stream`或者`_chat_stream`，想问下，是否可参考下列方式（上一版本大模型ReAct的推理）实现即可？

```
    def text_completion(model, tokenizer, input_text: str, stop_words) -> str:
        im_end = '<|im_end|>'
        if im_end not in stop_words:
            stop_words = stop_words + [im_end]
        stop_words_ids = [tokenizer.encode(w) for w in stop_words]

        # TODO: 增加流式输出的样例实现
        input_ids = torch.tensor([tokenizer.encode(input_text)]).to(model.device)
        output = model.generate(input_ids, stop_words_ids=stop_words_ids)
        output = output.tolist()[0]
        output = tokenizer.decode(output, errors="ignore")
        assert output.startswith(input_text)
        output = output[len(input_text):].replace('<|endoftext|>', '').replace(im_end, '')

        for stop_str in stop_words:
            idx = output.find(stop_str)
            if idx != -1:
                output = output[: idx + len(stop_str)]
        # 续写 input_text 的结果，不包含 input_text 的内容
        # print("input_text:")
        # print(input_text)
        #
        # print("output:")
        # print(output)
        return output
```

**Comment by JianxinMa** [comment]
有两种方式：
- 方式一（推荐）：本地大模型服务提供一个openai兼容接口，这样就不需要改代码即可使用。ollama、vllm都能提供这个接口。
- 方式二（工作量较大）：像 https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/llm/oai.py 这样实现一个新的llm class，并且如您所说，可以用 model.generate 实现 _chat_stream。您截图的是非流式的generate，要流式的generate可能需要参考 https://huggingface.co/Qwen/Qwen-72B-Chat/blob/main/modeling_qwen.py#L1163 或其他参考实现。

**Comment by lyj555** [comment]
> 有两种方式：
> 
> * 方式一（推荐）：本地大模型服务提供一个openai兼容接口，这样就不需要改代码即可使用。ollama、vllm都能提供这个接口。
> * 方式二（工作量较大）：像 https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/llm/oai.py 这样实现一个新的llm class，并且如您所说，可以用 model.generate 实现 _chat_stream。您截图的是非流式的generate，要流式的generate可能需要参考 https://huggingface.co/Qwen/Qwen-72B-Chat/blob/main/modeling_qwen.py#L1163 或其他参考实现。

嗯嗯，明白啦，多谢，多谢。
