### ISSUE TITLE
您好，请问如果函数不需要入参的时候函数的格式怎么写比较好？

### ISSUE THREAD

**Issue by tzyodear** [QwenLM/Qwen-Agent#93]
试过在description里加上  “不需要输入参数” 的说明，或者
        "parameters": {
            'type': 'object',
            'properties': {}
        }
又或者
        "parameters": {}

但是经常模型还是会生成不存在的参数。
不知道您之前遇到过这种情况没有？
谢谢

**Comment by JianxinMa** [comment]
我拿 examples/function_calling.py 那个脚本简单试了下，改成类似这样：

```py
    functions = [{
        'name': 'get_current_weather',
        'description': 'Get the current weather in SF',
        'parameters': '输入参数为 {} 即可',
    }]
```

似乎是可行的。如果不行，可以提供下使用的是哪个模型版本、更完整的工具描述和用户问题，我们看下。

**Comment by tzyodear** [comment]
感谢百忙之中抽空回答，我又试了一下上面那种，还是可能额外生成一些不需要的参数。甚至包括规定好的参数也会。

不过这个倒不是啥大问题，因为在这种情况下只要能正确生成函数名/需要的参数就行了，这个目前都是ok的。

我是用的Qwen1.5-14B-Chat 、用的react模板写的纯文本生成方式，自己解析结果。
现在主要是打印出来在前端不太好看，不过我们可以自己做一些处理来规避这个问题。

其实想想也挺正常的，上下文比较长的时候，基于函数的功能，额外生成一些可能用到的参数完全能理解。
