### ISSUE TITLE
这个qwenagent和我本地部署的qwen 的api，怎么适配？有Bug，怎么启动qwen的api?

### ISSUE THREAD

**Issue by GoogleAlphaZero** [QwenLM/Qwen-Agent#95]

**Comment by JianxinMa** [comment]
推荐使用 vLLM 或 ollama 获得兼容 openai 的 api。

如果您使用的是 ollama：

安装好 ollama 后，命令行中启动；
```
ollama serve
```
再执行如下命令拉取0.5b的qwen1.5（0.5b可以改成你想要的具体的模型大小，注意看ollama文档）：
```
ollama run qwen:0.5b
# 然后 /bye 退出
```

之后，如果您是要使用 browserQwen 应用，则执行（注意此时不要关闭 ollama serve）：
```
python run_server.py --llm qwen:0.5b --model_server http://127.0.0.1:11434/v1
```

如果您是要使用 qwen_agent 框架开发，则 llm_cfg 可以如下：
```py
from qwen_agent.llm import get_chat_model

llm_cfg = {
    'model': 'qwen:0.5b',
    'model_server': 'http://127.0.0.1:11434/v1',
    'api_key': 'ollama',
}
llm = get_chat_model(llm_cfg)
```
qwen_agent更多用法常见 examples目录。

参考资料：
- 安装ollama：https://github.com/ollama/ollama/tree/main
- ollama的openai接口：https://github.com/ollama/ollama/blob/main/docs/openai.md

如果您想使用 vLLM 提供openai服务，用法也是类似的。如果依然遇到报错可以贴在本 issue，我们排查下。

**Comment by GoogleAlphaZero** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by GoogleAlphaZero** [comment]
请问，这个qwen用的是qwen1.5还是千问1.0？
因为我发现qwen1.0的README内自带的部署api（即不用ollama和vllm），是和qwen-agent不适配的。

**Comment by JianxinMa** [comment]
> 请问，这个qwen用的是qwen1.5还是千问1.0？ 因为我发现qwen1.0的README内自带的部署api（即不用ollama和vllm），是和qwen-agent不适配的。

默认qwen1.5。qwen1已经不维护了。

**Comment by GoogleAlphaZero** [comment]
谢谢，醍醐灌顶
