### ISSUE TITLE
你README上给的demo，提示词是查询天气再画一张图。用户怎么问（user query）比较好？

### ISSUE THREAD

**Issue by GoogleAlphaZero** [QwenLM/Qwen-Agent#96]
尽管提示词中给的是让它查天气和作图，但use query输入：“查询北京的天气？”时，它只调用一个function（查天气），不会调用第二个function（作图）。
我必须user query为，”北京的天气如何，并绘制图片“，才调用天气+绘图，2个函数

用户怎么提问比较好？
感谢

**Comment by GoogleAlphaZero** [comment]
怎么设计提示词和user query比较好？
可否再举例一个
因为我想把它迁移到我的场景，并有好的效果

**Comment by JianxinMa** [comment]
可以在system_message里提供一些要求（system_message可以看做是对agent的人设要求），比如在system_message里要求模型每次回答完都要画图、甚至可以在system里提供一些问答示例让模型的效果更稳定。一个参考例子：https://github.com/QwenLM/Qwen-Agent/blob/main/examples/assistant_growing_girl.py#L15

**Comment by GoogleAlphaZero** [comment]
谢谢，懂了

**Comment by Lxhnnn** [comment]
> 可以在system_message里提供一些要求（system_message可以看做是对agent的人设要求），比如在system_message里要求模型每次回答完都要画图、甚至可以在system里提供一些问答示例让模型的效果更稳定。一个参考例子：https://github.com/QwenLM/Qwen-Agent/blob/main/examples/assistant_growing_girl.py#L15

这个例子怎么找不到了

**Comment by GoogleAlphaZero** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
