### ISSUE TITLE
qwen Chat模型无法调用function calling

### ISSUE THREAD

**Issue by l-besiege-l** [QwenLM/Qwen-Agent#99]
使用灵积服务的chat模型（qwen-72b-chat等）无法正常调用定义的function工具
![image](https://github.com/QwenLM/Qwen-Agent/assets/52117792/b98a1023-34fd-4d95-80b4-7008fbc210e2)
使用灵积服务的qwen-turbo、qwen-max则可以正常调用function工具
![image](https://github.com/QwenLM/Qwen-Agent/assets/52117792/05341e65-0ab5-4fac-833c-ef618776a681)

**Comment by JianxinMa** [comment]
目前框架的fn call功能是针对 qwen1.5系列及之后 写的。不适用于 qwen1，qwen1应该只适合用  react agent（框架有提供）

**Comment by JianxinMa** [comment]
请参考 https://github.com/QwenLM/Qwen1.5 的 README 使用 qwen1.5（ollama或vllm均可提供openai接口）。

**Comment by l-besiege-l** [comment]
感谢大佬的回复，请问qwen-turbo、qwen-max实际上是可以归属于qwen1.5系列是吧，那么灵积服务未来会提供qwen1.5的开源系chat模型吗（7B、14B、72B等），我看了一下现在开源chat模型都是v1版本的

**Comment by JianxinMa** [comment]
> 感谢大佬的回复，请问qwen-turbo、qwen-max实际上是可以归属于qwen1.5系列是吧，那么灵积服务未来会提供qwen1.5的开源系chat模型吗（7B、14B、72B等），我看了一下现在开源chat模型都是v1版本的

qwen-turbo、qwen-max实际上是可以归属于qwen1.5系列是吧？—— 可以这么理解。

灵积服务未来会提供qwen1.5的开源系chat模型吗（7B、14B、72B等）—— 应该已经提供了，见 https://help.aliyun.com/zh/dashscope/developer-reference/tongyi-qianwen-7b-14b-72b-api-detailes?disableWebsiteRedirect=true#BQnl3 调用dashscope填 `dashscope.Generation.call(model='qwen1.5-72b-chat', ...)` 即可。

**Comment by l-besiege-l** [comment]
好的，十分感谢

**Comment by jiangix-paper** [comment]
你好，如果是本地通过vllm部署qwen1.5 chat模型。想调用function calling函数，需要自己在prompt中拼装function calling的格式吗？如果是的话，具体的prompt是怎样的呢？
还是说可以直接通过vllm的openai接口传入function calling呢

希望收到您的回复，非常感谢

**Comment by JianxinMa** [comment]
> 你好，如果是本地通过vllm部署qwen1.5 chat模型。想调用function calling函数，需要自己在prompt中拼装function calling的格式吗？如果是的话，具体的prompt是怎样的呢？ 还是说可以直接通过vllm的openai接口传入function calling呢
> 
> 希望收到您的回复，非常感谢

vllm的接口即使传了functions也不会生效，它的内部没有相关实现。

关于prompt是什么样的，可以参考 https://github.com/QwenLM/Qwen-Agent/blob/main/qwen_agent/llm/function_calling.py#L271
